// Texture definitions generated by SLADE3
// on Wed Aug 12 10:06:52 2026

Sprite "OL00C0", 190, 330
{
	XScale 2.000
	YScale 2.400
	Offset -188, -216
	Patch "OL00C0", 0, 0
}

Sprite "OL00D0", 244, 425
{
	XScale 2.000
	YScale 2.400
	Offset -202, -121
	Patch "OL00D0", 0, 0
}

Sprite "OL00E0", 302, 430
{
	XScale 2.000
	YScale 2.400
	Offset -164, -116
	Patch "OL00E0", 0, 0
}

Sprite "OL00F0", 299, 422
{
	XScale 2.000
	YScale 2.400
	Offset -166, -124
	Patch "OL00F0", 0, 0
}

Sprite "OL00G0", 588, 272
{
	XScale 2.000
	YScale 2.400
	Offset -155, -274
	Patch "OL00G0", 0, 0
}

Sprite "OL00H0", 517, 292
{
	XScale 2.000
	YScale 2.400
	Offset -155, -254
	Patch "OL00H0", 0, 0
}

Sprite "OL00I0", 918, 330
{
	XScale 2.000
	YScale 2.400
	Offset -78, -216
	Patch "OL00I0", 0, 0
}

Sprite "OL00J0", 799, 423
{
	XScale 2.000
	YScale 2.400
	Offset -72, -123
	Patch "OL00J0", 0, 0
}

Sprite "OL01A0", 268, 256
{
	XScale 2.000
	YScale 2.400
	Offset -238, -272
	Patch "OL01A0", 0, 0
}

Sprite "OL01B0", 281, 354
{
	XScale 2.000
	YScale 2.400
	Offset -200, -174
	Patch "OL01B0", 0, 0
}

Sprite "OL01C0", 331, 373
{
	XScale 2.000
	YScale 2.400
	Offset -155, -155
	Patch "OL01C0", 0, 0
}

Sprite "OL01D0", 351, 369
{
	XScale 2.000
	YScale 2.400
	Offset -155, -159
	Patch "OL01D0", 0, 0
}

Sprite "OL01E0", 506, 293
{
	XScale 2.000
	YScale 2.400
	Offset 50, -235
	Patch "OL01E0", 0, 0
}

Sprite "OL01F0", 625, 288
{
	XScale 2.000
	YScale 2.400
	Offset 169, -240
	Patch "OL01F0", 0, 0
}

Sprite "OL02A0", 317, 278
{
	XScale 2.000
	YScale 2.400
	Offset -210, -260
	Patch "OL02A0", 0, 0
}

Sprite "OL02B0", 353, 419
{
	XScale 2.000
	YScale 2.400
	Offset -201, -119
	Patch "OL02B0", 0, 0
}

Sprite "OL02C0", 403, 392
{
	XScale 2.000
	YScale 2.400
	Offset -160, -146
	Patch "OL02C0", 0, 0
}

Sprite "OL02D0", 371, 392
{
	XScale 2.000
	YScale 2.400
	Offset -156, -146
	Patch "OL02D0", 0, 0
}

Sprite "OL02E0", 390, 236
{
	XScale 2.000
	YScale 2.400
	Offset -101, -302
	Patch "OL02E0", 0, 0
}

Sprite "OL02F0", 278, 236
{
	XScale 2.000
	YScale 2.400
	Offset -196, -302
	Patch "OL02F0", 0, 0
}

Sprite "OL03A0", 169, 317
{
	XScale 2.000
	YScale 2.400
	Offset -225, -221
	Patch "OL03A0", 0, 0
}

Sprite "OL03B0", 261, 435
{
	XScale 2.000
	YScale 2.400
	Offset -186, -103
	Patch "OL03B0", 0, 0
}

Sprite "OL03C0", 302, 430
{
	XScale 2.000
	YScale 2.400
	Offset -164, -108
	Patch "OL03C0", 0, 0
}

Sprite "OL03D0", 299, 422
{
	XScale 2.000
	YScale 2.400
	Offset -166, -116
	Patch "OL03D0", 0, 0
}

Sprite "OL03E0", 426, 289
{
	XScale 2.000
	YScale 2.400
	Offset -128, -249
	Patch "OL03E0", 0, 0
}

Sprite "OL03F0", 361, 289
{
	XScale 2.000
	YScale 2.400
	Offset -126, -249
	Patch "OL03F0", 0, 0
}

Sprite "OL04A0", 603, 362
{
	XScale 2.000
	YScale 2.400
	Offset 64, -225
	Patch "OL04A0", 0, 0
}

Sprite "OL04B0", 284, 423
{
	XScale 2.000
	YScale 2.400
	Offset -200, -164
	Patch "OL04B0", 1, 0
}

Sprite "OL04C0", 345, 430
{
	XScale 2.000
	YScale 2.400
	Offset -163, -157
	Patch "OL04C0", 0, 0
}

Sprite "OL04D0", 603, 422
{
	XScale 2.000
	YScale 2.400
	Offset 64, -165
	Patch "OL04D0", 0, 0
}

Sprite "OL04E0", 559, 343
{
	XScale 2.000
	YScale 2.400
	Offset 64, -185
	Patch "OL04E0", 0, 0
}

Sprite "OL04F0", 457, 285
{
	XScale 2.000
	YScale 2.400
	Offset -37, -243
	Patch "OL04F0", 0, 0
}

Sprite "OL04G0", 322, 323
{
	XScale 2.000
	YScale 2.400
	Offset -160, -84
	Patch "OL04G0", 0, 0
}

Sprite "OL04H0", 320, 357
{
	XScale 2.000
	YScale 2.400
	Offset -159, -50
	Patch "OL04H0", 0, 0
}

Sprite "OL05A0", 460, 234
{
	XScale 2.000
	YScale 2.400
	Offset -90, -269
	Patch "OL05A0", 0, 0
}

Sprite "OL05B0", 460, 334
{
	XScale 2.000
	YScale 2.400
	Offset -90, -169
	Patch "OL05B0", 0, 0
}

Sprite "OL05C0", 460, 357
{
	XScale 2.000
	YScale 2.400
	Offset -90, -146
	Patch "OL05C0", 0, 0
}

Sprite "OL06A0", 496, 280
{
	XScale 2.000
	YScale 2.400
	Offset -72, -220
	Patch "OL06A0", 0, 0
}

Sprite "OL06B0", 480, 319
{
	XScale 2.000
	YScale 2.400
	Offset -80, -181
	Patch "OL06B0", 0, 0
}

Sprite "OL06C0", 496, 350
{
	XScale 2.000
	YScale 2.400
	Offset -76, -150
	Patch "OL06C0", 0, 0
}

Sprite "OL07A0", 504, 274
{
	XScale 2.000
	YScale 2.400
	Offset -67, -229
	Patch "OL07A0", 0, 0
}

Sprite "OL07B0", 507, 308
{
	XScale 2.000
	YScale 2.400
	Offset -66, -195
	Patch "OL07B0", 0, 0
}

Sprite "OL07C0", 504, 292
{
	XScale 2.000
	YScale 2.400
	Offset -67, -211
	Patch "OL07C0", 0, 0
}

Sprite "OL08A0", 252, 305
{
	XScale 2.000
	YScale 2.400
	Offset 34, -133
	Patch "OL08A0", 0, 0
}

Sprite "OL08B0", 627, 135
{
	XScale 2.000
	YScale 2.400
	Offset -310, -173
	Patch "OL08B0", 0, 0
}

Sprite "OL08C0", 554, 318
{
	XScale 2.000
	YScale 2.400
	Offset 213, -120
	Patch "OL08C0", 0, 0
}

Sprite "OL08D0", 392, 310
{
	XScale 2.000
	YScale 2.400
	Offset 76, -144
	Patch "OL08D0", 0, 0
}

Sprite "OL09A0", 367, 214
{
	XScale 2.000
	YScale 2.400
	Offset 42, -219
	Patch "OL09A0", 0, 0
}

Sprite "OL09B0", 712, 374
{
	XScale 2.000
	YScale 2.400
	Offset 27, -59
	Patch "OL09B0", 0, 0
}

Sprite "OL09C0", 671, 197
{
	XScale 2.000
	YScale 2.400
	Offset -273, -118
	Patch "OL09C0", 0, 0
}

Sprite "OL09D0", 441, 318
{
	XScale 2.000
	YScale 2.400
	Offset 97, -115
	Patch "OL09D0", 0, 0
}

Sprite "OL09E0", 400, 220
{
	XScale 2.000
	YScale 2.400
	Offset 42, -213
	Patch "OL09E0", 0, 0
}

Sprite "OL09F0", 400, 220
{
	XScale 2.000
	YScale 2.400
	Offset 42, -213
	Patch "OL09F0", 0, 0
}

Sprite "OL09G0", 400, 220
{
	XScale 2.000
	YScale 2.400
	Offset 42, -213
	Patch "OL09G0", 0, 0
}

Sprite "OL09H0", 400, 220
{
	XScale 2.000
	YScale 2.400
	Offset 42, -213
	Patch "OL09H0", 0, 0
}

Sprite "OL09I0", 400, 220
{
	XScale 2.000
	YScale 2.400
	Offset 42, -213
	Patch "OL09I0", 0, 0
}

Sprite "OL10A0", 211, 288
{
	XScale 2.000
	YScale 2.400
	Offset -490, -166
	Patch "OL10A0", 0, 0
}

Sprite "OL10B0", 417, 290
{
	XScale 2.000
	YScale 2.400
	Offset 91, -164
	Patch "OL10B0", 0, 0
}

Sprite "OL10C0", 220, 216
{
	XScale 2.000
	YScale 2.400
	Offset 64, -238
	Patch "OL10C0", 0, 0
}

Sprite "OL10D0", 417, 290
{
	XScale 2.000
	YScale 2.400
	Offset -315, -164
	Patch "OL10D0", 0, 0
}

Sprite "OL10E0", 220, 216
{
	XScale 2.000
	YScale 2.400
	Offset -490, -219
	Patch "OL10E0", 0, 0
}

Sprite "OL11A0", 54, 64
{
	XScale 1.200
	YScale 1.400
	Offset 26, 64
	Patch "OL11A0", 0, 0
}

Sprite "OL11B0", 45, 64
{
	XScale 1.200
	YScale 1.400
	Offset 21, 64
	Patch "OL11B0", 0, 0
}

Sprite "OL11C0", 31, 64
{
	XScale 1.200
	YScale 1.400
	Offset 14, 64
	Patch "OL11C0", 0, 0
}

Sprite "OL11D0", 14, 64
{
	XScale 1.200
	YScale 1.400
	Offset 6, 64
	Patch "OL11D0", 0, 0
}

Sprite "OL11E0", 13, 64
{
	XScale 1.200
	YScale 1.400
	Offset 7, 64
	Patch "OL11E0", 0, 0
}

Sprite "OL11F0", 30, 64
{
	XScale 1.200
	YScale 1.400
	Offset 16, 64
	Patch "OL11F0", 0, 0
}

Sprite "OL11G0", 44, 64
{
	XScale 1.200
	YScale 1.400
	Offset 23, 64
	Patch "OL11G0", 0, 0
}

Sprite "OL11H0", 54, 64
{
	XScale 1.200
	YScale 1.400
	Offset 28, 64
	Patch "OL11H0", 0, 0
}

Graphic "OL11G0", 54, 64
{
	XScale 2.200
	YScale 2.600
	Offset -8, -6
	Patch "OL11A0", 0, 0
}

Sprite "OL93J0", 32, 23
{
	XScale 1.200
	YScale 1.400
	Offset 17, 23
	Patch "OL93J0", 0, -3
}

Sprite "OL93A0", 48, 17
{
	XScale 1.200
	YScale 1.400
	Offset 24, 17
	Patch "OL93A0", 0, 0
}

Sprite "OL93B0", 71, 15
{
	XScale 1.200
	YScale 1.400
	Offset 35, 15
	Patch "OL93B0", 0, 0
}

Sprite "OL93C0", 83, 16
{
	XScale 1.200
	YScale 1.400
	Offset 41, 16
	Patch "OL93C0", 0, 0
}

Sprite "OL93D0", 52, 15
{
	XScale 1.200
	YScale 1.400
	Offset 26, 15
	Patch "OL93D0", 0, 0
}

Sprite "OL93E0", 69, 12
{
	XScale 1.200
	YScale 1.400
	Offset 34, 12
	Patch "OL93E0", 0, 0
}

Sprite "OL93F1", 57, 64
{
	XScale 1.200
	YScale 1.400
	Offset 29, 59
	Patch "OL93F1", 0, 0
}

Sprite "OL93F2", 64, 71
{
	XScale 1.200
	YScale 1.400
	Offset 33, 59
	Patch "OL93F2", 0, 0
}

Sprite "OL93F3", 69, 72
{
	XScale 1.200
	YScale 1.400
	Offset 34, 58
	Patch "OL93F3", 0, 0
}

Sprite "OL93F4", 67, 68
{
	XScale 1.200
	YScale 1.400
	Offset 34, 57
	Patch "OL93F4", 0, 0
}

Sprite "OL93F5", 56, 60
{
	XScale 1.200
	YScale 1.400
	Offset 29, 56
	Patch "OL93F5", 0, 0
}

Sprite "OL93F6", 66, 68
{
	XScale 1.200
	YScale 1.400
	Offset 34, 57
	Patch "OL93F6", 0, 0
}

Sprite "OL93F7", 69, 71
{
	XScale 1.200
	YScale 1.400
	Offset 36, 57
	Patch "OL93F7", 0, 0
}

Sprite "OL93F8", 64, 71
{
	XScale 1.200
	YScale 1.400
	Offset 32, 59
	Patch "OL93F8", 0, 0
}

Sprite "OL93G1", 32, 68
{
	XScale 1.200
	YScale 1.400
	Offset 20, 61
	Patch "OL93G1", 0, 0
}

Sprite "OL93G2", 70, 71
{
	XScale 1.200
	YScale 1.400
	Offset 50, 61
	Patch "OL93G2", 0, 0
}

Sprite "OL93G3", 78, 68
{
	XScale 1.200
	YScale 1.400
	Offset 50, 61
	Patch "OL93G3", 0, 0
}

Sprite "OL93G4", 54, 66
{
	XScale 1.200
	YScale 1.400
	Offset 28, 60
	Patch "OL93G4", 0, 0
}

Sprite "OL93G5", 30, 69
{
	XScale 1.200
	YScale 1.400
	Offset 10, 60
	Patch "OL93G5", 0, 0
}

Sprite "OL93G6", 54, 66
{
	XScale 1.200
	YScale 1.400
	Offset 26, 60
	Patch "OL93G6", 0, 0
}

Sprite "OL93G7", 78, 67
{
	XScale 1.200
	YScale 1.400
	Offset 28, 60
	Patch "OL93G7", 0, 0
}

Sprite "OL93G8", 70, 71
{
	XScale 1.200
	YScale 1.400
	Offset 20, 61
	Patch "OL93G8", 0, 0
}

Sprite "OL93H1", 49, 69
{
	XScale 1.200
	YScale 1.400
	Offset 25, 62
	Patch "OL93H1", 0, 0
}

Sprite "OL93H2", 46, 73
{
	XScale 1.200
	YScale 1.400
	Offset 28, 61
	Patch "OL93H2", 0, 0
}

Sprite "OL93H3", 52, 69
{
	XScale 1.200
	YScale 1.400
	Offset 24, 60
	Patch "OL93H3", 0, 0
}

Sprite "OL93H4", 49, 68
{
	XScale 1.200
	YScale 1.400
	Offset 28, 61
	Patch "OL93H4", 0, 0
}

Sprite "OL93H5", 43, 71
{
	XScale 1.200
	YScale 1.400
	Offset 21, 61
	Patch "OL93H5", 0, 0
}

Sprite "OL93H6", 50, 68
{
	XScale 1.200
	YScale 1.400
	Offset 20, 61
	Patch "OL93H6", 0, 0
}

Sprite "OL93H7", 52, 69
{
	XScale 1.200
	YScale 1.400
	Offset 26, 60
	Patch "OL93H7", 0, 0
}

Sprite "OL93H8", 46, 72
{
	XScale 1.200
	YScale 1.400
	Offset 17, 61
	Patch "OL93H8", 0, 0
}

Sprite "OL99A0", 2, 2
{
	XScale 2.000
	YScale 2.400
	Offset 1, 1
	Patch "OL99A0", 0, 0
}

Graphic "OLBART", 856, 31
{
	XScale 2.000
	YScale 2.400
	Offset 108, 0
	Patch "OLBART", 0, 0
}

Graphic "OLBARTR", 856, 73
{
	XScale 2.000
	YScale 2.400
	Offset 108, 0
	Patch "OLBARTR", 0, 0
	{
		Alpha 0.50
		Style Translucent
	}
}

Graphic "OLBAR", 856, 77
{
	XScale 2.000
	YScale 2.400
	Offset 108, 0
	Patch "OLBAR", 0, 0
}

Graphic "OLNUM30", 19, 36
{
	XScale 2.000
	YScale 2.400
	Patch "OLNUM30", 0, 0
}

Graphic "OLNUM31", 19, 36
{
	XScale 2.000
	YScale 2.400
	Patch "OLNUM31", 0, 0
}

Graphic "OLNUM32", 19, 36
{
	XScale 2.000
	YScale 2.400
	Patch "OLNUM32", 0, 0
}

Graphic "OLNUM33", 19, 36
{
	XScale 2.000
	YScale 2.400
	Patch "OLNUM33", 0, 0
}

Graphic "OLNUM34", 19, 36
{
	XScale 2.000
	YScale 2.400
	Patch "OLNUM34", 0, 0
}

Graphic "OLNUM35", 19, 36
{
	XScale 2.000
	YScale 2.400
	Patch "OLNUM35", 0, 0
}

Graphic "OLNUM36", 19, 36
{
	XScale 2.000
	YScale 2.400
	Patch "OLNUM36", 0, 0
}

Graphic "OLNUM37", 19, 36
{
	XScale 2.000
	YScale 2.400
	Patch "OLNUM37", 0, 0
}

Graphic "OLNUM38", 19, 36
{
	XScale 2.000
	YScale 2.400
	Patch "OLNUM38", 0, 0
}

Graphic "OLNUM39", 19, 36
{
	XScale 2.000
	YScale 2.400
	Patch "OLNUM39", 0, 0
}

Graphic "OLAMMZ1", 24, 24
{
	XScale 2.000
	YScale 2.400
	Patch "OLAMMZ1", 0, 0
}

Graphic "OLAMMZ2", 24, 24
{
	XScale 2.000
	YScale 2.400
	Patch "OLAMMZ2", 0, 0
}

Graphic "OLAMMZ3", 24, 24
{
	XScale 2.000
	YScale 2.400
	Patch "OLAMMZ3", 0, 0
}

Graphic "OLAMMZ4", 24, 24
{
	XScale 2.000
	YScale 2.400
	Patch "OLAMMZ4", 0, 0
}

Graphic "OLDEAD2", 26, 34
{
	XScale 2.000
	YScale 2.400
	Patch "OLDEAD2", 0, 0
}

Graphic "OLWPS1", 34, 66
{
	XScale 2.000
	YScale 2.400
	Patch "OLWPL1", 0, 0
}

Graphic "OLWPS2", 34, 66
{
	XScale 2.000
	YScale 2.400
	Patch "OLWPL2", 0, 0
}

Graphic "OLWPS3", 34, 66
{
	XScale 2.000
	YScale 2.400
	Patch "OLWPL3", 0, 0
}

Graphic "OLWPS3B", 34, 66
{
	XScale 2.000
	YScale 2.400
	Patch "OLWPL3B", 0, 0
}

Graphic "OLWPS4", 34, 66
{
	XScale 2.000
	YScale 2.400
	Patch "OLWPL4", 0, 0
}

Graphic "OLWPS5", 34, 66
{
	XScale 2.000
	YScale 2.400
	Patch "OLWPL5", 0, 0
}

Graphic "OLWPS6", 34, 66
{
	XScale 2.000
	YScale 2.400
	Patch "OLWPL6", 0, 0
}

Graphic "OLWPS7", 34, 66
{
	XScale 2.000
	YScale 2.400
	Patch "OLWPL7", 0, 0
}

Graphic "OLWPS8", 34, 66
{
	XScale 2.000
	YScale 2.400
	Patch "OLWPL8", 0, 0
}

// End of texture definitions
