//DB5 Stuff
Script "Goldfinger_BuildDB5" (void)
{
	int x = GetActorX(0);
	int y = GetActorY(0);
	int z = GetActorZ(0);
	int myTid = UniqueTid();
	Thing_ChangeTid(0,myTid);
	int partTid = UniqueTid();

	SpawnForced("Goldfinger_DB5_Collision_Front",x,y,z,partTid);
	SetActorAngle(partTid,GetActorAngle(0));
	SetPointerExt(AAPTR_Tracer,0,partTid);
	Thing_ChangeTid(partTid,0);

	SpawnForced("Goldfinger_DB5_Collision_Center",x,y,z,partTid);
	SetActorAngle(partTid,GetActorAngle(0));
	SetPointerExt(AAPTR_Tracer,0,partTid);
	Thing_ChangeTid(partTid,0);

	SpawnForced("Goldfinger_DB5_Collision_BackL",x,y,z,partTid);
	SetActorAngle(partTid,GetActorAngle(0));
	SetPointerExt(AAPTR_Tracer,0,partTid);
	Thing_ChangeTid(partTid,0);

	SpawnForced("Goldfinger_DB5_Collision_BackR",x,y,z,partTid);
	SetActorAngle(partTid,GetActorAngle(0));
	SetPointerExt(AAPTR_Tracer,0,partTid);
	Thing_ChangeTid(partTid,0);
	
	SpawnForced("Goldfinger_DB5_Collision_Roof",x,y,z,partTid);
	SetActorAngle(partTid,GetActorAngle(0));
	SetPointerExt(AAPTR_Tracer,0,partTid);
	Thing_ChangeTid(partTid,0);
	
	SpawnForced("Goldfinger_DB5_Body",x,y,z,partTid);
	SetActorAngle(partTid,GetActorAngle(0));
	SetPointerExt(AAPTR_Tracer,0,partTid);
	Thing_ChangeTid(partTid,0);
	
	SpawnForced("Goldfinger_DB5_Glass",x,y,z,partTid);
	SetActorAngle(partTid,GetActorAngle(0));
	SetPointerExt(AAPTR_Tracer,0,partTid);
	Thing_ChangeTid(partTid,0);
	
	SpawnForced("Goldfinger_DB5_Activator",x,y,z,partTid);
	SetActorAngle(partTid,GetActorAngle(0));
	SetPointerExt(AAPTR_Tracer,0,partTid);
	Thing_ChangeTid(partTid,0);
	
	SpawnForced("Goldfinger_DB5Suspension",GetActorX(0),GetActorY(0),GetActorZ(0),partTid);
	SetActorAngle(partTid,GetActorAngle(0));
	SetPointerExt(AAPTR_Tracer,0,partTid);
	SetPointerExt(AAPTR_Tracer,partTid,0);
	Thing_ChangeTid(partTid,0);
	
	SetActivator(partTid);
	Thing_ChangeTid(partTid,0);
}

Script "Goldfinger_DB5Activator" (void)
{
	int tankStart = timer();
	int yawStorage = GetActorAngle(0);
	int GZDoom = (GetCvar("samsara_zscriptready") > 0);
	int interpolate = WARPF_INTERPOLATE * GZDoom;
	ACS_NamedExecuteWithResult("Goldfinger_MoveDB5", interpolate);
	SetActivator(0,AAPTR_Target);
	GiveInventory("Goldeneye_TankForward",65536);
	GiveInventory("Goldeneye_TankSide",65536);
	while(CheckInventory("Goldeneye_UsingTank"))
	{
		//GiveInventory("SamsaraGoldenEyeTankProtection",1);
		SetPlayerProperty(0,1,PROP_FROZEN);
		if ((GetPlayerInput(-1,INPUT_BUTTONS) & BT_USE && timer() > (tankStart + 35) && !CheckInventory("BondWatchToken")) || isDead(0)) { TakeInventory("Goldeneye_UsingTank",1); }
		int playerYaw = GetPlayerInput(-1,INPUT_YAW);	
		int playerPitch = GetPlayerInput(-1,INPUT_PITCH);
		yawStorage += playerYaw;
		if(yawStorage > 1.0) yawStorage -= 1.0;
		if(yawStorage < 0.0) yawStorage += 1.0;
		SetInventory("Goldeneye_TankAngle",yawStorage);

		SetActorVelocity(0,0,0,0,0,0);
		Delay(1);
	}
	//TakeInventory("PowerSamsaraGoldenEyeTankProtection",1);
	SetPlayerProperty(0,0,PROP_FROZEN);
	TakeInventory("Goldeneye_TankForward",131072);
	TakeInventory("Goldeneye_TankSide",131072);
}

//mode, view height, attack z offset
Script "DB5ACSCompanion" (int mode, int value, int who)
{
	if(who != 0) SetActivator(0,who);
	switch(mode)
	{
		case 0:
			SetResultValue(GetActorProperty(0,APROP_ViewHeight));
			break;
		case 1:
			SetResultValue(GetActorProperty(0,APROP_AttackZOffset));
			break;
		case 2:
			SetActorProperty(0,APROP_ViewHeight,value);
			break;
		case 3:
			SetActorProperty(0,APROP_AttackZOffset,value);
			break;
		case 4:
			SetResultValue(GetActorProperty(0,APROP_SPECIES));
			break;
		case 5:
			SetActorProperty(0,APROP_Species,value);
			break;
		case 6:
			TakeInventory("Goldeneye_UsingTank",1);
			StopSound(0,CHAN_5);
			StopSound(0,CHAN_6);
			break;
		case 7:
			SetInventory("Goldfinger_DB5CarAngle",value+65536);
			break;
		case 8: 
			SetInventory("Goldfinger_DB5_WheelFRZ",value+65536); 
			break;
		case 9: 
			SetInventory("Goldfinger_DB5_WheelFLZ",value+65536);
			break;
		case 10: 
			SetInventory("Goldfinger_DB5_WheelBRZ",value+65536); 
			break;
		case 11: 
			SetInventory("Goldfinger_DB5_WheelBLZ",value+65536); 
			break;
		case 12: SetResultValue(GetActorZ(0)); break;
		case 13:
			Warp(0,0,0,value,0,WARPF_NOCHECKPOSITION);
			break;
		case 14: ChangeActorPitch(0,value,true); break;
		case 15: ChangeActorRoll(0,value,true); break;
		case 16: SetResultValue(GetActorPitch(0)); break;
		case 17: SetResultValue(GetActorRoll(0)); break;
		case 18: 
			int wheelFR = CheckInventory("Goldfinger_DB5_WheelFRZ")-65536;
			int wheelFL = CheckInventory("Goldfinger_DB5_WheelFLZ")-65536;
			int wheelBR = CheckInventory("Goldfinger_DB5_WheelBRZ")-65536;
			int wheelBL = CheckInventory("Goldfinger_DB5_WheelBLZ")-65536;
			int minWheelZ = min(wheelFR,min(wheelFL,min(wheelBR,wheelBL)))<<16;
			int averageOffset = ((wheelFR+wheelFL+wheelBR+wheelBL)/4)<<16;
			//PrintBold(s:"Class 2: ",s:GetActorClass(0));
			//PrintBold(d:CheckInventory("Goldfinger_DB5_WheelFRZFloor")+CheckInventory("Goldfinger_DB5_WheelFLZFloor")+CheckInventory("Goldfinger_DB5_WheelBRZFloor")+CheckInventory("Goldfinger_DB5_WheelBLZFloor"));
			if(CheckInventory("Goldfinger_DB5_WheelFRZFloor")+CheckInventory("Goldfinger_DB5_WheelFLZFloor")+CheckInventory("Goldfinger_DB5_WheelBRZFloor")+CheckInventory("Goldfinger_DB5_WheelBLZFloor")==0)
			{
				minWheelZ = 0;	
				averageOffset = 0;
			}
			/*PrintBold(s:"wheelFR: ",d:wheelFR);
			PrintBold(s:"wheelFL: ",d:wheelFL);
			PrintBold(s:"wheelBR: ",d:wheelBR);
			PrintBold(s:"wheelBL: ",d:wheelBL);
			PrintBold(s:"minWheelZ: ",d:minWheelZ);
			PrintBold(s:"actorZ: ",f:GetActorZ(0));
			PrintBold(s:"floorZ: ",f:GetActorFloorZ(0));
			PrintBold(s:"averageOffset: ",f:averageOffset);*/
			
			SetResultValue(minWheelZ + abs(averageOffset)); 
			break;
		case 19: SetInventory("Goldfinger_DB5CarPitch",value+65536); break;
		case 20: SetResultValue(CheckInventory("Goldfinger_DB5CarPitch")-65536);  break;
		case 21: SetActivator(0,AAPTR_TRACER); SetInventory("Goldfinger_DB5_WheelFRZFloor",value); break;
		case 22: SetActivator(0,AAPTR_TRACER); SetInventory("Goldfinger_DB5_WheelFLZFloor",value); break;
		case 23: SetActivator(0,AAPTR_TRACER); SetInventory("Goldfinger_DB5_WheelBRZFloor",value); break;
		case 24: SetActivator(0,AAPTR_TRACER); SetInventory("Goldfinger_DB5_WheelBLZFloor",value); break;
	}
}

Script "DB5UpdateCosmetics" (void)
{
	int myTid = UniqueTid();
	int GZDoom = (GetCvar("samsara_zscriptready") > 0);
	int interpolate = WARPF_INTERPOLATE * GZDoom;
	Thing_ChangeTid(0,myTid);
	while(ClassifyActor(0) > 1)
	{
		ChangeActorPitch(0,-ACS_NamedExecuteWithResult("DB5ACSCompanion",16,0,AAPTR_TRACER),true);
		if(gzdoom) ChangeActorRoll(0,ACS_NamedExecuteWithResult("DB5ACSCompanion",17,0,AAPTR_TRACER),true);
		//zpos = ACS_NamedExecuteWithResult("DB5ACSCompanion",18,0,AAPTR_TRACER)<<16
		Warp(AAPTR_TRACER,0,0,ACS_NamedExecuteWithResult("DB5ACSCompanion",18,0,AAPTR_TRACER),0,WARPF_USEPTR|WARPF_NOCHECKPOSITION|interpolate);
		Delay(1);
	}
}

Script "DB5UpdateSpecies" (void)
{
	ACS_NamedExecuteWithResult("DB5ACSCompanion",5,ACS_NamedExecuteWithResult("DB5ACSCompanion",4,0,AAPTR_TRACER));
}

Script "DB5PlayerAngle" (void)
{
	SetActivator(0,AAPTR_TARGET);
	SetActorAngle(0,CheckInventory("Goldeneye_TankAngle"));
}

Script "Goldfinger_MoveDB5" (int interpolate)
{
	int startingviewHeight = ACS_NamedExecuteWithResult("DB5ACSCompanion",0,0,AAPTR_TARGET);
	int startingattackOffset = ACS_NamedExecuteWithResult("DB5ACSCompanion",1,0,AAPTR_TARGET);
	str startingspecies = ACS_NamedExecuteWithResult("DB5ACSCompanion",4,0,AAPTR_TARGET);
	int db5Seed = PlayerNumber();
	while(ACS_NamedExecuteWithResult("Goldeneye_IsUsingTank"))
	{
		ACS_NamedExecuteWithResult("Goldfinger_DB5MoveInput",interpolate);	
		Warp(AAPTR_TRACER,0,0,0,0,WARPF_NOCHECKPOSITION|WARPF_USEPTR|interpolate);
		Warp(AAPTR_TARGET,-10.0,14.0,-20.0+ACS_NamedExecuteWithResult("DB5ACSCompanion",18,0,AAPTR_TRACER),0,WARPF_NOCHECKPOSITION|WARPF_MOVEPTR|WARPF_USEPTR|interpolate);
		ACS_NamedExecuteWithResult("DB5ACSCompanion",19,ACS_NamedExecuteWithResult("DB5ACSCompanion",16,0,AAPTR_TRACER),AAPTR_TARGET);
		ACS_NamedExecuteWithResult("DB5PlayerAngle",AAPTR_TRACER);
		ACS_NamedExecuteWithResult("DB5ACSCompanion",2,53.0,AAPTR_TARGET);
		ACS_NamedExecuteWithResult("DB5ACSCompanion",3,startingattackOffset+8.0,AAPTR_TARGET);
		ACS_NamedExecuteWithResult("DB5ACSCompanion",5,strparam(s:"DB5",d:db5Seed),AAPTR_TARGET);
		ACS_NamedExecuteWithResult("DB5ACSCompanion",5,strparam(s:"DB5",d:db5Seed),AAPTR_TRACER);
		ACS_NamedExecuteWithResult("DB5ACSCompanion",7,GetActorAngle(0)%1.0,AAPTR_TARGET);
		Delay(1);
	}
	TakeInventory("Goldeneye_UsingTank",1);
	ACS_NamedExecuteWithResult("DB5ACSCompanion",6,0,AAPTR_TRACER);
	SetActivator(0,AAPTR_TARGET);
	ACS_NamedExecuteWithResult("DB5ACSCompanion",2,startingviewHeight);
	ACS_NamedExecuteWithResult("DB5ACSCompanion",3,startingattackOffset);
	ACS_NamedExecuteWithResult("DB5ACSCompanion",5,startingspecies);
	
	//Fix player position when exiting
	if(!CheckInventory("Goldfinger_DB5EjectorSeat"))
	{
		if(!Warp(0,0,32.0,0,0,WARPF_MOVEPTR))
			if(!Warp(0,0,-80.0,0,0,WARPF_MOVEPTR))
				if(!Warp(0,80.0,0,0,0,WARPF_MOVEPTR))
					if(!Warp(0,-64.0,0,0,0,WARPF_MOVEPTR))
						Warp(0,0,0,40.0,0,WARPF_MOVEPTR);	
	}
	else
	{
		ThrustThingZ(0,72,0,1);
		Warp(0,0,0,40.0,0,WARPF_MOVEPTR);
	}
	TakeInventory("Goldfinger_DB5EjectorSeat",1);
}

Script "Goldfinger_DB5MoveInput" (int interpolate)
{
	int myTid = UniqueTid();
	Thing_ChangeTid(0,myTid);
	SetActivator(0,AAPTR_Target);

	int playerForward = GetPlayerInput(-1,INPUT_FORWARDMOVE)/16;
	int playerSideMove = GetPlayerInput(-1,INPUT_SIDEMOVE);
	int cruiseControl = GetPlayerInput(-1,INPUT_BUTTONS) & BT_JUMP;
	int accelerate = GetPlayerInput(-1,INPUT_FORWARDMOVE) > 2048;

	if(playerForward == 0)
	{
		playerForward = CheckInventory("Goldeneye_TankForward")-65536;
		playerForward = FixedMul(playerForward,0.98);
		
		if(abs(playerForward) <= 0.0125) playerForward = 0;
		
		SetInventory("Goldeneye_TankForward",playerForward+65536);
	}
	else
	{
		if(playerForward > 0)
		{
			int speedRatio = (1.0 - ((1.0*(CheckInventory("Goldeneye_TankForward")-65536) / 28000)));
			if(speedRatio < 0) speedRatio = 0;
			if(CheckInventory("Goldeneye_TankForward")-65536 < 28000 && !cruiseControl)
				GiveInventory("Goldeneye_TankForward",(playerForward*speedRatio)>>16);	
		}
		else
		{
			if(CheckInventory("Goldeneye_TankForward")-65536 > -12000)
				TakeInventory("Goldeneye_TankForward",abs(playerForward/2));
		}
		playerForward = CheckInventory("Goldeneye_TankForward")-65536;
		SetInventory("Goldeneye_TankForward",playerForward+65536);
	}

	if(playerSideMove == 0)
	{
		playerSideMove = CheckInventory("Goldeneye_TankSide")-65536;
		playerSideMove = FixedMul(playerSideMove,0.667);
		if(abs(playerSideMove) <= 3) playerSideMove = 0;
		SetInventory("Goldeneye_TankSide",playerSideMove+65536);
	}
	else
	{
		SetInventory("Goldeneye_TankSide",playerSideMove+65536);
	}

	if(abs(playerForward) > 1024 || abs(playerSideMove) > 1024 != 0)
	{
		SetActivator(myTid,AAPTR_Tracer);
		int angle = GetActorAngle(0);
		SetActivator(myTid,AAPTR_Target);
		SetInventory("Goldeneye_TankBaseAngle",angle);
		GiveInventory("Goldfinger_DB5DamageObjects",1);
	}

	SetActivator(myTid,AAPTR_Tracer);
	if(CheckInventory("Goldeneye_Tank_Blocked"))
	{
		TakeInventory("Goldeneye_Tank_Blocked",1);
		SetActivator(myTid,AAPTR_TARGET);
		SetInventory("Goldeneye_TankForward",65536);
		playerForward = 0;
		SetActivator(myTid,AAPTR_Tracer);
	}
	ACS_NamedExecuteWithResult("Goldfinger_DB5Move",playerForward,-playerSideMove,accelerate,interpolate);
	Thing_ChangeTid(myTid,0);
}

Script "Goldfinger_DB5Move" (int playerForward, int playerSideMove, int accelerate, int interpolate)
{
	int angle = GetActorAngle(0);
	int x = GetActorX(0);
	int y = GetActorY(0);
	int z = GetActorZ(0);
	int forwardOffset = 64/* + playerForward/500*/;
	int backwardOffset = 96;
	int sideOffset = 16;
	int dummyTid = UniqueTid();
	if(playerForward > 0)
	{
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x + (forwardOffset * cos(angle)),y + (forwardOffset * sin(angle)),z + 12.0,dummyTid)) playerForward = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x + (forwardOffset * cos(angle)) - (sideOffset * sin(angle)),y + (forwardOffset * sin(angle)) + (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerForward = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x + (forwardOffset * cos(angle)) + (sideOffset * sin(angle)),y + (forwardOffset * sin(angle)) - (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerForward = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x + (forwardOffset * cos(angle)) - (sideOffset * 2 * sin(angle)),y + (forwardOffset * sin(angle)) + (sideOffset * 2 * cos(angle)),z + 12.0,dummyTid)) playerForward = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x + (forwardOffset * cos(angle)) + (sideOffset * 2 * sin(angle)),y + (forwardOffset * sin(angle)) - (sideOffset * 2 * cos(angle)),z + 12.0,dummyTid)) playerForward = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		SetActorAngle(dummyTid,angle);
	}
	if(playerForward < 0)
	{
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x - (backwardOffset * cos(angle)),y - (backwardOffset * sin(angle)),z + 12.0,dummyTid)) playerForward = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x - (backwardOffset * cos(angle)) - (sideOffset * sin(angle)),y - (backwardOffset * sin(angle)) + (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerForward = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x - (backwardOffset * cos(angle)) + (sideOffset * sin(angle)),y - (backwardOffset * sin(angle)) - (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerForward = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x - (backwardOffset * cos(angle)) - (sideOffset * 2 * sin(angle)),y - (backwardOffset * sin(angle)) + (sideOffset * 2 * cos(angle)),z + 12.0,dummyTid)) playerForward = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x - (backwardOffset * cos(angle)) + (sideOffset * 2 * sin(angle)),y - (backwardOffset * sin(angle)) - (sideOffset * 2 * cos(angle)),z + 12.0,dummyTid)) playerForward = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		SetActorAngle(dummyTid,angle+0.5);
	}
	forwardOffset = 30;
	sideOffset = 36;
	if(playerSideMove > 0)
	{
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x - (sideOffset * sin(angle)),y + (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerSideMove = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x + (forwardOffset * cos(angle)) - (sideOffset * sin(angle)),y + (forwardOffset * sin(angle)) + (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerSideMove = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x + (forwardOffset * 2 * cos(angle)) - (sideOffset * sin(angle)),y + (forwardOffset * 2 * sin(angle)) + (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerSideMove = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x + (forwardOffset * 3 * cos(angle)) - (sideOffset * sin(angle)),y + (forwardOffset * 3 * sin(angle)) + (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerSideMove = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x - (forwardOffset * cos(angle)) - (sideOffset * sin(angle)),y - (forwardOffset * sin(angle)) + (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerSideMove = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x - (forwardOffset * 2 * cos(angle)) - (sideOffset * sin(angle)),y - (forwardOffset * 2 * sin(angle)) + (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerSideMove = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x - (forwardOffset * 3 * cos(angle)) - (sideOffset * sin(angle)),y - (forwardOffset * 3 * sin(angle)) + (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerSideMove = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		SetActorAngle(dummyTid,angle+0.25);
	}
	if(playerSideMove < 0)
	{
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x + (sideOffset * sin(angle)),y - (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerSideMove = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x + (forwardOffset * cos(angle)) + (sideOffset * sin(angle)),y + (forwardOffset * sin(angle)) - (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerSideMove = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x + (forwardOffset * 2 * cos(angle)) + (sideOffset * sin(angle)),y + (forwardOffset * 2 * sin(angle)) - (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerSideMove = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x + (forwardOffset * 3 * cos(angle)) + (sideOffset * sin(angle)),y + (forwardOffset * 3 * sin(angle)) - (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerSideMove = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x - (forwardOffset * cos(angle)) + (sideOffset * sin(angle)),y - (forwardOffset * sin(angle)) - (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerSideMove = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x - (forwardOffset * 2 * cos(angle)) + (sideOffset * sin(angle)),y - (forwardOffset * 2 * sin(angle)) - (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerSideMove = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		if(!Spawn("Goldfinger_DB5_CollisionBoundary",x - (forwardOffset * 3 * cos(angle)) + (sideOffset * sin(angle)),y - (forwardOffset * 3 * sin(angle)) - (sideOffset * cos(angle)),z + 12.0,dummyTid)) playerSideMove = 0;
		SetPointerExt(AAPTR_MASTER,0,dummyTid);
		SetActorAngle(dummyTid,angle-0.25);
	}
	
	Delay(1);
	SetActorAngle(0,angle+playerSideMove/16);
	if(accelerate) PlaySound(0,"Goldfinger/DB5/Move",CHAN_6,0.5,1,0.5);
	else { PlaySound(0,"Goldeneye/Tank/Idle",CHAN_5,0.25,1,0.5); StopSound(0,CHAN_6); }
	Thing_Remove(dummyTid);
	if(CheckInventory("Goldeneye_Tank_Blocked"))
	{
		playerForward = 0; 
		playerSideMove = 0;
		//TakeInventory("Goldeneye_Tank_Blocked",1);
	}
	else Warp(0,playerForward*60,0,0,0,WARPF_NOCHECKPOSITION|interpolate);
	
	//PrintBold(f:ACS_NamedExecuteWithResult("DB5ACSCompanion",18));
}

Script "SamsaraGoldfingerDB5AttackObject" (int coop)
{
	int partTid = UniqueTid();
	SpawnForced(coop ? "SamsaraGoldfingerDB5AttackObjectCoop" : "SamsaraGoldfingerDB5AttackObject",GetActorX(0)+cos(CheckInventory("Goldfinger_DB5CarAngle"))*84,GetActorY(0)+sin(CheckInventory("Goldfinger_DB5CarAngle"))*84,GetActorZ(0),partTid);
	SetActorAngle(partTid,CheckInventory("Goldfinger_DB5CarAngle"));
	SetActorProperty(partTid,APROP_Species,GetActorProperty(0,APROP_Species));
	SetPointerExt(AAPTR_Master,0,partTid);
	//Warp(partTid,84.0,0,0,CheckInventory("Goldfinger_DB5CarAngle"),WARPF_NOCHECKPOSITION|WARPF_ABSOLUTEANGLE|WARPF_MOVEPTR);
	SetActorPitch(partTid,-(CheckInventory("Goldfinger_DB5CarPitch")-65536));
	Thing_ChangeTid(partTid,0);
}

Script "Goldfinger_DB5_BuildSuspension" (void)
{
	int partTid = UniqueTid();
	int wheelFR, wheelFL, wheelBR, wheelBL;
	int vecF, vecB, vecR, vecL;
	int roll, pitch;
	
	SpawnForced("Goldfinger_DB5Suspension_WheelFR",0,0,0,partTid);
	SetPointerExt(AAPTR_Master,0,partTid);
	Thing_ChangeTid(partTid,0);
	
	SpawnForced("Goldfinger_DB5Suspension_WheelFL",0,0,0,partTid);
	SetPointerExt(AAPTR_Master,0,partTid);
	Thing_ChangeTid(partTid,0);
	
	SpawnForced("Goldfinger_DB5Suspension_WheelBR",0,0,0,partTid);
	SetPointerExt(AAPTR_Master,0,partTid);
	Thing_ChangeTid(partTid,0);
	
	SpawnForced("Goldfinger_DB5Suspension_WheelBL",0,0,0,partTid);
	SetPointerExt(AAPTR_Master,0,partTid);
	Thing_ChangeTid(partTid,0);
	
	while(ClassifyActor(0) > 1)
	{
		Warp(AAPTR_TRACER,0,0,0,0,WARPF_NOCHECKPOSITION|WARPF_USEPTR);
		wheelFR = (CheckInventory("Goldfinger_DB5_WheelFRZ")-65536)<<16;
		wheelFL = (CheckInventory("Goldfinger_DB5_WheelFLZ")-65536)<<16;
		wheelBR = (CheckInventory("Goldfinger_DB5_WheelBRZ")-65536)<<16;
		wheelBL = (CheckInventory("Goldfinger_DB5_WheelBLZ")-65536)<<16;
		
		vecF = (wheelFR + wheelFL)/2;
		vecB = (wheelBR + wheelBL)/2;
		vecR = (wheelFR + wheelBR)/2;
		vecL = (wheelFL + wheelBL)/2;
		pitch = VectorAngle(94.0,vecF - vecB);
		roll = VectorAngle(56.0,vecR - vecL);
		//PrintBold(s:"VecF: ",f:vecF);
		//PrintBold(s:"VecB: ",f:vecB);
		
		ACS_NamedExecuteWithResult("DB5ACSCompanion",14,-pitch,AAPTR_TRACER);
		ACS_NamedExecuteWithResult("DB5ACSCompanion",15,-roll,AAPTR_TRACER);
		
		ACS_NamedExecuteWithResult("DB5ACSCompanion",8,CheckInventory("Goldfinger_DB5_WheelFRZ")-65536,AAPTR_TRACER);
		ACS_NamedExecuteWithResult("DB5ACSCompanion",9,CheckInventory("Goldfinger_DB5_WheelFLZ")-65536,AAPTR_TRACER);
		ACS_NamedExecuteWithResult("DB5ACSCompanion",10,CheckInventory("Goldfinger_DB5_WheelBRZ")-65536,AAPTR_TRACER);
		ACS_NamedExecuteWithResult("DB5ACSCompanion",11,CheckInventory("Goldfinger_DB5_WheelBLZ")-65536,AAPTR_TRACER);
		
		Delay(1);
	}
}

Script "Goldfinger_DB5_WheelThink" (int wheel)
{
	int wheelX, wheelY, wheelZ, parentZ, diff;
	while(ClassifyActor(0) > 1)
	{
		parentZ = round(ACS_NamedExecuteWithResult("DB5ACSCompanion",12,0,AAPTR_MASTER));
		diff = GetActorFloorZ(0) - parentZ;
		
		if(abs(diff) <= 24.0)
			wheelZ = diff;
		else wheelZ = 0;
				
		switch(wheel)
		{
			case 1:
				wheelX = 48.0;
				wheelY = 28.0;
				break;
			case 2:
				wheelX = 48.0;
				wheelY = -28.0;	
				break;
			case 3:
				wheelX = -46.0;
				wheelY = 28.0;
				break;
			case 4:	
				wheelX = -46.0;
				wheelY = -28.0;
				break;
		}
		
		//PrintBold(s:"floorZ: ",f:GetActorFloorZ(0));
		//PrintBold(s:"parentZ: ",f:parentZ);
		//PrintBold(s:"Diff: ",d:diff>>16);
		ACS_NamedExecuteWithResult("DB5ACSCompanion",20+wheel,GetActorZ(0) - GetActorFloorZ(0) <= 1.0,AAPTR_MASTER);
		Warp(AAPTR_MASTER,wheelX,wheelY,wheelZ,0,WARPF_NOCHECKPOSITION|WARPF_USEPTR);
		ACS_NamedExecuteWithResult("DB5ACSCompanion",7+wheel,wheelZ>>16,AAPTR_MASTER);
		
		Delay(1);
	}
}
