str KingpinStateNames[9] = { "Pipe", "Pistol", "Crowbar", "Shotgun", "GrenadeLauncher", "Tommygun", "Bazooka", "Flamethrower", "HMG" };

//A decorate won't convert a decimal to a floating point as far as my knowledge goes, so it's up to the decorate to multiply the intended decimal by 65536
Script "Kingpin_FX" (int type, int duration, int maxSize)
{
	int i = 0;
	int startScaleX = GetActorProperty(0,APROP_ScaleX);
	int startScaleY = GetActorProperty(0,APROP_ScaleY);
	switch(type)
	{
		case 1:
			for(i = 0; i <= duration; i++)
			{
				//SetActorProperty(0,APROP_Alpha,(1.0/duration)*i);
				SetActorProperty(0,APROP_ScaleX,startScaleX+(maxSize/duration)*i);
				SetActorProperty(0,APROP_ScaleY,startScaleY+(maxSize/duration)*i);
				Delay(1);
			}
			for(i = duration; i >= 0; i--)
			{
				SetActorProperty(0,APROP_Alpha,(1.0/duration)*i);
				Delay(1);
			}
			Thing_Remove(0);
			break;
		case 2:
			for(i = 0; i <= duration; i++)
			{
				SetActorProperty(0,APROP_ScaleX,startScaleX+(maxSize/duration)*i);
				SetActorProperty(0,APROP_ScaleY,startScaleY+(maxSize/duration)*i);
				Delay(1);
			}
			Thing_Remove(0);
			break;
	}
}

Script "Kingpin_GrenadeFuse" (void)
{
	GiveInventory("Kingpin_GrenadeFuse",105);
	while(CheckInventory("Kingpin_GrenadeFuse") > 0)
	{
		TakeInventory("Kingpin_GrenadeFuse",1);
		Delay(1);
	}
}

Script "Kingpin_BloodGenerator_Offsets" (void)
{
	int missilex = GetActorX(0);
	int missiley = GetActorY(0);
	int missilez = GetActorZ(0);
	int missileAngle = GetActorAngle(0);
	SetActivator(0,AAPTR_Tracer);

	int enemyx = GetActorX(0);
	int enemyy = GetActorY(0);
	int enemyz = GetActorZ(0);
	int currentangle = GetActorAngle(0);
	int vang = VectorAngle(enemyx - missilex, enemyy - missiley);
	int angle = vang % 1.0;
	SetInventory("Kingpin_BloodGeneratorAngle",angle+65536);
	SetInventory("Kingpin_BloodGeneratorBleedAngle",missileAngle+65536);
	SetInventory("Kingpin_BloodGeneratorZ",(missilez - enemyz)>>16 + 65536);
}

Script "Kingpin_BloodGenerator_Return" (int mode)
{
	int result;
	switch(mode)
	{
		case 1:
			result = ((CheckInventory("Kingpin_BloodGeneratorAngle") - 65536)/182)+180;
			break;
		case 2:
			result = CheckInventory("Kingpin_BloodGeneratorZ");
			break;
		case 3:
			result = ((CheckInventory("Kingpin_BloodGeneratorBleedAngle") - 65536)/182);
			break;
	}
	SetResultValue(result);
}

Script "Kingpin_BloodPool" (void)
{
	int ownerTid = uniqueTid();
	SpawnForced("Kingpin_BloodPool",GetActorX(0),GetActorY(0),GetActorFloorZ(0),ownerTid);
	Thing_SetTranslation(ownerTid,-1);
	SetActivator(0,AAPTR_MASTER);
	SetPointerExt(AAPTR_MASTER,0,ownerTid);
	SetActorProperty(ownerTid,APROP_ScaleX,GetActorProperty(0,APROP_Radius)/20);
	Thing_ChangeTid(ownerTid,0);
}

#DEFINE KINGPINMAXTRAILS 64

Script "Kingpin_TrailLimiter" (void)
{
	int actorCount = ThingCountName(GetActorClass(0),0);
	if(actorCount > KINGPINMAXTRAILS)
		GiveInventory("Kingpin_TrailLimiter",actorCount > KINGPINMAXTRAILS * 2 ? 2 : 1);

}

Script "Kingpin_GibTransfer" (void)
{
	int gibTid = uniqueTid();
	int timerValue = CheckInventory("Kingpin_GibLifeSpan");
	int frame = CheckInventory("Kingpin_GibFrame");
	SpawnForced("Kingpin_GibStay",GetActorX(0),GetActorY(0),GetActorZ(0),gibTid);
	SetActorProperty(gibTid,APROP_ScaleX,GetActorProperty(0,APROP_ScaleX));
	SetActorProperty(gibTid,APROP_ScaleY,GetActorProperty(0,APROP_ScaleY));
	GiveActorInventory(gibTid,"Kingpin_GibLifeSpan",timerValue);
	GiveActorInventory(gibTid,"Kingpin_GibFrame",frame);
	Thing_SetTranslation(gibTid,-1);
	Thing_ChangeTid(gibTid,0);
}

Script "Kingpin_GibSpawner" (void)
{
	int gibTid = uniqueTid();
	int thisTid = uniqueTid();
	Thing_ChangeTid(0,thisTid);
	SetActivator(0,AAPTR_Master);
	int height = GetActorProperty(0,APROP_Height)*4;
	int radius = GetActorProperty(0,APROP_Radius);
	//Thing_Remove(0);
	SetActivator(thisTid);
	Thing_ChangeTid(thisTid,0);
	int gibScale = (((height>>16)*(radius>>16))<<16)/1120;
	int throwAngle, throwPitch, horzVelocity;
	for(int a = 0; a < radius/65536; a++)
	{
		throwAngle = random(0,1.0);
		throwPitch = random(-0.25,0.25);
		horzVelocity = 12*cos(throwPitch);
		SpawnForced("Kingpin_Gib",GetActorX(0)+random(-radius/2,radius/2),GetActorY(0)+random(-radius/2,radius/2),GetActorZ(0)+random(height/10,height-(height/10)),gibTid);
		SetActorVelocity(gibTid,FixedMul(horzVelocity,cos(throwAngle)),FixedMul(horzVelocity,sin(throwAngle)),12*sin(throwPitch),0,0);
		SetActorProperty(gibTid,APROP_ScaleX,gibScale);
		SetActorProperty(gibTid,APROP_ScaleY,gibScale);
		Thing_SetTranslation(gibTid,-1);
		Thing_ChangeTid(gibTid,0);
	}
}

Script "Kingpin_Player" (void)
{
	int currentplayeraction = 0;
	int playerStillMoving = 0;
	int actionValue = 0; //I need this to reduce duplicated code
	int UsingFullScreen = false;
	int startIndex = 45600;
	while(CheckInventory("KingpinClass"))
	{
		int velX = GetActorVelX(0)>>16;
		int velY = GetActorVelY(0)>>16;

		SetAmmoCapacity("Kingpin_TommyGunMagazine",50*(1+CheckInventory("Kingpin_TommyGun_MagazineCapacity")));
		SetAmmoCapacity("Kingpin_GrenadeLauncherMagazine",3*(1+CheckInventory("Kingpin_GrenadeLauncher_MagazineCapacity")));

		if (CheckInventory("SamsaraReloadMode") >= 2 && CheckInventory("SamsaraHasInfiniteAmmo") <= 1) { SetInventory("Kingpin_Shotgun_DoubleBarrelAlternate", CheckInventory("Kingpin_ShotgunMagazine") % 2); }

		if (GetCVar("screenblocks") == 11 && CheckInventory("SamsaraUsingNewFullscreenHUD"))
		{
			UsingFullScreen = true;
			ACS_NamedExecuteWithResult("Kingpin_DrawHud",startIndex,0,0,0);
		}
		//This is an optimization, instead of calling these a bunch of times, it should only need to call it once
		else if(UsingFullScreen == true)
		{
			RemoveMessages(startIndex,startIndex+40);
			UsingFullScreen = false;
		}

		int laserdelay;

		if(currentplayeraction >= 0)
		{
			if (CheckWeapon("Kingpin_Bazooka") && CheckInventory("Kingpin_Bazooka_LaserSystem"))
			{
				if (laserdelay > 0) { laserdelay -= 1 + CheckInventory("SamsaraHasDoubleFiringSpeed"); }

				if (laserdelay < 0) { laserdelay = 0; } // just in case

				if (GetPlayerInput(-1, INPUT_BUTTONS) & BT_ZOOM && laserdelay <= 0)
				{
					SetInventory("SamsaraKingpinBazookaLaserActivated", !CheckInventory("SamsaraKingpinBazookaLaserActivated"));
					laserdelay = 5;
				}

				if (CheckInventory("SamsaraKingpinBazookaLaserActivated"))
				{
					if (isSinglePlayer() || isCoop()) { LineAttack(0, GetActorAngle(0), GetActorPitch(0), 0, "Kingpin_Bazooka_LaserPuffCoop", "None", 8192.0, FHF_NORANDOMPUFFZ|FHF_NOIMPACTDECAL, 0); }
					else { LineAttack(0, GetActorAngle(0), GetActorPitch(0), 0, "Kingpin_Bazooka_LaserPuff", "None", 8192.0, FHF_NORANDOMPUFFZ|FHF_NOIMPACTDECAL, 0); }
				}
			}
			else { laserdelay = 0; }

			if(CheckInventory("Kingpin_ResetPlayerAction")) 
			{ 
				currentplayeraction = -1; 
				//SetInventory("Kingpin_ShootToken",0); 
				SetInventory("Kingpin_PlayerJumping",0); 
				SetInventory("Kingpin_LastWeapon",0); 
				SetInventory("Kingpin_ResetPlayerAction",0); 
				continue; 
			}	
			//Dead
			else if(ClassifyActor(0) & ACTOR_DEAD) 
			{
				//Do crouch death
				if(currentplayeraction >= 8)
					SetActorState(0,"CrouchDeath",true);
					
				//Do nothing, let the controller take over, for the time being
				currentplayeraction = -1;
				SetInventory("Kingpin_PlayerJumping",0); 
				SetInventory("Kingpin_LastWeapon",0); 
				SetInventory("Kingpin_ResetPlayerAction",0);
			} 
			//Jumping
			else if((GetPlayerInput(-1,INPUT_BUTTONS) & BT_JUMP) && !CheckInventory("Kingpin_PlayerJumping"))
			{
				if(CheckInventory("Kingpin_SelectedWeapon") != CheckInventory("Kingpin_LastWeapon") || currentplayeraction != 4)
				{
					currentplayeraction = 4;
					SetActorState(0,strparam(s:"Jump",s:KingpinStateNames[CheckInventory("Kingpin_SelectedWeapon")]),true);
					SetInventory("Kingpin_LastWeapon",CheckInventory("Kingpin_SelectedWeapon"));
				}
			}
			//Crouch Behavior
			else if(isCrouching(26.0) && !CheckInventory("Kingpin_PlayerJumping"))
			{
				if((GetPlayerInput(-1,MODINPUT_SIDEMOVE) != 0 || GetPlayerInput(-1,MODINPUT_FORWARDMOVE) != 0 || playerStillMoving > 0) ) 
				{
					if(GetPlayerInput(-1,MODINPUT_SIDEMOVE) != 0 || GetPlayerInput(-1,MODINPUT_FORWARDMOVE) != 0)
					{
						if(playerStillMoving < 16) 
							playerStillMoving+=2;
					}
					
					//We will always use this move animation...
					if(CheckInventory("Kingpin_SelectedWeapon") != CheckInventory("Kingpin_LastWeapon") || currentplayeraction != 9)
					{
						currentplayeraction = 9;
						SetActorState(0,strparam(s:"CrouchWalk",s:KingpinStateNames[CheckInventory("Kingpin_SelectedWeapon")]),true);
						SetInventory("Kingpin_LastWeapon",CheckInventory("Kingpin_SelectedWeapon"));
					}
				}
				else if(CheckInventory("Kingpin_ShootToken") && currentplayeraction != 10)
				{
					currentplayeraction = 10;
					SetActorState(0,strparam(s:"CrouchShoot",s:KingpinStateNames[CheckInventory("Kingpin_SelectedWeapon")]),true);
					SetInventory("Kingpin_LastWeapon",CheckInventory("Kingpin_SelectedWeapon"));
				}
				else if((CheckInventory("Kingpin_SelectedWeapon") != CheckInventory("Kingpin_LastWeapon") || currentplayeraction != 8) && !CheckInventory("Kingpin_ShootToken"))
				{
					currentplayeraction = 8;
					SetActorState(0,strparam(s:"Crouch",s:KingpinStateNames[CheckInventory("Kingpin_SelectedWeapon")]),true);
					SetInventory("Kingpin_LastWeapon",CheckInventory("Kingpin_SelectedWeapon"));
				}
			}
			//Movement
			else if((GetPlayerInput(-1,MODINPUT_SIDEMOVE) != 0 || GetPlayerInput(-1,MODINPUT_FORWARDMOVE) != 0 || playerStillMoving > 0) && !CheckInventory("Kingpin_PlayerJumping")) 
			{
				if(GetPlayerInput(-1,MODINPUT_SIDEMOVE) != 0 || GetPlayerInput(-1,MODINPUT_FORWARDMOVE) != 0)
				{
					if(playerStillMoving < 16) 
						playerStillMoving+=2;
				}
				
				//If the player is moving more forward than to the left or right, do this
				if(GetPlayerInput(-1,MODINPUT_FORWARDMOVE) != 0 && abs(GetPlayerInput(-1,MODINPUT_FORWARDMOVE)) > abs(GetPlayerInput(-1,MODINPUT_SIDEMOVE)))
				{
					if(sqrt(velX*velX + velY*velY)<<16 >= 8.0)
					{
						actionValue = CheckInventory("Kingpin_ShootToken") ? 7 : 1;
						if(CheckInventory("Kingpin_SelectedWeapon") != CheckInventory("Kingpin_LastWeapon") || currentplayeraction != actionValue)
						{
							currentplayeraction = actionValue;
							SetActorState(0,strparam(s:actionValue == 1 ? "See" : "RunShoot",s:KingpinStateNames[CheckInventory("Kingpin_SelectedWeapon")]),true);
							SetInventory("Kingpin_LastWeapon",CheckInventory("Kingpin_SelectedWeapon"));
						}
					}
					else
					{
						actionValue = CheckInventory("Kingpin_ShootToken") ? 8 : 5;
						if(CheckInventory("Kingpin_SelectedWeapon") != CheckInventory("Kingpin_LastWeapon") || currentplayeraction != actionValue)
						{
							currentplayeraction = actionValue;
							SetActorState(0,strparam(s:actionValue == 5 ? "Walk" : "WalkShoot",s:KingpinStateNames[CheckInventory("Kingpin_SelectedWeapon")]),true);
							SetInventory("Kingpin_LastWeapon",CheckInventory("Kingpin_SelectedWeapon"));
						}
					}
				}
				//Execute player controller code
				else if(GetPlayerInput(-1,MODINPUT_SIDEMOVE) < 0)
				{
					if(CheckInventory("Kingpin_SelectedWeapon") != CheckInventory("Kingpin_LastWeapon") || currentplayeraction != 3)
					{
						currentplayeraction = 3;
						SetActorState(0,strparam(s:"StrafeLeft",s:KingpinStateNames[CheckInventory("Kingpin_SelectedWeapon")]),true);
						SetInventory("Kingpin_LastWeapon",CheckInventory("Kingpin_SelectedWeapon"));
					}
				}
				else if(GetPlayerInput(-1,MODINPUT_SIDEMOVE) > 0)
				{
					if(CheckInventory("Kingpin_SelectedWeapon") != CheckInventory("Kingpin_LastWeapon") || currentplayeraction != 2)
					{
						currentplayeraction = 2;
						SetActorState(0,strparam(s:"StrafeRight",s:KingpinStateNames[CheckInventory("Kingpin_SelectedWeapon")]),true);
						SetInventory("Kingpin_LastWeapon",CheckInventory("Kingpin_SelectedWeapon"));
					}
				}
			}
			else if(CheckInventory("Kingpin_ShootToken") && !CheckInventory("Kingpin_PlayerJumping") && currentplayeraction != 6)
			{
				currentplayeraction = 6;
				SetActorState(0,strparam(s:"Shoot",s:KingpinStateNames[CheckInventory("Kingpin_SelectedWeapon")]),true);
				SetInventory("Kingpin_LastWeapon",CheckInventory("Kingpin_SelectedWeapon"));
			}
			else if((CheckInventory("Kingpin_SelectedWeapon") != CheckInventory("Kingpin_LastWeapon") || currentplayeraction != 0) && !CheckInventory("Kingpin_PlayerJumping") && !CheckInventory("Kingpin_ShootToken"))
			{
				currentplayeraction = 0;
				SetActorState(0,strparam(s:"Spawn",s:KingpinStateNames[CheckInventory("Kingpin_SelectedWeapon")]),true);
				SetInventory("Kingpin_LastWeapon",CheckInventory("Kingpin_SelectedWeapon"));
			}
			
			if(playerStillMoving > 0) playerStillMoving--;
			
			Delay(1);
		}
		else
		{
			if(ClassifyActor(0) & ACTOR_ALIVE)
				currentplayeraction = 0;

			laserdelay = 0;

			Delay(1);
		}
	}
}

str KingpinHUDWeapons[9][9] =
{
	{ "Kingpin_Pipe", "", "", "", "", "" },
	{ "Kingpin_Pistol", "Kingpin_PistolMagazine", "-1", "KPHWEAP1", "KPHAMMO1", "Kingpin_Pistol_Magnum", "Kingpin_Pistol_Reload", "Kingpin_Pistol_RateOfFire", "Kingpin_Pistol_Silencer" },
	{ "Kingpin_Crowbar", "", "", "KPHWEAP2", "", "", "", "", "" },
	{ "Kingpin_Shotgun", "Kingpin_ShotgunMagazine", "Shell", "KPHWEAP3", "KPHAMMO2", "Kingpin_Shotgun_Magazine", "Kingpin_Shotgun_DoubleBarrel", "Kingpin_Shotgun_SelectFire", "Kingpin_Shotgun_BleedShot" },
	{ "Kingpin_GrenadeLauncher", "Kingpin_GrenadeLauncherMagazine", "RocketAmmo", "KPHWEAP4", "KPHAMMO3", "Kingpin_GrenadeLauncher_ConcussionGrenades", "Kingpin_GrenadeLauncher_MagazineCapacity", "Kingpin_GrenadeLauncher_Fragmentation", "Kingpin_GrenadeLauncher_ClusterBombs" },
	{ "Kingpin_TommyGun", "Kingpin_TommyGunMagazine", "Clip", "KPHWEAP5", "KPHAMMO1", "Kingpin_TommyGun_MagazineCapacity", "Kingpin_TommyGun_Damage", "Kingpin_TommyGun_Accuracy", "Kingpin_TommyGun_Buzzsaw" },
	{ "Kingpin_Bazooka", "Kingpin_BazookaMagazine", "RocketAmmo", "KPHWEAP6", "KPHAMMO4", "Kingpin_Bazooka_LaserSystem", "Kingpin_Bazooka_FastRockets", "Kingpin_Bazooka_BigBubba", "Kingpin_Bazooka_HighExplosives" },
	{ "Kingpin_Flamethrower", "", "Cell", "KPHWEAP7", "KPHAMMO5", "Kingpin_Flamethrower_Range", "Kingpin_Flamethrower_FuelPump", "Kingpin_Flamethrower_HotterFlame", "Kingpin_Flamethrower_Napalmer" },
	{ "Kingpin_HMG", "Kingpin_HMGMagazine", "Cell", "KPHWEAP8", "KPHAMMO6", "Kingpin_HMG_SelectFire", "Kingpin_HMG_AntiMaterial", "Kingpin_HMG_CoolingRod", "Kingpin_HMG_TacticalScope" },
};

Script "Kingpin_DrawHud" (int startIndex)
{
	int offset, digit, i;
	int kp_cash = CheckInventory("Kingpin_Cash");
	int kp_cashDigits = strlen(strparam(d:kp_cash));
	int kp_health = GetActorProperty(0,APROP_Health);
	//Clamp from negative health
	if(kp_health < 0) kp_health = 0;
	int kp_healthDigits = strlen(strparam(d:kp_health));
	int kp_armor = CheckInventory("BasicArmor");
	int kp_armorDigits = strlen(strparam(d:kp_armor));
	int kp_kills = CheckInventory("KillCountAmount");
	int kp_killsDigits = strlen(strparam(d:kp_kills));
	int currentWeapon = CheckInventory("Kingpin_SelectedWeapon");
	
	//Set hud size. This seems pretty safe
	SetHudSize(800,600,0);	
	//Draw money icon
	SetFont("KPHMONEY");
	HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN|HUDMSG_ALPHA,startIndex+29,CR_UNTRANSLATED,700.2,28.0,0.0,0.33);
	//Draw money amount
	RemoveMessages(startIndex+24,startIndex+28);
	SetFont("KPHUDL");
	for(i = kp_cashDigits; i > 0; i--)
	{
		//Since these are aligned from the left, we need an offset for the drawing function
		offset = kp_cashDigits-i;
		//This formula will compute the current digit
		digit = (kp_cash % pow(10,i)) / pow(10,i-1);
		//Finally, draw the digit
		HudMessage(d:digit;HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN|HUDMSG_COLORSTRING,startIndex+24+offset,"KPGreenMoney",704.1 + (offset * 16.0),28.0 + (offset * 3.0),0.0);	
	}
	
	//Draw kills icon
	SetFont("KPHKILL");
	HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN|HUDMSG_ALPHA,startIndex+30,CR_UNTRANSLATED,700.2,72.0,0.0,0.33);
	//Draw money amount
	RemoveMessages(startIndex+31,startIndex+35);
	SetFont("KPHUDL");
	for(i = kp_killsDigits; i > 0; i--)
	{
		//Since these are aligned from the left, we need an offset for the drawing function
		offset = kp_killsDigits-i;
		//This formula will compute the current digit
		digit = (kp_kills % pow(10,i)) / pow(10,i-1);
		//Finally, draw the digit
		HudMessage(d:digit;HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN|HUDMSG_COLORSTRING,startIndex+31+offset,"KPRed",704.1 + (offset * 16.0),72.0 + (offset * 3.0),0.0);	
	}
	
	//Draw health amount
	RemoveMessages(startIndex+21,startIndex+23);
	SetFont("KPHUDL");
	for(i = kp_healthDigits; i > 0; i--)
	{
		//Since these are aligned from the left, we need an offset for the drawing function
		offset = kp_healthDigits-i;
		//This formula will compute the current digit
		digit = (kp_health % pow(10,i)) / pow(10,i-1);
		//Finally, draw the digit
		HudMessage(d:digit;HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+21+offset,CR_UNTRANSLATED,80.2 + (offset * 16.0),576.0 + (offset * 3.0),0.0);	
	}
	//Draw Health Icon - inconsistent placement, I know
	SetFont("KPHLIFE");
	HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN|HUDMSG_ALPHA,startIndex+20,CR_UNTRANSLATED,20.1,580.0,0.0,0.33);
	
	//Draw armor amount
	RemoveMessages(startIndex+17,startIndex+19);
	SetFont("KPHUDL");
	for(i = kp_armorDigits; i > 0; i--)
	{
		//Since these are aligned from the left, we need an offset for the drawing function
		offset = kp_armorDigits-i;
		//This formula will compute the current digit
		digit = (kp_armor % pow(10,i)) / pow(10,i-1);
		//Finally, draw the digit
		HudMessage(d:digit;HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+17+offset,CR_UNTRANSLATED,80.2 + (offset * 16.0),500.0 + (offset * 3.0),0.0);	
	}
	SetHudSize(960,640,0);	
	//Draw armor icon
	SetFont("KPHBODY");
	HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN|HUDMSG_ALPHA,startIndex+16,CR_UNTRANSLATED,80.2,580.2,0.0,0.33);
	SetFont("KPHARMOR");
	HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN|HUDMSG_ALPHA,startIndex+15,CR_UNTRANSLATED,80.2,580.2,0.0,kp_armor*1.0/100);
	//Draw armor outline, here
	if(kp_armor >= 150)
		SetFont("KPHARMB");
	else if(kp_armor >= 75)
		SetFont("KPHARMG");
	else if(kp_armor >= 50)
		SetFont("KPHARMY");
	else if(kp_armor >= 25)
		SetFont("KPHARMO");
	else if(kp_armor > 0)
		SetFont("KPHARMR");
	else
		RemoveMessages(startIndex+14,startIndex+14);
	if(kp_armor > 0) HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN|HUDMSG_ALPHA,startIndex+14,CR_UNTRANSLATED,80.2,580.2,0.0,0.5);
	SetHudSize(800,600,0);	
	
	//Draw ammo/weapon info
	SetFont("KPHUDL"); 
	//Draw total ammo
	RemoveMessages(startIndex+10,startIndex+13);
	if((StrCmp(KingpinHUDWeapons[currentWeapon][2], "") && StrCmp(KingpinHUDWeapons[currentWeapon][2], "-1")) || (!StrCmp(KingpinHUDWeapons[currentWeapon][2], "-1") && CheckInventory("PistolModeOn")))
	{
		int kp_ammo = CheckInventory(!StrCmp(KingpinHUDWeapons[currentWeapon][2], "-1") ? "Clip" : KingpinHUDWeapons[currentWeapon][2]);
		if(kp_ammo > 9999) kp_ammo = 9999;
		int kp_ammoDigits = strlen(strparam(d:kp_ammo));
		for(i = kp_ammoDigits; i > 0; i--)
		{
			//Since these are aligned from the left, we need an offset for the drawing function
			//This formula will compute the current digit
			digit = (kp_ammo % pow(10,i)) / pow(10,i-1);
			//Finally, draw the digit
			HudMessage(d:digit;HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+10+i,CR_UNTRANSLATED,760.2 - (i * 16.0),568.0 + (i * 3.0),0.0);	
		}
	}
	//Draw clip ammo
	RemoveMessages(startIndex+6,startIndex+9);
	if(StrCmp(KingpinHUDWeapons[currentWeapon][1], "") && CheckInventory("SamsaraReloadMode") >= 2)
	{
		int kp_clip = CheckInventory(KingpinHUDWeapons[currentWeapon][1]);
		if(kp_clip > 9999) kp_clip = 9999;
		int kp_clipDigits = strlen(strparam(d:kp_clip));
		for(i = kp_clipDigits; i > 0; i--)
		{
			//Since these are aligned from the left, we need an offset for the drawing function
			//This formula will compute the current digit
			digit = (kp_clip % pow(10,i)) / pow(10,i-1);
			//Finally, draw the digit
			HudMessage(d:digit;HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+6+i,CR_UNTRANSLATED,796.2 - (i * 16.0),524.0 + (i * 3.0),0.0);	
		}
	}
	//Draw ammo type icon
	if(strlen(KingpinHUDWeapons[currentWeapon][4]) > 0)
	{
		SetHudSize(1280,960,0);	
		SetFont(KingpinHUDWeapons[currentWeapon][4]); 
		HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+5,CR_UNTRANSLATED,1276.2,940.2,0.0);	
	}
	else RemoveMessages(startIndex+5,startIndex+5);
	//Draw weapon icon
	if(strlen(KingpinHUDWeapons[currentWeapon][3]) > 0)
	{
		SetHudSize(960,640,0);
		SetFont(KingpinHUDWeapons[currentWeapon][3]); 
		HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+4,CR_UNTRANSLATED,940.2,540.2,0.0);	
	}
	else RemoveMessages(startIndex+4,startIndex+4);
	//Finally, draw upgrades
	RemoveMessages(startIndex,startIndex+3);
	if(strlen(KingpinHUDWeapons[currentWeapon][5]) > 0 && CheckInventory(KingpinHUDWeapons[currentWeapon][5]))
	{
		SetHudSize(1280,960,0);	
		SetFont("KPUPGR1"); 
		HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+3,CR_UNTRANSLATED,1100.2,732.2,0.0);	
	}
	if(strlen(KingpinHUDWeapons[currentWeapon][6]) > 0 && CheckInventory(KingpinHUDWeapons[currentWeapon][6]))
	{
		SetHudSize(1280,960,0);	
		SetFont("KPUPGR2"); 
		HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+2,CR_UNTRANSLATED,1160.2,732.2,0.0);	
	}
	if(strlen(KingpinHUDWeapons[currentWeapon][7]) > 0 && CheckInventory(KingpinHUDWeapons[currentWeapon][7]))
	{
		SetHudSize(1280,960,0);	
		SetFont("KPUPGR3"); 
		HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+1,CR_UNTRANSLATED,1220.2,732.2,0.0);	
	}
	if(strlen(KingpinHUDWeapons[currentWeapon][8]) > 0 && CheckInventory(KingpinHUDWeapons[currentWeapon][8]))
	{
		SetHudSize(1280,960,0);	
		SetFont("KPUPGR4"); 
		HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex,CR_UNTRANSLATED,1280.2,732.2,0.0);	
	}
}

Script "Kingpin_RocketFlare" (void)
{
	int flareTid = uniqueTid();
	SpawnForced("Kingpin_RocketFlare",0,0,0,flareTid);
	SetPointerExt(AAPTR_MASTER,0,flareTid);
	Thing_ChangeTid(flareTid,0);
}

Script "Kingpin_Bazooka" (int type, int arg1, int arg2)
{
	int lTid;
	switch(type)
	{
		case 0:
			SetPointer(AAPTR_TRACER,arg1);
			break;
		case 1:
			int myTid = ActivatorTid();
			int missileTid = uniqueTid();
			Thing_ChangeTid(0,missileTid);
			SetActivator(0,AAPTR_Target);
			lTid = abs(CheckInventory("Kingpin_Bazooka_LaserTID"));
			SetActivator(missileTid);
			Thing_ChangeTid(missileTid,0);
			ACS_NamedExecuteWithResult("Kingpin_Bazooka",0,lTid);
			break;
		case 2:
			lTid = uniqueTid();
			SpawnForced("Kingpin_Bazooka_Seeker",GetActorX(0),GetActorY(0),GetActorZ(0),lTid);
			SetActivator(0,AAPTR_Target);
			SetInventory("Kingpin_Bazooka_LaserTID",0);
			GiveInventory("Kingpin_Bazooka_LaserTID",lTid);
			break;	
	}
}

Script "Kingpin_ThrowMoney" (void)
{
	int moneyTid = UniqueTid();
	int monsterHealth = GetActorProperty(0,APROP_SpawnHealth);
	str moneyActor = "Kingpin_CashPickup";
	if(monsterHealth >= 1000) moneyActor = "Kingpin_CashPickupBagS";
	else if(monsterHealth >= 500) moneyActor = "Kingpin_CashPickupBagS";
	SpawnForced(moneyActor,GetActorX(0),GetActorY(0),GetActorZ(0)+(GetActorProperty(0,APROP_Height)*2),moneyTid);
	SetActorAngle(moneyTid,random(0,1.0));
	SetActorVelocity(moneyTid,4*cos(GetActorAngle(moneyTid)),4*sin(GetActorAngle(moneyTid)),random(0,4.0),0,0);
	SetActorProperty(moneyTid, APROP_Accuracy, Random(1, monsterHealth / 10));
    Thing_ChangeTID(moneyTid, 0);
}

script "Kingpin_Flamethrower" (int normalcost, int fuelpumpcost)
{
    if (CheckInventory("Kingpin_Flamethrower_Hold")) { terminate; }

    if (CheckInventory("Cell") < (CheckInventory("Kingpin_Flamethrower_FuelPump") ? fuelpumpcost : normalcost) && !CheckInventory("SamsaraHasInfiniteAmmo")) { terminate; }

    if (CheckInventory("SamsaraCurrentWaterLevel") >= 3 && !CheckInventory("SamsaraCanFireWeaponsUnderwater")) { terminate; }

    GiveInventory("Kingpin_Flamethrower_Hold", 1);

    while (CheckWeapon("Kingpin_Flamethrower") && !isDead(0) && CheckInventory("Kingpin_Flamethrower_Hold"))
    {
        PlaySound(0, StrParam(s:"Kingpin/Flamethrower/Flame", d:((Timer() % 3)) + 1), CHAN_AUTO);
        GiveInventory("Kingpin_Flamethrower_FireTrigger", 1);
        Delay(1);
    }

    SetInventory("Kingpin_Flamethrower_Hold", 0);
}

Script "Kingpin_FlamethrowerDistance" (int px, int py, int pz)
{
	int rX = GetActorX(0)/65536 - px;
	int rY = GetActorY(0)/65536 - py;
	int rZ = GetActorZ(0)/65536 - pz;
	int result = sqrt(rX*rX + rY*rY + rZ*rZ);
	//PrintBold(s:"Trail Start X: ",d:px,s:"Trail Start Y: ",d:py,s:"Trail Start Z: ",d:pz,s:"\n",s:"Trail End X: ",d:GetActorX(0)>>16,s:"Trail End Y: ",d:GetActorY(0)>>16,s:"Trail End Z: ",d:GetActorZ(0)>>16);
	SetResultValue(result);
}

Script "Kingpin_ReturnUpgrade" (int upgrade)
{
	SetActivator(0,AAPTR_Target);
	switch(upgrade)
	{
		case 21:
			SetResultValue(CheckInventory("Kingpin_Flamethrower_Range"));
			break;
	}
}

Script "Kingpin_FlamethrowerTracer" (int upgrade)
{
	int myOldTid = ActivatorTid();
	int myTid = UniqueTid();
	Thing_ChangeTid(0, myTid);

	SetActivator(0,AAPTR_Tracer);

	int requiredIgnition = (ClassifyActor(0) & ACTOR_Player || ClassifyActor(0) & ACTOR_Bot ? 6 : CheckFlag(0,"NOBLOOD") ? 72 : 36)/upgrade;

	int actorClass = ClassifyActor(0);
	if(!(actorClass & ACTOR_ALIVE) && !(actorClass & ACTOR_MONSTER || (!isSinglePlayer() && !isCoop() && (isPlayerOrBot(0) || GetActorProperty(0, APROP_FRIENDLY)))))
		terminate;

	if(!CheckInventory("Kingpin_FlamethrowerHitTarget"))
	{
		if(!CheckInventory("Kingpin_FlamethrowerBurnt"))
		{
			GiveInventory("Kingpin_FlamethrowerHitTarget",1);
			GiveInventory("Kingpin_FlamethrowerIgnition",1);

			if(CheckInventory("Kingpin_FlamethrowerIgnition") >= requiredIgnition && !CheckInventory("Kingpin_FlamethrowerBurnt"))
			{
				bool isPVEGame = isSinglePlayer() || isCoop();

				//Gross hack for enemy gender
				int gender = -GetActorProperty(0,APROP_STAMINA);
				if(isPlayerOrBot(0)) gender = 0; // do not play sounds for players
				TakeInventory("Kingpin_FlamethrowerHitTarget",1);
				TakeInventory("Kingpin_FlamethrowerIgnition",50);
				GiveInventory("Kingpin_FlamethrowerBurnt",1);
				GiveInventory("Kingpin_FlamethrowerStacker",1);
				ACS_NamedExecuteWithResult("Kingpin_Decorate",8);
				int burnerTid = UniqueTid();
				if(gender == 2) PlaySound(0,"Kingpin/Flamethrower/BurnF",CHAN_AUTO,1.0,0,ATTN_NORM);
				else if(gender == 1) PlaySound(0,"Kingpin/Flamethrower/Burn",CHAN_AUTO,1.0,0,ATTN_NORM);
				SpawnForced(isPVEGame ? "Kingpin_FlamethrowerBurnerCoop" : "Kingpin_FlamethrowerBurner",GetActorX(0),GetActorY(0),GetActorZ(0),burnerTid);
				SetActivator(myTid,AAPTR_Target);
				SetPointerExt(AAPTR_Target,0,burnerTid);
				SetActivator(myTid,AAPTR_Tracer);
				SetPointerExt(AAPTR_Tracer,0,burnerTid);
				Thing_ChangeTid(myTid, myOldTid);
				terminate;
			}

			Thing_ChangeTid(myTid, myOldTid);
			Delay(1);
			TakeInventory("Kingpin_FlamethrowerHitTarget",1);

			Delay(105);
			if(!CheckInventory("Kingpin_FlamethrowerBurnt")) TakeInventory("Kingpin_FlamethrowerIgnition",1);
		}
		else
		{		
			GiveInventory("Kingpin_FlamethrowerHitTarget",1);
			GiveInventory("Kingpin_FlamethrowerIgnition",1);
			if(CheckInventory("Kingpin_FlamethrowerIgnition") >= requiredIgnition)
			{
				TakeInventory("Kingpin_FlamethrowerHitTarget",1);
				TakeInventory("Kingpin_FlamethrowerIgnition",50);
				GiveInventory("Kingpin_FlamethrowerStacker",1);
				Thing_ChangeTid(myTid, myOldTid);
				ACS_NamedExecuteWithResult("Kingpin_Decorate",8);
				terminate;
			}

			Thing_ChangeTid(myTid, myOldTid);
			Delay(1);
			TakeInventory("Kingpin_FlamethrowerHitTarget",1);

			Delay(105);
			if(!CheckInventory("Kingpin_FlamethrowerBurnt")) TakeInventory("Kingpin_FlamethrowerIgnition",1);
		}
	}
	else
		Thing_ChangeTid(myTid, myOldTid);
}

Script "Kingpin_EnemyBurn" (void)
{
	int radius = GetActorProperty(0,APROP_Radius)/4;
	int height = GetActorProperty(0,APROP_Height);
	While(CheckInventory("Kingpin_OnFire"))
	{
		SpawnForced("Kingpin_FlamethrowerFireVisual",GetActorX(0)+randSign()*radius,GetActorY(0)+randSign()*radius,GetActorZ(0)+random(0,height*4),0);
		Delay(2);
	}
}

Script "Kingpin_BurnHandler" (void)
{
	if(ACS_NamedExecuteWithResult("Kingpin_BurningOnPlayer"))
	{
		while(ACS_NamedExecuteWithResult("Kingpin_BurningPlayerIsAlive") && ClassifyActor(0) > 1)
		{
			if(ACS_NamedExecuteWithResult("Kingpin_Decorate",10) <= 0)
			{
				SetActorState(0,"Remove",1);
				terminate;
			}
			Delay(2);
		}
	}
	else
	{
		while(ACS_NamedExecuteWithResult("Kingpin_BurningPlayerIsAlive") && ClassifyActor(0) > 1)
		{
			if(ACS_NamedExecuteWithResult("Kingpin_Decorate",10) <= 0)
			{
				SetActorState(0,"Remove",1);
				terminate;
			}
			Delay(2);
		}
	}
}

Script "Kingpin_BurningPlayerIsAlive" (void)
{
	SetActivator(0,AAPTR_Tracer);
	if(ClassifyActor(0) & ACTOR_Alive)
		SetResultValue(1);
	else
		SetResultValue(0);
}

Script "Kingpin_BurningOnPlayer" (void)
{
	SetActivator(0,AAPTR_Tracer);
	if(ClassifyActor(0) & ACTOR_Player || ClassifyActor(0) & ACTOR_Bot)
	{
		//ACS_NamedExecuteWithResult("Kingpin_ScreenBurn");
		SetResultValue(1);
	}
	else
	{
		SetResultValue(0);
	}
}

Script "Kingpin_Decorate" (int type, int arg1, int arg2)
{
	int result;
	switch(type)
	{
		case 2:
			SetActivator(0,AAPTR_Target);
			SetResultValue(1+(2*CheckInventory("Kingpin_Flamethrower_HotterFlame")));
			break;
		case 5:
			if(GetActorProperty(0,APROP_Health) < -GetActorProperty(0,APROP_SpawnHealth)/((random(0,2)+(2+(GetActorProperty(0,APROP_SpawnHealth)/200)))))
				GiveInventory("Kingpin_SetGib",1);			
			SetResultValue(1);
			break;
		case 7:
			if(GetSectorLightLevel(0) < 64) SetActorState(0,"Light4",1);
			else if(GetSectorLightLevel(0) < 128) SetActorState(0,"Light3",1);
			else if(GetSectorLightLevel(0) < 192) SetActorState(0,"Light2",1);
			else SetActorState(0,"Light1",1);
			break;
		case 8:
			Delay(105);
			TakeInventory("Kingpin_FlamethrowerStacker",1);
			break;
		case 9: //Flamethrower burn visuals
			SetActivator(0,AAPTR_Tracer);
			if(arg1 == 0)
				SetResultValue(GetActorProperty(0,APROP_Radius)>>16);
			else
				SetResultValue(GetActorProperty(0,APROP_Height)>>16);
			break;
		case 10:
			SetActivator(0,AAPTR_Tracer);
			SetResultValue(CheckInventory("Kingpin_FlamethrowerStacker"));
			break;
		case 11:
			switch(arg1)
			{
				case 1:
					if(GetActorClass(0) == "Kingpin_Thug") SetActorState(0,"Next",1);
					break;
				case 2:
					if(GetActorClass(0) == "Kingpin_CashPickup") SetActorState(0,"Next",1);
					break;
				case 3:
					if(GetActorClass(0) == "Kingpin_CashPickupBagS") SetActorState(0,"Next",1);
					break;
				case 4:
					if(GetActorClass(0) == "Kingpin_CashPickupBagL") SetActorState(0,"Next",1);
					break;
			}
			break;
		case 12:
			if (CheckInventory("SamsaraReloadMode") >= 2 && CheckInventory("SamsaraHasInfiniteAmmo") <= 1) { SetInventory("Kingpin_Shotgun_DoubleBarrelAlternate", CheckInventory("Kingpin_ShotgunMagazine") % 2); }
			else
			{
				if (arg1 > 0) { SetInventory("Kingpin_Shotgun_DoubleBarrelAlternate", !CheckInventory("Kingpin_Shotgun_DoubleBarrelAlternate")); }
			}
			break;
	}
}

Script "Kingpin_ScopeClient" (void) clientside
{
	FadeTo(0.0,0.0,0.0,1.0,0);
	FadeTo(0.0,0.0,0.0,0.0,0.5);
	While(CheckInventory("Kingpin_HMG_ScopeActive"))
	{
		SetHudSize(256,256,0);
		SetFont("KPSCOPE");

		HudMessage(s:"a"; HUDMSG_PLAIN|HUDMSG_ALPHA|HUDMSG_NOTWITHFULLMAP|HUDMSG_LAYER_UNDERHUD, 1600, CR_UNTRANSLATED, 128.0, 128.0, 0, 1.0);

		Delay(1);
	}
	FadeTo(0.0,0.0,0.0,1.0,0);
	FadeTo(0.0,0.0,0.0,0.0,0.5);
	HudMessage(s:""; HUDMSG_PLAIN|HUDMSG_ALPHA|HUDMSG_NOTWITHFULLMAP|HUDMSG_LAYER_UNDERHUD, 1600, CR_UNTRANSLATED, 128.0, 128.0, 0.1, 0.0);
}

Script "Kingpin_BulletDamage" (int damage)
{
	int bulletX = GetActorX(0);
	int bulletY = GetActorY(0);
	int bulletZ = GetActorZ(0);

	SetActivator(0,AAPTR_Tracer);

	if(CheckFlag(0,"NOBLOOD")) { SetResultValue(damage); terminate; }

	int monsterX = GetActorX(0);
	int monsterY = GetActorY(0);
	int monsterZ = GetActorZ(0);
	int monsterHealth = GetActorProperty(0,APROP_Health);
	int monsterHeight = GetActorProperty(0,APROP_Height);
	int monsterWidth = GetActorProperty(0,APROP_Radius)*2;
	int health = GetActorProperty(0,APROP_SpawnHealth);

	/*if(CheckInventory("RTCW_MetalMonster"))
	{
		PlaySound(0,"RTCW/BulletHitMetal",CHAN_6,0.5,0,ATTN_NORM);
	}
	else
		PlaySound(0,"RTCW/BulletHitFlesh",CHAN_6,0.5,0,ATTN_NORM);*/

	if (health >= 1000)
	{
		SetResultValue(damage);
	}
	else if(monsterWidth >= monsterHeight && !CheckInventory("IsFatButBiped"))
	{
		int monsterAngle = GetActorAngle(0);
		int vang = VectorAngle(monsterX - bulletX, monsterY - bulletY);
		int angle = vang % 1.0;
				
		if(!CheckInventory("NoHeadShots") && bulletZ > monsterZ + FixedMul(monsterHeight,0.35) && bulletZ < monsterZ + FixedMul(monsterHeight,0.65) && ((abs(monsterAngle - angle)) < 0.65 && (abs(monsterAngle - angle)) > 0.35))
		{
			if(monsterHealth - (damage*2) <= -damage)
				GiveInventory("Kingpin_BloodHeadshotGenerator",1);
		
			SetResultValue(damage*2);
		}
		else
			SetResultValue(damage);
	}
	else
	{
		if(bulletZ > monsterZ + FixedMul(monsterHeight,0.75))
		{
			if(monsterHealth - (damage*2) <= -damage)
				GiveInventory("Kingpin_BloodHeadshotGenerator",1);
		
			int result;
			if(GetCvar("samsara_mixerloaded"))
				result = ACS_NamedExecuteWithResult("Goldeneye_HatShot",0,0,0,0);
			else
				result = 0;

			if(result == -1)
			{
				SetResultValue(-1);
				terminate;
			}
			//if(StrLeft(GetActorClass(0),4)=="RTCW" && GetCvar("samsara_mixerloaded"))
				//GiveInventory("RTCW_RemoveHat",1);
				

			SetResultValue(damage*2);
		}
		else
			SetResultValue(damage);
	}
}

Script "Kingpin_PawnOMatic_Initiate" (void) Net
{
	if(!CheckInventory("Kingpin_PawnOMaticOpen"))
	{
		if(!CheckInventory("CompendiumOpened"))
		{
			int sTid = uniqueTid();
			GiveInventory("Kingpin_PawnOMaticOpen",1);
			SetPlayerProperty(0,1,PROP_TOTALLYFROZEN);
			SpawnForced("Kingpin_PawnOMaticSoundController",0,0,0,sTid);
			SetInventory("Kingpin_PawnOMaticSoundTid",sTid);
			PlaySound(sTid,"PawnoMatic/Welcome",CHAN_VOICE,1.0,0,ATTN_NONE);
			
			ACS_NamedExecuteWithResult("Kingpin_PawnOMatic",PlayerNumber(),sTid);
		}
	}
	else
	{
		TakeInventory("Kingpin_PawnOMaticOpen",1);
		SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);
	}
}

str pawnOMaticItemOptions[2][8][2] =
{
	{ {"Clip", ""}, {"Shell", ""}, {"RocketAmmo", ""}, {"Cell", ""} },
	{ {"HealPack0", ""}, {"HealPack1", ""}, {"HealPack2", "PawnOMAtic/Medikit"}, {"SuperHealth", ""}, {"ArmorScrap", ""}, {"ArmorPack1", ""}, {"ArmorPack3", ""}, {"MegaPack", ""} },
};

//Number of options followed by prices
int pawnOMaticItemPrices[3][9] =
{
	{ 8, 1, 50, 150, 300, 200, 500, 400, 800 },
	{ 4, 2, 4, 10, 5 },
	{ 8, 5, 25, 50, 200, 5, 100, 250, 500 }
};

int pawnOMaticItemBulkBuy[2][8] =
{
	{ 1, 1, 1, 1 },
	{ 1, 0, 0, 0, 2 }
};

str pawnOMaticUpgradeOptions[7][4][2] =
{
	{ {"Kingpin_Pistol_Reload", "PawnOMAtic/Mod1/Reload"}, {"Kingpin_Pistol_RateOfFire", "PawnOMAtic/Mod1/RateOfFire"}, {"Kingpin_Pistol_Magnum", "PawnOMAtic/Mod1/Magnum"}, {"Kingpin_Pistol_Silencer", "PawnOMAtic/Mod1/Silencer"} },
	{ {"Kingpin_Shotgun_DoubleBarrel", "PawnOMAtic/Mod2/DoubleBarrel"}, {"Kingpin_Shotgun_BleedShot", "PawnOMAtic/Mod2/BleedShot"}, {"Kingpin_Shotgun_Magazine", "PawnOMAtic/Mod2/Magazine"}, {"Kingpin_Shotgun_SelectFire", "PawnOMAtic/Mod2/SelectFire"} },
	{ {"Kingpin_GrenadeLauncher_Fragmentation", "PawnOMAtic/Mod3/Fragmentation"}, {"Kingpin_GrenadeLauncher_ClusterBombs", "PawnOMAtic/Mod3/ClusterBombs"}, {"Kingpin_GrenadeLauncher_ConcussionGrenades", "PawnOMAtic/Mod3/ConcussionGrenades"}, {"Kingpin_GrenadeLauncher_MagazineCapacity", "PawnOMAtic/Mod3/MagazineCapacity"} },
	{ {"Kingpin_TommyGun_MagazineCapacity", "PawnOMAtic/Mod4/MagazineCapacity"}, {"Kingpin_TommyGun_Damage", "PawnOMAtic/Mod4/Damage"}, {"Kingpin_TommyGun_Accuracy", "PawnOMAtic/Mod4/Accuracy"}, {"Kingpin_TommyGun_Buzzsaw", "PawnOMAtic/Mod4/Buzzsaw"} },
	{ {"Kingpin_Bazooka_FastRockets", "PawnOMAtic/Mod5/FastRockets"}, {"Kingpin_Bazooka_LaserSystem", "PawnOMAtic/Mod5/LaserSystem"}, {"Kingpin_Bazooka_HighExplosives", "PawnOMAtic/Mod5/HighExplosives"}, {"Kingpin_Bazooka_BigBubba", "PawnOMAtic/Mod5/BigBubba"} },
	{ {"Kingpin_Flamethrower_Range", "PawnOMAtic/Mod6/Range"}, {"Kingpin_Flamethrower_HotterFlame", "PawnOMAtic/Mod6/HotterFlame"}, {"Kingpin_Flamethrower_FuelPump", "PawnOMAtic/Mod6/FuelPump"}, {"Kingpin_Flamethrower_Napalmer", "PawnOMAtic/Mod6/Napalmer"} },
	{ {"Kingpin_HMG_TacticalScope", "PawnOMAtic/Mod7/TacticalScope"}, {"Kingpin_HMG_CoolingRod", "PawnOMAtic/Mod7/CoolingRod"}, {"Kingpin_HMG_SelectFire", "PawnOMAtic/Mod7/SelectFire"}, {"Kingpin_HMG_AntiMaterial", "PawnOMAtic/Mod7/AntiMaterial"} },
};

// To fill...
str pawnOMaticUpgradeDialogue[7][4][2] =
{
	{
		{ "Ah, pistol reload mod, very good choice... None of that fumblin' around with a clip.", "Ah, the reload mod... That'll decrease your reloading time."},
		{ "Ah, the ROF, very nice mod... Increase your rate of fire.", "Take that ROF, you can spit bullets out."},
		{ "Magnum mod, one of my favorites. A real punch, ya know?", "Magnum mod, very good choice... Great stoppin' power."},
		{ "Ahh, silencer... Very good when you're sneaking up on somebody.", "That'll quiet your pistol down a little bit."},
	},
	{
		{ "Double the barrels, double the fun. Pretty simple stuff.", "Yea, the double barrel. A lotta power, but it uses more ammo."},
		{ "Bleed-shots, these'll make your pellets hurt a lot worse over time.", "Bleed-shots. Very nice choice, makes your enemies leak blood like a stuck pig."},
		{ "Magazine mod, y'can reload that thing way faster, eh? No more droppin' shells.", "Ah, magazine mod... You can get those shells in all at once with this."},
		{ "Ah yeah, select fire. No more fiddlin' around with that handle.", "Select fire, real sweet choice, makes ya gun semi-auto."},
	},
	{
		{ "Ah, frag mod, real nice choice, give your bombs a sharp punch.", "You're gonna turn people into pincushions with this one."},
		{ "Nice choice there, the cluster mod, you can cover a whole area with that.", "Ah, cluster mod, ideal for clearing crowds."},
		{ "Concussion mod. Just makes 'em bombs hurt a lot more.", "Oh yeah, the concussion mod really brings the pain."},
		{ "Bigger drum, classic choice. Now you ain't gotta worry about runnin' out of bombs.", "Good, bigger drum will let you shoot twice as many bombs before havin' to pop it out."},
	},
	{
		{ "Ah, larger drum mod, no more runnin' out of bullets.", "Larger drum means you ain't gotta reload so much."},
		{ "Bigger bore means a bigger bullet.", "This'll let you punch a real hole in the competition."},
		{ "Let's go ahead and get that spread tightened up for ya.", "With this, you'll be able to hit the broad side of a barn for once."},
		{ "Ah, buzzsaw mod. Tears through guys like paper.", "This'll make the Tommy spit hot lead like a fire hose."},
	},
	{
		{ "Faster rockets, makes it easier to hit stuff from afar.", "Yeah, now you'll be able to hit your targets before they can hit you."},
		{ "Standard laser system, lets you track moving targets.", "Ah, laser mod. Now ya don't gotta worry about aiming the thing right away."},
		{ "High explosives for a bigger boom. Just don't stand too close, alright?", "Ey, high explosives, blasts away pretty much anything with real efficiency."},
		{ "The Big Bubba. Makes those regular rockets look like cheap firecrackers, but needs a lot more ammo.", "It's pretty dangerous, but I'll let you have it. Just don't blow up my shop, eh?"},
	},
	{
		{ "Extra range mod, now you ain't gotta worry about burnin' yourself so much.", "With one of these, you can cook 'em nice and crispy from across the room."},
		{ "Ah, hotter flame mod, your enemies will feel the burn way quicker.", "Get yourself a hotter flame mod and light 'em up in a fraction of the time."},
		{ "Adding a fuel pump means you'll get the same burn for less gas.", "Fuel pump, real good investment, saves you a lot of gas."},
		{ "Switch from regular gas to napalm, and you can keep a whole area lit up.", "Ah, napalm mod, that stuff will stick fire to pretty much anything."},
	},
	{
		{ "Stick a scope on there, and you can line up your shots way easier.", "Tactical scope mod, you'll be carryin' a real sniper rifle with that."},
		{ "Oh, the HMG cooling mod, very nice option. Boom boom b-boom boom boom boom! Heheheheh!", "Oh, the HMG cooling mod, that's a nice little number. Turn that baby nearly automatic for ya! Heh." },
		{ "Ah, select fire mod, makes that thing hammer off rounds instead of a burst.", "Select fire, sweet choice. Make that thing into a real automatic, eh?"},
		{ "Anti-material rounds give a nice boom on impact. Ya know they use these to punch through tanks?", "Folks will learn not to mess with you when you show up with these explosive rounds."}
	},
};

int pawnOMaticUpgradePrices [7][4] =
{
	{ 25, 50, 100, 50 },
	{ 200, 100, 150, 250 },
	{ 50, 200, 100, 50 },
	{ 100, 200, 100, 300 },
	{ 50, 150, 250, 500 },
	{ 100, 200, 100, 250 },
	{ 100, 150, 350, 500 },
};

str KingpinWeapons[8][2] =
{
    { "Kingpin_Crowbar", "GotWeapon0" },
    { "Kingpin_Pistol", "" },
    { "Kingpin_Shotgun", "GotWeapon2" },
    { "Kingpin_GrenadeLauncher", "GotWeapon3" },
    { "Kingpin_TommyGun", "GotWeapon4" },
    { "Kingpin_Bazooka", "GotWeapon5" },
    { "Kingpin_Flamethrower", "GotWeapon6" },
    { "Kingpin_HMG", "GotWeapon7" },
};

str SharkySoldNoBuy[2][3] =
{
	{ "It's all yours.", "Here ya go.", "Sold." },
	{ "Nah? How 'bout somethin' else?", "Okay, find somethin' else you like.", "Nah?" }
};

str SharkyDenied[5][4] =
{
	{ "Hey, you don't have enough cash...", "You ain't got enough money." },
	{ "Hey, that mod ain't gonna do you any good unless you've got the gun to go with it.", "Hey, you gotta have the right piece for that thing... Otherwise, it's worthless." },
	{ "Hey, you already got that.", "Hey, you don't need two... You already got one." },
	{ "Hey, you're all full up... You can't hold any more.", "You don't need any more health... You're full up.", "Hey, you don't need any more... You're all patched up now.", "Hey, you're fine... You don't need any more health." },
	{ "Hey, you can't carry any more.", "You're maxed out." }
};

str SharkyRandomWeapons[9] =
{
	"Hey, very good choice.",
	"Haha, my personal favorite.",
	"Oh, I like that one a lot.",
	"Very good choice.",
	"Yeah, nice selection.",
	"That'll work.",
	"Boom! Heheheh.",
	"So you're gonna take this one...",
	"Awright."
};

str SharkyHealthArmorStrings[8][2] =
{
	{ "What, got yourself a papercut? Don't you worry.", "This will heal a cut or bruise, but you may want more." },
	{ "Stimpack, okay.", "Not a bad choice, a stimpack." },
	{ "Ah, those medkits'll get you through some scrapes, huh?", "Hey, if you're really hurtin', that thing'll do you some good, huh?" },
	{ "Soulspheres are the best health item I sell.", "This will do more than I heal ya up." },
	{ "Needing a minor patch up, huh?", "Just a small patch up. Alright?" },
	{ "Ahh, green armor. Not the best, but decent enough.", "Nice, green armor. Can't go wrong with that." },
	{ "Blue armor, huh? Nothing better than that.", "Blue armor isn't cheap." },
	{ "Wow, a megasphere. Not too many people buy these.", "Ah yeah, I happen to have a spare one of these laying around. Very expensive." }
};

str SharkyAmmoStrings[4][2] =
{
	{ "Alright, you wanna buy some bullets?", "So you wanna purchase some bullets... That it?" },
	{ "So you wanna buy some shells, eh?", "Shotgun shells." },
	{ "Heh. Explosives. Very nasty, you wanna buy 'em?", "Explosives... You want 'em?" },
	{ "Yeah, gas canisters and .308 rounds, very deadly.", "Gonna do a little touch up work, eh? Gas canisters and .308 rounds." }
};

function void KingpinDisplayDialogue(int arg1, int arg2, int arg3, int arg4)
{
	str text = "";
	int price = 0;
	switch(arg1)
	{
		default:
			text = "Hey, welcome to Pawn-O-Matic, huh?";
			break;
		case 1:
			text = strparam(s:"\c[KPPawnOMaticWhite]", s:pawnOMaticUpgradeDialogue[arg2][arg3][arg4], s:" That will be \c[KPPawnOMaticRed]",d:pawnOMaticUpgradePrices[arg2][arg3], s:"\c[KPPawnOMaticWhite] dollar", s:pawnOMaticUpgradePrices[arg2][arg3] > 1 ? "s" : "", s:".", s:"\n\n\c[KPPawnOMaticRed](Activate again to purchase)");
			break;
		case 2:
			text = strparam(s:"\c[KPPawnOMaticWhite]", s:SharkyRandomWeapons[arg3], s:" That will be \c[KPPawnOMaticRed]",d:pawnOMaticItemPrices[0][arg2], s:"\c[KPPawnOMaticWhite] dollar", s:pawnOMaticItemPrices[0][arg2] > 1 ? "s" : "", s:".", s:"\n\n\c[KPPawnOMaticRed](Activate again to purchase)");
			break;
		case 3: 
			if(pawnOMaticItemBulkBuy[arg1-3][arg2-1] == 0)
				text = strparam(s:"\c[KPPawnOMaticWhite]", s:SharkyAmmoStrings[arg2-1][arg3], s:" That will be \c[KPPawnOMaticRed]",d:pawnOMaticItemPrices[1][arg2], s:"\c[KPPawnOMaticWhite] dollar", s:pawnOMaticItemPrices[1][arg2] > 1 ? "s" : "", s:".", s:"\n\n\c[KPPawnOMaticRed](Activate again to purchase)");
			else
			{
				if(arg4 > 0)
					text = strparam(s:"\c[KPPawnOMaticWhite]", s:SharkyAmmoStrings[arg2-1][arg3], s:" You want \c[KPPawnOMaticRed]",d:arg4, s:"\c[KPPawnOMaticWhite]? That will be \c[KPPawnOMaticRed]", d:pawnOMaticItemPrices[1][arg2]*arg4, s:"\c[KPPawnOMaticWhite] dollar", s:pawnOMaticItemPrices[1][arg2]*arg4 > 1 ? "s" : "", s:".", s:"\n\n\c[KPPawnOMaticRed](Activate again to purchase - Use movement keys to adjust amount)");
				else
					text = strparam(s:"\c[KPPawnOMaticRed](Activate again to cancel)");
			}
			break;
		case 4:
			if(pawnOMaticItemBulkBuy[arg1-3][arg2-1] == 0)
				text = strparam(s:"\c[KPPawnOMaticWhite]", s:SharkyHealthArmorStrings[arg2-1][arg3], s:" That will be \c[KPPawnOMaticRed]",d:pawnOMaticItemPrices[2][arg2], s:"\c[KPPawnOMaticWhite] dollar", s:pawnOMaticItemPrices[2][arg2] > 1 ? "s" : "", s:".", s:"\n\n\c[KPPawnOMaticRed](Activate again to purchase)");
			else
			{
				if(arg4 > 0)
					text = strparam(s:"\c[KPPawnOMaticWhite]", s:SharkyHealthArmorStrings[arg2-1][arg3], s:" You want \c[KPPawnOMaticRed]",d:arg4, s:"\c[KPPawnOMaticWhite]? That will be \c[KPPawnOMaticRed]", d:pawnOMaticItemPrices[2][arg2]*arg4, s:"\c[KPPawnOMaticWhite] dollar", s:pawnOMaticItemPrices[2][arg2]*arg4 > 1 ? "s" : "", s:".", s:"\n\n\c[KPPawnOMaticRed](Activate again to purchase - Use movement keys to adjust amount)");
				else
					text = strparam(s:"\c[KPPawnOMaticRed](Activate again to cancel)");
			}
			break;
		case 9:
			text = strparam(s:"\c[KPPawnOMaticWhite]", s:SharkySoldNoBuy[arg2][arg3]);
			break;
		case 10:
			text = strparam(s:"\c[KPPawnOMaticWhite]", s:SharkyDenied[arg2][arg3]);
			break;
	}
	Setfont("KPFONTBG");
	SetHudSize(1800,1200,1);
	SetHudClipRect(200,1012,1400,140,1400);
	HudMessage(s:text;HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP|HUDMSG_COLORSTRING,62,CR_UNTRANSLATED,200.1,1012.1,0.0);
	SetHudClipRect(0,0,0,0,0);
	SetHudSize(1200,800,1);
}

Script "Kingpin_PawnOMatic" (int playerNum, int sTid) Net
{
	int breakloop;
	int pawnOpen;
	int cigarAnimator;
	int lastInputTimer;
	int scrollingItem;
	int intendedItem = 1;
	int maxInputDelay = 4;
	int scrollersCounter = 20;
	//Big menu items, on the left
	int currentMenu = 1;
	int currentMenuItem = 0;
	int lastMenu = 1;
	//Sub menu related variables
	int currentUpgradeMenu = 0;
	int triggerUpgradeMenu;
	//Item related variables
	int currentItem = 0;
	int selectedItemOpen;
	int triggerItems;
	int modSelected;
	int bulkCounter = 1;
	int welcomeMessage = true;
	int messageDialog = 0;
	//Variables related to bulk buying
	int maxBulkBuy, itemLimit;
	while(CheckInventory("Kingpin_PawnOMaticOpen"))
	{
		//Draw the default stuff for pawn-o-matic. Also, get input
		int playerInputX = GetPlayerInput(-1,INPUT_SIDEMOVE);
		int playerInputY = -GetPlayerInput(-1,INPUT_FORWARDMOVE);
		int buttons = GetPlayerInput(-1,INPUT_BUTTONS);
		int oldbuttons = GetPlayerInput(-1,INPUT_OLDBUTTONS);
		int useKey = (buttons & BT_USE) && !(oldbuttons & BT_USE);
		cigarAnimator = ((timer()%116)/2)+1;
		SetFont("KPSTORE");
		SetHudSize(1200,800,1);
		HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,61,CR_UNTRANSLATED,600.0,400.0,0.0);
		SetFont(strparam(s:"KPCIGR",s:cigarAnimator < 10 ? "0" : "",d:cigarAnimator));
		HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,60,CR_UNTRANSLATED,576.0,480.0,0.0);
		SetFont("KPLITOFF");
		HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,59,CR_UNTRANSLATED,600.0,400.0,0.0);
		//Only display the text if it's 0. It will never do this until reopened
		if(welcomeMessage == true) KingpinDisplayDialogue(0,0,0,0);
		SetFont("KPDIALOG");
		HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP|HUDMSG_ALPHA,63,CR_UNTRANSLATED,600.0,420.0,0.0,0.67);
		//Bulk ammo/health buying
		
		//Check for the input delay and if items are currently scrolling
		if(lastInputTimer >= maxInputDelay && !scrollingItem)
		{	
			if(modSelected && currentMenu > 2 && pawnOMaticItemBulkBuy[currentMenu-3][currentMenuItem-1])
			{
				//Update the display
				KingpinDisplayDialogue(currentMenu,currentMenuItem,messageDialog,pawnOMaticItemBulkBuy[currentMenu-3][currentMenuItem-1] > 0 ? bulkCounter : 0);
				//Check ammo
				if(currentMenu == 3)
				{
					itemLimit = GetAmmoCapacity(pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][0]);
					maxBulkBuy = itemLimit - CheckInventory(pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][0]);
				}
				else if(currentMenu == 4)
				{
					//Check health
					if(pawnOMaticItemBulkBuy[currentMenu-3][currentMenuItem-1] == 1)
					{
						itemLimit = ACS_NamedExecuteWithResult("SamsaraPlayerHealer", -1, 200);
						maxBulkBuy = itemLimit - GetActorProperty(0,APROP_Health);
					}
					//Check armor
					else if(pawnOMaticItemBulkBuy[currentMenu-3][currentMenuItem-1] == 2)
					{
						itemLimit = ACS_NamedExecuteWithResult("SamsaraArmorCapResultChecker", 0, 0);
						maxBulkBuy = itemLimit - CheckInventory("BasicArmor");
					}
				}
				//Constrain financially
				maxBulkBuy = min(maxBulkBuy,CheckInventory("Kingpin_Cash")/pawnOMaticItemPrices[currentMenu-2][currentMenuItem]);
				
				//Clamp the value here
				if(bulkCounter > maxBulkBuy)
				{
					bulkCounter = maxBulkBuy;
					//Cancel transaction if out of money
					if(maxBulkBuy == 0)
					{
						modSelected = 0;
						messageDialog = random(0,1);
						KingpinDisplayDialogue(10,0,messageDialog,0);
						welcomeMessage = false;
						PlaySound(sTid,StrParam(s:"PawnOMatic/LowCash",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE);
						bulkCounter = -1;
					}
				}
	
				//Alter bulk counter depending on input
				if(playerInputX != 0 || playerInputY != 0)
				{
					if(playerInputX > 0)
					{
						bulkCounter++;
						if(bulkCounter > maxBulkBuy)
							bulkCounter = 0;
					}
					else if(playerInputX < 0)
					{
						bulkCounter--;
						if(bulkCounter < 0)
							bulkCounter = maxBulkBuy;
					}
					else if(playerInputY < 0)
					{
						bulkCounter+=10;
						if(bulkCounter > maxBulkBuy)
							bulkCounter = 0;
					}
					else if(playerInputY > 0)
					{
						bulkCounter-=10;
						if(bulkCounter < 0)
							bulkCounter = maxBulkBuy;
					}
					
					//Reset the input timer
					lastInputTimer = 0;
				}
			}
			//If Up-Down input...
			else if(playerInputY != 0)
			{
				//This will scroll up and down on the main list
				if(!triggerItems && !triggerUpgradeMenu)
				{
					PlaySound(sTid,"PawnOMatic/Selection",CHAN_5,1.0,0,ATTN_NONE);
					if(playerInputY > 0) currentMenu++;
					else if(playerInputY < 0) currentMenu--;		
					
					//Clamp main menu values
					if(currentMenu < 1) currentMenu = 8;
					else if(currentMenu > 8) currentMenu = 1;
					else if(currentMenu == 5) currentMenu = 8;
					else if(currentMenu == 7) currentMenu = 4;
				}
				//That assumes the upgrade menu is open. If so, do this
				else if(!triggerItems)
				{
					PlaySound(sTid,"PawnOMatic/Selection",CHAN_5,1.0,0,ATTN_NONE);
					if(playerInputY > 0) currentUpgradeMenu++;
					else if(playerInputY < 0) currentUpgradeMenu--;	
					
					if(currentUpgradeMenu < 1) currentUpgradeMenu = 7;
					else if(currentUpgradeMenu > 7) currentUpgradeMenu = 1;
				}
				//You must be in the items menu, then
				else
				{
					PlaySound(sTid,"PawnOMatic/Selection",CHAN_5,1.0,0,ATTN_NONE);
					if(playerInputY > 0) currentMenuItem++;
					else if(playerInputY < 0) currentMenuItem--;
					
					//We use the fixed 4 if this is the upgrades menu
					if(currentMenu == 1)
					{
						if(currentMenuItem < 1) currentMenuItem = 4;
						if(currentMenuItem > 4) currentMenuItem = 1;
					}
					//Otherwise, we get dynamic values
					else
					{
						//WTF? Why -2?
						if(currentMenuItem < 1) currentMenuItem = pawnOMaticItemPrices[currentMenu-2][0];
						if(currentMenuItem > pawnOMaticItemPrices[currentMenu-2][0]) currentMenuItem = 1;
					}
				}	
				//Reset input timer
				lastInputTimer = 0;
				
				//Queue "no thanks" if an item was selected
				if(modSelected > 0)
				{
					modSelected = 0;
					messageDialog = random(0,2);
					KingpinDisplayDialogue(9,1,messageDialog,0);
					welcomeMessage = false;
					PlaySound(sTid,StrParam(s:"PawnOMatic/NoThanks",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE);
				}
			}	
			//If the upgrade menu isn't open, then we must handle the menu items
			else if(!triggerUpgradeMenu && (playerInputX != 0 || useKey && currentMenuItem == 0))
			{
				PlaySound(sTid,"PawnOMatic/Selection",CHAN_5,1.0,0,ATTN_NONE);
					
				//Behavior is different, depending on what menu to pick
				if(currentMenu > 1)
				{
					//Moving to the right or use key activates this
					if((playerInputX > 0 || useKey) && !triggerItems)
					{
						//Exit here
						if(currentMenu == 8) 
						{
							TakeInventory("Kingpin_PawnOMaticOpen",1);
							SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);
							break;
						}		
						
						//Switch to items menu
						triggerItems = true;	
						
						//Set the selected menu to the current menu index
						selectedItemOpen = currentMenu;	
						
						//Flip the intended item index to the one needed, so it will scroll
						intendedItem = 1+(4*currentMenu);
							if(intendedItem >= 20)
								intendedItem = 1;
								
						//Tell it to scroll the items menu
						scrollingItem = true;
						
						//Set the default menu item index
						currentMenuItem = 1;
						
						//Force the panels to go to their starting point
						currentItem = 1;
					}	
					//Moving to the left will go back to input of the main menu to the left
					else if(playerInputX < 0)
					{
						triggerItems = false;
						selectedItemOpen = 0;	
						intendedItem = 1;	
						scrollingItem = true;			
						currentMenuItem = 0;
					}
				}
				//This is the upgrade menu
				else if(currentMenu == 1)
				{
					if((playerInputX > 0 || useKey) && !triggerItems)
					{
						triggerItems = false;		
						triggerUpgradeMenu = true;
						currentItem = 1;
						
						//Flip the intended item index to the one needed, so it will scroll
						intendedItem = 1+(4*currentMenu);
							if(intendedItem >= 32)
								intendedItem = 1;
								
						//Tell it to scroll the items menu
						scrollingItem = true;
						
						//Set the default upgrade item index
						currentUpgradeMenu = 1;
						currentMenuItem = 0;
					}
					else if(playerInputX < 0 && triggerItems)
					{
						triggerUpgradeMenu = true;
						triggerItems = false;
						selectedItemOpen = 0;	
						
						//Set the item to scroll back to
						intendedItem = 1+(4*currentMenu);
						
						//Force the item to scroll
						currentItem = 1;
						scrollingItem = true;			
						currentMenuItem = 0;
					}				
				}
				
				//Reset input timer
				lastInputTimer = 0;
				PlaySound(sTid,"PawnOMatic/Scrollers",CHAN_6,1.0,1,ATTN_NONE);
				
				//Queue "no thanks" if an item was selected
				if(modSelected > 0)
				{
					modSelected = 0;
					messageDialog = random(0,2);
					KingpinDisplayDialogue(9,1,messageDialog,0);
					welcomeMessage = false;
					PlaySound(sTid,StrParam(s:"PawnOMatic/NoThanks",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE);
				}
			}
			//Otherwise, do this stuff if the upgrade menu is open
			else if(triggerUpgradeMenu && (playerInputX != 0 || useKey))
			{
				PlaySound(sTid,"PawnOMatic/Selection",CHAN_5,1.0,0,ATTN_NONE);
				if((playerInputX > 0 || useKey) && !triggerItems)
				{
					//Switch to modifications menu
					triggerItems = true;	
					triggerUpgradeMenu = false;
					
					//Set the selected menu to the current menu index
					selectedItemOpen = currentUpgradeMenu;	
					
					//Flip the intended item index to the one needed, so it will scroll
					intendedItem = 1+(4*currentUpgradeMenu);
						if(intendedItem >= 32)
							intendedItem = 1;
												
					//Force the panels to go to their starting point
					currentItem = 1;
					
					//Tell it to scroll the items menu
					scrollingItem = true;
					
					//Set the default menu item index
					currentMenuItem = 1;
				}
				//Moving to the left will go back to input of the main menu to the left
				else if(playerInputX < 0)
				{
					triggerItems = false;
					triggerUpgradeMenu = false;
					selectedItemOpen = 0;	
					intendedItem = 1;	
					scrollingItem = true;			
					currentMenuItem = 0;
					currentUpgradeMenu = 0;
				}
				
				//Reset input timer
				lastInputTimer = 0;
				PlaySound(sTid,"PawnOMatic/Scrollers",CHAN_6,1.0,1,ATTN_NONE);
			}
		}
		
		//Update the scrollers counter value
		scrollersCounter = (triggerItems && currentMenu == 1) ? 32 : 20;
		//Flip scroller things
		if(currentItem != intendedItem)
		{
			if(timer()%2 == 0)
			{
				currentItem++;
				if(currentItem >= scrollersCounter)
					currentItem = 1;
			}
		}
		else
		{
			scrollingItem = 0;
			StopSound(sTid,CHAN_6);
		}
		
		if(triggerItems && currentMenu == 1)
		{
			SetFont(strparam(s:"KPITEM",s:currentItem < 10 ? "0" : "",d:currentItem));
			HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,56,CR_UNTRANSLATED,600.0,400.0,0.0);
		}
		else
		{
			SetFont(strparam(s:"KPITM2",s:currentItem < 10 ? "0" : "",d:currentItem));
			HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,56,CR_UNTRANSLATED,600.0,400.0,0.0);	
		}
		
		//Draw the selected item next to price
		if(triggerItems && currentMenu == 1)
			SetFont(strparam(s:"KPSELE",d:currentItem));
		else
			SetFont(strparam(s:"KPSEL2",d:currentItem));
		HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,55,CR_UNTRANSLATED,600.0,400.0,0.0);
		
		SetFont(strparam(s:"KPSTLT1",d:currentMenu));
		HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,58,CR_UNTRANSLATED,600.0,400.0,0.0);
		
		if(currentMenuItem > 0 || currentUpgradeMenu > 0)
		{
			if(currentUpgradeMenu > 0 && currentMenuItem == 0)
			{
				SetFont(strparam(s:"KPSTLT2",d:currentUpgradeMenu));
				HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,57,CR_UNTRANSLATED,600.0,400.0,0.0);
			}
			else
			{
				SetFont(strparam(s:"KPSTLT2",d:currentMenuItem));
				HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,57,CR_UNTRANSLATED,600.0,400.0,0.0);
			}
			
			if(triggerItems)
			{
				if(currentMenu == 1)
				{
					SetFont(strparam(s:"KPDIGT",d:(pawnOMaticUpgradePrices[currentUpgradeMenu-1][currentMenuItem-1]/100)%10));
					HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,54,CR_UNTRANSLATED,574.0,400.0,0.0);
				
					SetFont(strparam(s:"KPDIGT",d:(pawnOMaticUpgradePrices[currentUpgradeMenu-1][currentMenuItem-1]/10)%10));
					HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,53,CR_UNTRANSLATED,600.0,400.0,0.0);
					
					SetFont(strparam(s:"KPDIGT",d:pawnOMaticUpgradePrices[currentUpgradeMenu-1][currentMenuItem-1]%10));
					HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,52,CR_UNTRANSLATED,626.0,400.0,0.0);
				}
				else
				{
					SetFont(strparam(s:"KPDIGT",d:(pawnOMaticItemPrices[currentMenu-2][currentMenuItem]/100)%10));
					HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,54,CR_UNTRANSLATED,574.0,400.0,0.0);
				
					SetFont(strparam(s:"KPDIGT",d:(pawnOMaticItemPrices[currentMenu-2][currentMenuItem]/10)%10));
					HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,53,CR_UNTRANSLATED,600.0,400.0,0.0);
					
					SetFont(strparam(s:"KPDIGT",d:pawnOMaticItemPrices[currentMenu-2][currentMenuItem]%10));
					HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,52,CR_UNTRANSLATED,626.0,400.0,0.0);
				}
			}
			//Remove digits
			else RemoveMessages(52,54);
						
			//Buying weapon upgrades
			if(lastInputTimer >= maxInputDelay && !scrollingItem && useKey)
			{
				//Purchase weapon upgrades
				if(currentMenu == 1 && currentMenuItem < 5)
				{
					lastInputTimer = 0;
					if(!CheckInventory(KingpinWeapons[currentUpgradeMenu][0]))
					{
						messageDialog = random(0,1);
						KingpinDisplayDialogue(10,1,messageDialog,0);
						welcomeMessage = false;
						PlaySound(sTid,StrParam(s:"PawnOMatic/NoWeapon",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE);
					}
					else if(CheckInventory(pawnOMaticUpgradeOptions[currentUpgradeMenu-1][currentMenuItem-1][0]))
					{
						messageDialog = random(0,1);
						KingpinDisplayDialogue(10,2,messageDialog,0);
						welcomeMessage = false;
						PlaySound(sTid,StrParam(s:"PawnOMatic/AlreadyHave",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE);
					}
					else if(CheckInventory("Kingpin_Cash") < pawnOMaticUpgradePrices[currentUpgradeMenu-1][currentMenuItem-1])
					{
						messageDialog = random(0,1);
						KingpinDisplayDialogue(10,0,messageDialog,0);
						welcomeMessage = false;
						PlaySound(sTid,StrParam(s:"PawnOMatic/LowCash",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE);
					}
					else
					{
						lastInputTimer = -4;
						if(modSelected == 0)
						{
							//Play sound for confirmation
							messageDialog = random(0,1);
							KingpinDisplayDialogue(1,currentUpgradeMenu-1,currentMenuItem-1,messageDialog);
							welcomeMessage = false;
							if (StrCmp(pawnOMaticUpgradeOptions[currentUpgradeMenu-1][currentMenuItem-1][1], "")) { PlaySound(sTid,StrParam(s:pawnOMaticUpgradeOptions[currentUpgradeMenu-1][currentMenuItem-1][1],d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE); }
							modSelected = currentUpgradeMenu;
						}
						else
						{
							TakeInventory("Kingpin_Cash",pawnOMaticUpgradePrices[currentUpgradeMenu-1][currentMenuItem-1]);
							GiveInventory(pawnOMaticUpgradeOptions[currentUpgradeMenu-1][currentMenuItem-1][0],1);
							messageDialog = random(0,2);
							KingpinDisplayDialogue(9,0,messageDialog,0);
							welcomeMessage = false;
							PlaySound(sTid,"PawnOMatic/Register",CHAN_5,1.0,0,ATTN_NONE);
							PlaySound(sTid,StrParam(s:"PawnOMatic/Sold",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE);
							modSelected = 0;
						}
					}
				}
				//Other items
				else
				{
					if(currentMenuItem < pawnOMaticItemPrices[currentMenu-2][0]+1)
					{
						bool hitlimit = false;
						int itemtype = 0;

						if (currentMenu == 2) { hitlimit = CheckInventory(KingpinWeapons[currentMenuItem-1][0]); }
						else if (currentMenu == 3)
						{
							hitlimit = CheckInventory(pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][0]) >= GetAmmoCapacity(pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][0]);
							itemtype = 2;
						} else if (currentMenu == 4) {
							if (!StrCmp(pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][0], "HealPack0") || !StrCmp(pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][0], "SuperHealth"))
							{
								hitlimit = GetActorProperty(0, APROP_Health) >= ACS_NamedExecuteWithResult("SamsaraPlayerHealer", -1, 200);
								itemtype = 1;
							} else if (!StrCmp(pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][0], "HealPack1") || !StrCmp(pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][0], "HealPack2")) {
								hitlimit = GetActorProperty(0, APROP_Health) >= ACS_NamedExecuteWithResult("SamsaraPlayerHealer", -1);
								itemtype = 1;
							} else if (!StrCmp(pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][0], "ArmorScrap")) {
								hitlimit = ACS_NamedExecuteWithResult("SamsaraArmorCapCheck", 0, 0, 0, 2);
								itemtype = 2;
							} else if (!StrCmp(pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][0], "ArmorPack1")) {
								hitlimit = ACS_NamedExecuteWithResult("SamsaraArmorCapCheck", 5);
								itemtype = 2;
							} else if (!StrCmp(pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][0], "ArmorPack3")) {
								hitlimit = ACS_NamedExecuteWithResult("SamsaraArmorCapCheck", 7);
								itemtype = 2;
							} else if (!StrCmp(pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][0], "MegaPack")) {
								hitlimit = GetActorProperty(0, APROP_Health) >= ACS_NamedExecuteWithResult("SamsaraPlayerHealer", -1, 200) && ACS_NamedExecuteWithResult("SamsaraArmorCapCheck", 11);
								itemtype = 2;
							}
						}

						if(hitlimit)
						{
							switch (itemtype)
							{
								default:
									messageDialog = random(0,1);
									KingpinDisplayDialogue(10,2,messageDialog,0);
									break;

								case 1:
									messageDialog = random(0,3);
									KingpinDisplayDialogue(10,3,messageDialog,0);
									break;

								case 2:
									messageDialog = random(0,1);
									KingpinDisplayDialogue(10,4,messageDialog,0);
									break;
							}
							welcomeMessage = false;
							switch (itemtype)
							{
								default: PlaySound(sTid,StrParam(s:"PawnOMatic/AlreadyHave",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE); break;
								case 1: PlaySound(sTid,StrParam(s:"PawnOMatic/AlreadyHaveHealth",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE); break;
								case 2: PlaySound(sTid,StrParam(s:"PawnOMatic/AlreadyHaveItem",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE); break;
							}
						}
						else if(CheckInventory("Kingpin_Cash") < pawnOMaticItemPrices[currentMenu-2][currentMenuItem])
						{
							messageDialog = random(0,1);
							KingpinDisplayDialogue(10,0,messageDialog,0);
							welcomeMessage = false;
							PlaySound(sTid,StrParam(s:"PawnOMatic/LowCash",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE);
						}
						else
						{
							lastInputTimer = -4;
							if(modSelected == 0)
							{
								modSelected = currentMenuItem;
								//Purchase weapons
								if(currentMenu == 2)
								{
									messageDialog = random(0,8);
									KingpinDisplayDialogue(2,currentMenuItem,messageDialog,0);
									PlaySound(sTid,StrParam(s:"PawnOMatic/Weapon",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE);
								}

								//Purchase Ammo, Health and Armor
								else if(currentMenu > 2)
								{
									messageDialog = random(0,1);
									KingpinDisplayDialogue(currentMenu,currentMenuItem,messageDialog,pawnOMaticItemBulkBuy[currentMenu-3][currentMenuItem-1] > 0 ? bulkCounter : 0);
									if (StrCmp(pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][1], "")) { PlaySound(sTid,StrParam(s:pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][1],d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE); }
								}
								welcomeMessage = false;
								
								//Set the default bulk counter
								bulkCounter = 1;	
							}
							else
							{
								if(currentMenu > 2)
								{
									//If the bulk counter is greater than 0, make the purchase
									if(bulkCounter > 0)
									{
										TakeInventory("Kingpin_Cash",pawnOMaticItemPrices[currentMenu-2][currentMenuItem] * bulkCounter);
									
										GiveInventory("SamsaraPickupAndShutUp",1);
										//Looks like I will need a for loop for things like health
										for(int give = 0; give < bulkCounter; give++) 
											GiveInventory(pawnOMaticItemOptions[currentMenu-3][currentMenuItem-1][0],1);
										TakeInventory("SamsaraPickupAndShutUp",INTMAX);
										
										messageDialog = random(0,2);
										KingpinDisplayDialogue(9,0,messageDialog,0);
										welcomeMessage = false;
										PlaySound(sTid,"PawnOMatic/Register",CHAN_5,1.0,0,ATTN_NONE);
										PlaySound(sTid,StrParam(s:"PawnOMatic/Sold",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE);
									}
									//Otherwise, cancel the purchase.
									else
									{
										modSelected = 0;
										messageDialog = random(0,2);
										KingpinDisplayDialogue(9,1,messageDialog,0);
										welcomeMessage = false;
										PlaySound(sTid,StrParam(s:"PawnOMatic/NoThanks",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE);
									}
								}
								else if(currentMenu == 2)
								{
									TakeInventory("Kingpin_Cash",pawnOMaticItemPrices[currentMenu-2][currentMenuItem] * bulkCounter);
								
									GiveInventory(KingpinWeapons[currentMenuItem-1][0],1);
									if (StrCmp(KingpinWeapons[currentMenuItem-1][1], "")) { GiveInventory(KingpinWeapons[currentMenuItem-1][1],1); }
									
									messageDialog = random(0,2);
									KingpinDisplayDialogue(9,0,messageDialog,0);
									welcomeMessage = false;
									PlaySound(sTid,"PawnOMatic/Register",CHAN_5,1.0,0,ATTN_NONE);
									PlaySound(sTid,StrParam(s:"PawnOMatic/Sold",d:messageDialog+1),CHAN_VOICE,1.0,0,ATTN_NONE);
								}
								modSelected = 0;
							}
						}
					}
				}
			}
		}
		else
		{
			RemoveMessages(57,57);
			SetFont("KPDIGT0");
			HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,54,CR_UNTRANSLATED,574.0,400.0,0.0);	
			HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,53,CR_UNTRANSLATED,600.0,400.0,0.0);	
			HudMessage(s:"A";HUDMSG_PLAIN|HUDMSG_NOTWITHFULLMAP,52,CR_UNTRANSLATED,626.0,400.0,0.0);
		}
		
		lastInputTimer++;
		
		Delay(1);
	}
	
	// Play the exit sound and stop other noises
	PlaySound(sTid,"PawnOMAtic/Exit",CHAN_VOICE,1.0,0,ATTN_NONE);
	StopSound(sTid,CHAN_5);
	StopSound(sTid,CHAN_6);
	Thing_Remove(sTid);
	SetInventory("Kingpin_PawnOMaticSoundTid",0);
	RemoveMessages(50,63);
}