//======================================================================================================================
//									Any changes to a file prefixed "Class", compile this
//======================================================================================================================

#library "Class"
#include "zcommon.acs"
#include "commonFuncs.acs"

//======================================================================================================================
//											Class Definition Values are here
//======================================================================================================================

#DEFINE CLASS_DOOM 0
#DEFINE CLASS_CHEX 1
#DEFINE CLASS_HERETIC 2
#DEFINE CLASS_WOLF3D 3
#DEFINE CLASS_HEXEN1 4
#DEFINE CLASS_DUKE3D 5
#DEFINE CLASS_MARATHON 6
#DEFINE CLASS_QUAKE1 7
#DEFINE CLASS_ROTT 8
#DEFINE CLASS_BSTONE 9
#DEFINE CLASS_BLOOD 10
#DEFINE CLASS_STRIFE 11
#DEFINE CLASS_ERAD 12
#DEFINE CLASS_C7 13
#DEFINE CLASS_RMR 14
#DEFINE CLASS_DARKF 15
#DEFINE CLASS_IPOG 16
#DEFINE CLASS_DISRUP 17
#DEFINE CLASS_WITCH 18
#DEFINE CLASS_HALFLIFE 19
#DEFINE CLASS_SW 20
#DEFINE CLASS_CM 21
#DEFINE CLASS_PS 22
#DEFINE CLASS_RR 23
#DEFINE CLASS_QUAKE2 24
#DEFINE CLASS_HEXEN2 25
#DEFINE CLASS_GOLDENEYE 26
#DEFINE CLASS_CATACOMB 27
#DEFINE CLASS_PAINKILLER 28
#DEFINE CLASS_UNREAL 29
#DEFINE CLASS_RTCW 30
#DEFINE CLASS_QUAKE3 31
#DEFINE CLASS_DESCENT 32
#DEFINE CLASS_DEUSEX 33
#DEFINE CLASS_KINGPIN 34
#DEFINE CLASS_SOF 35
#DEFINE CLASS_OUTLAWS 36

//======================================================================================================================
//													Class Includes
//======================================================================================================================
#include "ClassFuncs.acs" // for functions that are shared with more than one class
#include "ClassScripts.acs" // for scripts that are shared with more than one class
#include "ClassHeretic.acs"
#include "ClassWolf3D.acs"
#include "ClassTotenkopf.acs"
#include "ClassHexen1.acs"
#include "ClassDuke3D.acs"
#include "ClassDuke64.acs"
#include "ClassMarathon.acs"
#include "ClassQuake1.acs"
#include "ClassROTT.acs"
#include "ClassBlake.acs"
#include "ClassBlood.acs"
#include "ClassStrifeguy.acs"
#include "ClassEradicator.acs"
#include "ClassCorridor7.acs"
#include "ClassDarkForces.acs"
#include "ClassIPOG.acs"
#include "ClassDisruptor.acs"
#include "ClassWitchaven.acs"
#include "ClassHalfLife.acs"
#include "ClassSW.acs"
#include "ClassExhumed.acs"
#include "ClassRR.acs"
#include "ClassQuake2.acs"
#include "ClassHexen2.acs"
#include "ClassGoldeneye.acs"
#include "ClassGoldfinger.acs"
#include "ClassCatacomb.acs"
#include "ClassPainkiller.acs"
#include "ClassUnreal.acs"
#include "ClassRTCW.acs"
#include "ClassQuake3.acs"
#include "ClassDescent.acs"
#include "ClassDeusEx.acs"
#include "ClassKingpin.acs"
#include "ClassSOF.acs"
#include "ClassOutlaws.acs"
