#define CLASSCOUNT 37

function void AdjustHealthOverMaxDisplay (void)
{
    SetInventory("SamsaraHealthOverMax", getMaxHealth(0) * 2);
    SetInventory("SamsaraHealthOverOverMax", getMaxHealth(0) * 3);
}

function void AdjustArmorDisplays (void)
{
    int pln = PlayerNumber();

    if (GetArmorType("ArmorPack5ArmorMarathon", pln)) { SetInventory("SamsaraArmorCategory", 10); }
    else if (GetArmorType("ArmorPack2ArmorMarathon", pln) ||
             GetArmorType("EnchantedShield", pln) ||
             GetArmorType("ArmorPack3ArmorHeretic", pln) || GetArmorType("StrifeArmorPack3ArmorHeretic", pln))
    { SetInventory("SamsaraArmorCategory", 9); }
    else if (GetArmorType("ArmorScrapArmorQuake", pln) || GetArmorType("MaxArmorScrapArmorQuake", pln) ||
             GetArmorType("ArmorScrapDumpArmorQuake", pln) ||
             GetArmorType("ArmorPackBonusLightArmorQuake", pln) ||
             GetArmorType("ArmorPackBonusHeavyArmorQuake", pln) ||
             GetArmorType("ArmorPack1ArmorQuake", pln) || GetArmorType("StrifeArmorPack1ArmorQuake", pln))
    { SetInventory("SamsaraArmorCategory", 8); }
    else if (GetArmorType("ArmorScrapArmorHeretic", pln) || GetArmorType("MaxArmorScrapArmorHeretic", pln) ||
             GetArmorType("ArmorScrapDumpArmorHeretic", pln) ||
             GetArmorType("ArmorPackBonusLightArmorHeretic", pln) ||
             GetArmorType("ArmorPackBonusHeavyArmorHeretic", pln) ||
             GetArmorType("SilverShield", pln) ||
             GetArmorType("ArmorPack1ArmorHeretic", pln) || GetArmorType("StrifeArmorPack1ArmorHeretic", pln) ||
             GetArmorType("ArmorPack4ArmorQuake", pln) ||
             GetArmorType("StrifeArmorPack3ArmorQuakePlusTier2Active", pln) ||
             GetArmorType("SilverArmor", pln) || // just in case
             GetArmorType("ArmorPack5ArmorNormal", pln))
    { SetInventory("SamsaraArmorCategory", 7); }
    else if (GetArmorType("ArmorScrapArmorQuakePlus", pln) || GetArmorType("MaxArmorScrapArmorQuakePlus", pln) ||
             GetArmorType("ArmorScrapDumpArmorQuakePlus", pln) ||
             GetArmorType("ArmorPackBonusLightArmorQuakePlus", pln) ||
             GetArmorType("ArmorPackBonusHeavyArmorQuakePlus", pln) ||
             GetArmorType("YellowArmor", pln) || // just in case
             GetArmorType("ArmorPack2ArmorNormal", pln) ||
             GetArmorType("ArmorPack2ArmorQuake", pln) || GetArmorType("StrifeArmorPack3ArmorQuakeTier2Inactive", pln) ||
             GetArmorType("StrifeArmorPack1ArmorQuakePlus", pln) ||
             GetArmorType("ArmorPack2ArmorHeretic", pln) ||
             GetArmorType("ArmorPack3ArmorMarathon", pln) || GetArmorType("StrifeArmorPack3ArmorMarathon", pln))
    { SetInventory("SamsaraArmorCategory", 6); }
    else if (GetArmorType("ArmorPack5ArmorQuake", pln)) { SetInventory("SamsaraArmorCategory", 5); } // not used for armormode 0 since hexen 25 armor pickups give 25 points of tier 1 armor
    else if (GetArmorType("ArmorScrapArmorMarathon", pln) || GetArmorType("MaxArmorScrapArmorMarathon", pln) ||
             GetArmorType("ArmorScrapDumpArmorMarathon", pln) ||
             GetArmorType("ArmorPackBonusLightArmorMarathon", pln) ||
             GetArmorType("ArmorPackBonusHeavyArmorMarathon", pln) ||
             GetArmorType("ArmorPack1ArmorMarathon", pln) || GetArmorType("StrifeArmorPack1ArmorMarathon", pln) ||
             GetArmorType("ArmorPack3ArmorQuake", pln) || GetArmorType("StrifeArmorPack3ArmorQuakeTier2Active", pln) ||
             GetArmorType("StrifeArmorPack3ArmorQuakePlusTier2Inactive", pln) ||
             GetArmorType("RedArmor", pln) || // why not?
             GetArmorType("ArmorPack4ArmorNormal", pln) ||
             GetArmorType("ArmorPack4ArmorHeretic", pln))
    { SetInventory("SamsaraArmorCategory", 4); }
    else if (GetArmorType("BasicArmorPickup", pln) || GetArmorType("BlueArmor", pln) || GetArmorType("BlueArmorForMegasphere", pln) || GetArmorType("MetalArmor", pln) || GetArmorType("SuperChexArmor", pln) || // BasicArmorPickup is given by armor cheat
             GetArmorType("ArmorPack3ArmorNormal", pln) || GetArmorType("StrifeArmorPack3ArmorNormal", pln) ||
             GetArmorType("FuckArmor", pln))
    { SetInventory("SamsaraArmorCategory", 3); }
    else if (GetArmorType("BasicArmorBonus", pln) || GetArmorType("ArmorBonus", pln) || GetArmorType("MaxArmorBonus", pln) || GetArmorType("SlimeRepellent", pln) ||
             GetArmorType("ArmorScrapArmorNormal", pln) || GetArmorType("ArmorScrap100", pln) || GetArmorType("ArmorScrap200", pln) || GetArmorType("InfiniteArmorBonus", pln) || GetArmorType("MaxArmorScrapArmorNormal", pln) ||
             GetArmorType("ArmorScrapDumpArmorNormal", pln) ||
             GetArmorType("ArmorPackBonusLightArmorNormal", pln) ||
             GetArmorType("ArmorPackBonusHeavyArmorNormal", pln) ||
             GetArmorType("GreenArmor", pln) || GetArmorType("LeatherArmor", pln) || GetArmorType("ChexArmor", pln) ||
             GetArmorType("ArmorPack1ArmorNormal", pln) || GetArmorType("StrifeArmorPack1ArmorNormal", pln))
    { SetInventory("SamsaraArmorCategory", 2); }
    else if (GetArmorType("ArmorPack4ArmorMarathon", pln) ||
             GetArmorType("ArmorPack5ArmorHeretic", pln))
    { SetInventory("SamsaraArmorCategory", 1); }
    else { SetInventory("SamsaraArmorCategory", 0); } // other armors

    if (CheckInventory("BasicArmor") > 0)
    {
        // some of these armors need special adjustments. there's probably a better way to do this, but I don't know what it could be
        if (GetArmorType("ArmorPack4ArmorHeretic", pln)) { SetInventory("SamsaraArmorSavePercent", 87); }
        else if (GetArmorType("ArmorPack2ArmorHeretic", pln)) { SetInventory("SamsaraArmorSavePercent", 67); }
        else if (GetArmorType("RedArmor", pln) || // why not?
                 GetArmorType("ArmorPack4ArmorNormal", pln))
        { SetInventory("SamsaraArmorSavePercent", 66); }
        else { SetInventory("SamsaraArmorSavePercent", roundZandronum(GetArmorInfo(ARMORINFO_SAVEPERCENT) * 100)); }
    }
    else { SetInventory("SamsaraArmorSavePercent", 0); }
}

script "GlobalRecoil" (int duration, int intensity, int halfdampen, int forced) CLIENTSIDE
{
    if (CheckInventory("SamsaraRecoilIsDisabled") && !forced) { terminate; }

    int i = 0;

    for (i = 0; i < duration; i++)
    {
        SetActorPitch(0, GetActorPitch(0) - intensity);
        Delay(1);
    }

    for (i = duration; i > 0; i--)
    {
        SetActorPitch(0, GetActorPitch(0) + intensity / (halfdampen + 1));
        Delay(1);
    }
}

//Script that will determine the necessary damage to inflict
Script "ScriptedBulletDamage" (int idamage, int type, int ndamage)
{
	//Damage value that will be applied
	int damage = 0;
	
	//Get the current tid of the monster and generate a new one
	int newTid = UniqueTid();
	int myTid = ActivatorTid();
	
	//Generate new tid for the projectile
	int projTid = UniqueTid();
	Thing_ChangeTid(0,projTid);
	
	//Now assign the monster a new temporary tid
	SetActivator(0,AAPTR_TRACER);
	Thing_ChangeTid(0,newTid);
	//Get the enemy health - Zandronum netplay related
	int enemyHealth = GetActorProperty(0,APROP_Health);
	
	//Get the activator's player class
	SetActivator(projTid,AAPTR_TARGET);
	int pClass = PlayerClass(0);
	
	//Set the tid back to the projectile
	SetActivator(projTid);

	//Get the amount of damage to do based on the class script
	switch(pClass)
	{
		case CLASS_HALFLIFE:
			damage = ACS_NamedExecuteWithResult("HalfLife_BulletDamage",idamage);
			break;
		case CLASS_GOLDENEYE:
			if (type >= 1) { damage = ACS_NamedExecuteWithResult("Goldeneye_SlapperDamage",idamage); }
			else { damage = ACS_NamedExecuteWithResult("BondHitBox",idamage); }
			break;
		case CLASS_UNREAL:
			damage = ACS_NamedExecuteWithResult("UnrealHitBox", idamage, ndamage);
			break;
		case CLASS_RTCW:
			if (type >= 3) { damage = ACS_NamedExecuteWithResult("RTCW_KnifeDamage",0); }
			else if (type == 2) { damage = ACS_NamedExecuteWithResult("RTCW_BulletDamage",idamage,2); }
			else if (type == 1) { damage = ACS_NamedExecuteWithResult("RTCW_BulletDamage",idamage,1); }
			else { damage = ACS_NamedExecuteWithResult("RTCW_BulletDamage",idamage); }
			break;
		case CLASS_DEUSEX:
			if (type >= 2) { damage = ACS_NamedExecuteWithResult("DeusEx_BackDamage", ACS_NamedExecuteWithResult("DeusEx_WeaponSkillDamage", 2, idamage)); }
			else if (type == 1) { damage = ACS_NamedExecuteWithResult("DeusEx_DamageModifiers", ACS_NamedExecuteWithResult("DeusEx_WeaponSkillDamage", 3, idamage)); }
			else { damage = ACS_NamedExecuteWithResult("DeusEx_DamageModifiers", ACS_NamedExecuteWithResult("DeusEx_WeaponSkillDamage", 1, idamage)); }
			break;
		case CLASS_KINGPIN:
			damage = ACS_NamedExecuteWithResult("Kingpin_BulletDamage",idamage);
			break;
		case CLASS_SOF:
			damage = ACS_NamedExecuteWithResult("SoF_BulletDamage",idamage);	
			break;
	}
	
	//Now damage the actor as the projectile
	SetActivator(projTid,AAPTR_TARGET);
	
	//In Zandronum netplay, enemies can gib even if the puff has NOEXTREMEDEATH, this is here to check if it should just simply kill the enemy
	//We're using NameTag as Zandronum doesn't support DamageType but we can use another property that is supported as an exploit
	int noExtremeDeath = CheckFlag(projTid,"NOEXTREMEDEATH");
	
	//Behavior must change depending on if the NOEXTREMEDEATH flag exists
	//If NOEXTREMEDEATH is present, just take away as much health that's needed to zero them out
	Thing_Damage2(newTid, noExtremeDeath && (enemyHealth - damage < 0) ? enemyHealth : damage, GetActorProperty(projTid,APROP_NameTag));
	
	//Revert tids
	Thing_ChangeTid(newTid,myTid);
	Thing_ChangeTid(projTid,0);
}