str BrutalityBonuses[8][2] =
{
	{ "Bullet Sponge", "SoF_BulletSponge" },
	{ "Leng Tche", "SoF_LengTche" },
	{ "Alex Murphy", "SoF_AlexMurphy" },
	{ "The Juicer", "SoF_TheJuicer" },
	{ "The Eviscerator", "SoF_TheEviscerator" },
	{ "Melon Popper", "SoF_MelonPopper" },
	{ "TV Dinner", "SoF_TVDinner" },
	{ "Roasted", "SoF_Roasted" },
};

int SoFWeaponStates[12] = { "Knife", "Pistol", "Pistol", "Rifle", "Shotgun", "MachineGun", "Launcher", "MachineGun", "MachineGun", "MachineGun", "Pistol", "Rifle" };

#DEFINE SOF_ACTION_NULL -1
#DEFINE SOF_ACTION_RESET 0
#DEFINE SOF_ACTION_SPAWN 1
#DEFINE SOF_ACTION_WALK 2
#DEFINE SOF_ACTION_WSTRAFEL 3
#DEFINE SOF_ACTION_WSTRAFER 4
#DEFINE SOF_ACTION_WALKBACK 5
#DEFINE SOF_ACTION_RUN 6
#DEFINE SOF_ACTION_STRAFEL 7
#DEFINE SOF_ACTION_STRAFER 8
#DEFINE SOF_ACTION_RUNBACK 9
#DEFINE SOF_ACTION_LEANLEFTLOOP 10
#DEFINE SOF_ACTION_LEANRIGHTLOOP 11
#DEFINE SOF_ACTION_JUMPSTRAIGHT 12
#DEFINE SOF_ACTION_JUMPFORWARD 13
#DEFINE SOF_ACTION_SHOOTING 14
#DEFINE SOF_ACTION_CROUCH 15
#DEFINE SOF_ACTION_CROUCHFORWARD 16
#DEFINE SOF_ACTION_CROUCHLEFT 17
#DEFINE SOF_ACTION_CROUCHRIGHT 18
#DEFINE SOF_ACTION_CROUCHLEANLEFT 19
#DEFINE SOF_ACTION_CROUCHLEANRIGHT 20
#DEFINE SOF_ACTION_CROUCHSHOOTING 21
Script "SoF_Player" (void)
{
	int GZDoom = (GetCvar("samsara_zscriptready") == 1);
	int currentplayeraction = 0;
	int playerStillMoving = 0;
	int actionValue = 0; //I need this to reduce duplicated code
	int viewModelsLoaded = GetCvar("samsara_cl_viewmodelsloaded");
	int changeWeapon = 0;
	int lastLean = 0;
	int lastCrouch = 0;
	int currentCrouch = 0;
	int UsingFullScreen = false;
	int startIndex = 45600;
	int switchCounter = 0;
	int lastWeapon = 0;
	int switchGradient = 0;
	bool doSwitchWeaponWidget = false;
	ACS_NamedExecuteWithResult("SoF_HandleLean");
	
	//Prevent the widget from activating at the beginning
	lastWeapon = CheckInventory("SoF_SelectedWeapon");
	while(CheckInventory("SoFClass"))
	{
		SetInventory("SamsaraSOFMachinegunReloadDisplay", CheckInventory("SoF_MachinegunMagazine")); // placed here for netplay purposes
		if (CheckInventory("SamsaraReloadMode") >= 2 && CheckInventory("SamsaraHasInfiniteAmmo") <= 1) { SetInventory("SamsaraSOFRocketCycle", CheckInventory("SoF_RocketMagazine") % 4); }

		if (GetCVar("screenblocks") == 11 && CheckInventory("SamsaraUsingNewFullscreenHUD"))
		{
			UsingFullScreen = true;
			
			if(CheckInventory("SoF_SelectedWeapon") != lastWeapon)
				doSwitchWeaponWidget = true;
				
			if(doSwitchWeaponWidget)
			{
				if(switchGradient < 26)
					switchGradient+=2;
				else
				{
					switchCounter = 35;
					switchGradient = 27;
					doSwitchWeaponWidget = false;
				}
			}
			else switchCounter--;
			if(switchCounter <= 0 && !doSwitchWeaponWidget)
			{
				if(switchGradient > 1)
					switchGradient-=2;
				else switchGradient = 0;
			}
				
			//Weapon widget
			lastWeapon = CheckInventory("SoF_SelectedWeapon");
			
			//Finally draw
			ACS_NamedExecuteWithResult("SoF_DrawHud",startIndex,switchGradient,0,0);
		}
		//This is an optimization, instead of calling these a bunch of times, it should only need to call it once
		else if(UsingFullScreen == true)
		{
			RemoveMessages(startIndex,startIndex+15);
			UsingFullScreen = false;
		}

		int brutalityCounter = 0;
		
		for(int i = 0; i < 8; i++)
		{
			if(CheckInventory(strparam(s:BrutalityBonuses[i][1],s:"Timer")) <= 0) 
			{
				if(CheckInventory(strparam(s:BrutalityBonuses[i][1],s:"Multiplier")) > 0)
				{
					ACS_NamedExecuteWithResult("SoF_BrutalityRewards",i);
					ACS_NamedExecuteWithResult("SoF_DrawBrutality",i,1,brutalityCounter);
					SetInventory(strparam(s:BrutalityBonuses[i][1],s:"Multiplier"),0);
					SetInventory(strparam(s:BrutalityBonuses[i][1],s:"Delay"),18);
					brutalityCounter++;
				}
				else if(CheckInventory(strparam(s:BrutalityBonuses[i][1],s:"Delay")) > 0)
					brutalityCounter++;
				else
					SetInventory(strparam(s:BrutalityBonuses[i][1],s:"Delay"),0);
			}
			else
			{
				ACS_NamedExecuteWithResult("SoF_DrawBrutality",i,0,brutalityCounter);
				brutalityCounter++;
			}
			
			TakeInventory(strparam(s:BrutalityBonuses[i][1],s:"Timer"),1);
			TakeInventory(strparam(s:BrutalityBonuses[i][1],s:"Delay"),1);
		}
		
		int inputX = -GetPlayerInput(-1,MODINPUT_SIDEMOVE);
		int inputY = GetPlayerInput(-1,MODINPUT_FORWARDMOVE);
		
		// If the player is not dead, do this stuff, otherwise, wait until they are alive
		if(currentplayeraction >= SOF_ACTION_RESET)
		{
			int velX = GetActorVelX(0)>>16;
			int velY = GetActorVelY(0)>>16;
			int currentSpeed = sqrt(velX*velX + velY*velY)<<16;
			int currentWeapon = CheckInventory("SoF_SelectedWeapon");
			// If in GZDoom, give the weapon updater ZScript token. Otherwise, use behavior of the Assault Rifle
			if(GZDoom && viewModelsLoaded) GiveInventory("JohnMullinsWeaponUpdater",1);
			else currentWeapon = 3;
			
			// Set Current crouch value
			currentCrouch = isCrouching(26.0);
			
			// Set ChangeWeapon
			changeWeapon = currentWeapon != CheckInventory("SoF_LastWeapon");
			
			if(CheckInventory("SoF_PainToken"))
				currentplayeraction = SOF_ACTION_RESET;
			
			// Dead
			if(ClassifyActor(0) & ACTOR_DEAD) 
			{
				GiveInventory("SoF_EnablePain",1);
				int DeathSine = sin(GetActorAngle(0));
				//Do crouch death
				if(currentplayeraction >= SOF_ACTION_CROUCH)
					SetActorState(0,"CrouchDeath",true);
				else if(DeathSine * currentSpeed >= 8.0)
					SetActorState(0,"DeathBlowForward",true);
				else if(DeathSine * currentSpeed <= -8.0)
					SetActorState(0,"DeathBlowBack",true);
					
				//Do nothing, let the death animations take over for now
				currentplayeraction = SOF_ACTION_NULL;
				SetInventory("SoF_PlayerJumping",0); 
				SetInventory("SoF_LastWeapon",0); 
			} 
			//Leaning
			else if(CheckInventory("SoF_LeanCounter") != 5)
			{		
				GiveInventory("SoF_DisablePain",1);
				TakeInventory("SoF_PainToken",1);
				SetInventory("SoF_PlayerJumping",0);
				//Left
				if(CheckInventory("SoF_LeanCounter") == 1)
				{
					if((currentplayeraction != SOF_ACTION_LEANLEFTLOOP || changeWeapon) && !currentCrouch)
					{
						currentplayeraction = SOF_ACTION_LEANLEFTLOOP;
						SetActorState(0,strparam(s:"LeanLeftMid",s:SoFWeaponStates[currentWeapon-1]),true);
						SetInventory("SoF_LastWeapon",currentWeapon);
					}
					else if((currentplayeraction != SOF_ACTION_CROUCHLEANLEFT || changeWeapon) && currentCrouch)
					{
						currentplayeraction = SOF_ACTION_CROUCHLEANLEFT;
						SetActorState(0,strparam(s:"CrouchLeanLeftMid",s:SoFWeaponStates[currentWeapon-1]),true);
						SetInventory("SoF_LastWeapon",currentWeapon);
					}
				}
				//Right
				else if(CheckInventory("SoF_LeanCounter") == 9)
				{
					if((currentplayeraction != SOF_ACTION_LEANRIGHTLOOP || changeWeapon) && !currentCrouch)
					{
						currentplayeraction = SOF_ACTION_LEANRIGHTLOOP;
						SetActorState(0,strparam(s:"LeanRightMid",s:SoFWeaponStates[currentWeapon-1]),true);
						SetInventory("SoF_LastWeapon",currentWeapon);
					}
					if((currentplayeraction != SOF_ACTION_CROUCHLEANRIGHT || changeWeapon) && currentCrouch)
					{
						currentplayeraction = SOF_ACTION_CROUCHLEANRIGHT;
						SetActorState(0,strparam(s:"CrouchLeanRightMid",s:SoFWeaponStates[currentWeapon-1]),true);
						SetInventory("SoF_LastWeapon",currentWeapon);
					}
				}
				//Transitional frames
				else if(CheckInventory("SoF_LeanCounter") != 9 && CheckInventory("SoF_LeanCounter") != 1)
				{
					if(!currentCrouch)
					{
						if(SoFWeaponStates[currentWeapon] != "Launcher")
							SetActorState(0,strparam(s:"LeanToMulti",d:CheckInventory("SoF_LeanCounter")),true);
						else
							SetActorState(0,strparam(s:"LeanToLauncher",d:CheckInventory("SoF_LeanCounter")),true);
					}
					else
					{
						if(SoFWeaponStates[currentWeapon] != "Launcher")
							SetActorState(0,strparam(s:"CrouchLeanToMulti",d:CheckInventory("SoF_LeanCounter")),true);
						else
							SetActorState(0,strparam(s:"CrouchLeanToLauncher",d:CheckInventory("SoF_LeanCounter")),true);
					}
				}
			}
			//Jumping is a lower priority than leaning
			else if((GetPlayerInput(-1,MODINPUT_BUTTONS) & BT_JUMP) || CheckInventory("SoF_PlayerJumping"))
			{
				GiveInventory("SoF_EnablePain",1);
				TakeInventory("SoF_PainToken",1);
				if(currentSpeed <= 4.0)
				{
					if(currentplayeraction != SOF_ACTION_JUMPSTRAIGHT && !CheckInventory("SoF_PlayerJumping"))
					{
						SetActorState(0,strparam(s:"JumpStraight",s:SoFWeaponStates[currentWeapon-1]),true);
						currentplayeraction = SOF_ACTION_JUMPSTRAIGHT;
					}
				}
				else
				{
					if(currentplayeraction != SOF_ACTION_JUMPFORWARD && !CheckInventory("SoF_PlayerJumping"))
					{
						SetActorState(0,strparam(s:"JumpForward",s:SoFWeaponStates[currentWeapon-1]),true);
						currentplayeraction = SOF_ACTION_JUMPFORWARD;
					}
				}
			}
			else if((inputY != 0 || inputX != 0 || playerStillMoving > 0) && !CheckInventory("SoF_PainToken"))
			{
				SetInventory("SoF_PlayerJumping",0);
				//Add inertia to the player
				if(inputY != 0 || inputX != 0)
				{
					if(playerStillMoving < 16) 
						playerStillMoving+=2;
				}
				
				if(!currentCrouch)
				{
					//Check for running
					if(currentSpeed >= 8.0)
					{
						if(abs(inputY) > abs(inputX) && inputY > 0)
						{
							if(changeWeapon || currentplayeraction != SOF_ACTION_RUN)
							{
								currentplayeraction = SOF_ACTION_RUN;
								SetActorState(0,strparam(s:"Run",s:SoFWeaponStates[currentWeapon-1]),true);
								SetInventory("SoF_LastWeapon",currentWeapon);
							}
						}
						else if(abs(inputY) > abs(inputX) && inputY < 0)
						{
							if(changeWeapon || currentplayeraction != SOF_ACTION_RUNBACK)
							{
								currentplayeraction = SOF_ACTION_RUNBACK;
								SetActorState(0,strparam(s:"RunBack",s:SoFWeaponStates[currentWeapon-1]),true);
								SetInventory("SoF_LastWeapon",currentWeapon);
							}
						}
						else if(inputX > 0)
						{
							if(changeWeapon || currentplayeraction != SOF_ACTION_STRAFER)
							{
								currentplayeraction = SOF_ACTION_STRAFER;
								SetActorState(0,strparam(s:"StrafeR",s:SoFWeaponStates[currentWeapon-1]),true);
								SetInventory("SoF_LastWeapon",currentWeapon);
							}
						}
						else if(inputX < 0)
						{
							if(changeWeapon || currentplayeraction != SOF_ACTION_STRAFEL)
							{
								currentplayeraction = SOF_ACTION_STRAFEL;
								SetActorState(0,strparam(s:"StrafeL",s:SoFWeaponStates[currentWeapon-1]),true);
								SetInventory("SoF_LastWeapon",currentWeapon);
							}
						}
					} 
					//Check for walking speed
					else
					{
						if(abs(inputY) > abs(inputX) && inputY > 0)
						{
							if(changeWeapon || currentplayeraction != SOF_ACTION_WALK)
							{
								currentplayeraction = SOF_ACTION_WALK;
								SetActorState(0,strparam(s:"Walk",s:SoFWeaponStates[currentWeapon-1]),true);
								SetInventory("SoF_LastWeapon",currentWeapon);
							}
						}
						else if(abs(inputY) > abs(inputX) && inputY < 0)
						{
							if(changeWeapon || currentplayeraction != SOF_ACTION_WALKBACK)
							{
								currentplayeraction = SOF_ACTION_WALKBACK;
								SetActorState(0,strparam(s:"WalkBack",s:SoFWeaponStates[currentWeapon-1]),true);
								SetInventory("SoF_LastWeapon",currentWeapon);
							}
						}
						else if(inputX > 0)
						{
							if(changeWeapon || currentplayeraction != SOF_ACTION_WSTRAFER)
							{
								currentplayeraction = SOF_ACTION_WSTRAFER;
								SetActorState(0,strparam(s:"WStrafeR",s:SoFWeaponStates[currentWeapon-1]),true);
								SetInventory("SoF_LastWeapon",currentWeapon);
							}
						}
						else if(inputX < 0)
						{
							if(changeWeapon || currentplayeraction != SOF_ACTION_WSTRAFEL)
							{
								currentplayeraction = SOF_ACTION_WSTRAFEL;
								SetActorState(0,strparam(s:"WStrafeL",s:SoFWeaponStates[currentWeapon-1]),true);
								SetInventory("SoF_LastWeapon",currentWeapon);
							}
						}
					}
				}
				else
				{
					if(abs(inputY) > abs(inputX))
					{
						if(changeWeapon || currentplayeraction != SOF_ACTION_CROUCHFORWARD)
						{
							currentplayeraction = SOF_ACTION_CROUCHFORWARD;
							SetActorState(0,strparam(s:"CrouchForward",s:SoFWeaponStates[currentWeapon-1]),true);
							SetInventory("SoF_LastWeapon",currentWeapon);
						}
					}
					else if(inputX > 0 && currentSpeed >= 1.0)
					{
						if(changeWeapon || currentplayeraction != SOF_ACTION_CROUCHRIGHT)
						{
							currentplayeraction = SOF_ACTION_CROUCHRIGHT;
							SetActorState(0,strparam(s:"CrouchRight",s:SoFWeaponStates[currentWeapon-1]),true);
							SetInventory("SoF_LastWeapon",currentWeapon);
						}
					}
					else if(inputX < 0 && currentSpeed >= 1.0)
					{
						if(changeWeapon || currentplayeraction != SOF_ACTION_CROUCHLEFT)
						{
							currentplayeraction = SOF_ACTION_CROUCHLEFT;
							SetActorState(0,strparam(s:"CrouchLeft",s:SoFWeaponStates[currentWeapon-1]),true);
							SetInventory("SoF_LastWeapon",currentWeapon);
						}
					}
				}
			}	
			//Shooting
			else if(CheckInventory("SoF_ShootingToken") && !CheckInventory("SoF_PainToken"))
			{
				GiveInventory("SoF_EnablePain",1);
				if(!currentCrouch && currentplayeraction != SOF_ACTION_SHOOTING)
				{
					SetInventory("SoF_PlayerJumping",0);
					currentplayeraction = SOF_ACTION_SHOOTING;
					SetActorState(0,strparam(s:"Shoot",s:SoFWeaponStates[currentWeapon-1]),true);
				}
				else if(currentCrouch && currentplayeraction != SOF_ACTION_CROUCHSHOOTING)
				{
					SetInventory("SoF_PlayerJumping",0);
					currentplayeraction = SOF_ACTION_CROUCHSHOOTING;
					SetActorState(0,strparam(s:"CrouchShoot",s:SoFWeaponStates[currentWeapon-1]),true);
				}
			}
			//Spawn/Standing
			else if((changeWeapon || currentplayeraction != SOF_ACTION_SPAWN || currentplayeraction != SOF_ACTION_CROUCH) && !CheckInventory("SoF_PainToken"))
			{
				GiveInventory("SoF_EnablePain",1);
				if(!currentCrouch && (currentplayeraction != SOF_ACTION_SPAWN || changeWeapon))
				{
					SetInventory("SoF_PlayerJumping",0);
					currentplayeraction = SOF_ACTION_SPAWN;
					SetActorState(0,strparam(s:"Spawn",s:SoFWeaponStates[currentWeapon-1]),true);
					SetInventory("SoF_LastWeapon",currentWeapon);
				}
				else if(currentCrouch && (currentplayeraction != SOF_ACTION_CROUCH || changeWeapon))
				{
					SetInventory("SoF_PlayerJumping",0);
					currentplayeraction = SOF_ACTION_CROUCH;
					SetActorState(0,strparam(s:"Crouch",s:SoFWeaponStates[currentWeapon-1]),true);
					SetInventory("SoF_LastWeapon",currentWeapon);
				}
			}
			//Lower intertia
			if(playerStillMoving > 0) playerStillMoving--;
			
			//Set the last known crouch status
			lastCrouch = currentCrouch;
			
			Delay(1);
		}
		else
		{
			if(ClassifyActor(0) & ACTOR_ALIVE)
				currentplayeraction = 0;
				
			Delay(1);
		}

		Delay(1);
	}

	if(UsingFullScreen == true) { RemoveMessages(startIndex,startIndex+15); }
}

str SoFWeapons [12][4] = {
	{ "SoF_Knife", "", "SoF_Knives", "KNIFE" },
	{ "SoF_Pistol1", "SoF_Pistol1Magazine", "-1", "9MM PISTOL" },
	{ "SoF_Pistol2", "SoF_Pistol2Magazine", "Clip", ".44 PISTOL" },
	{ "SoF_AssaultRifle", "SoF_AssaultRifleMagazine", "Clip", "SMG" },
	{ "SoF_Shotgun", "SoF_ShotgunMagazine", "Shell", "SHOTGUN" },
	{ "SoF_Machinegun", "SoF_MachinegunMagazine", "Clip", "HEAVY MG" },
	{ "SoF_Rocket", "SoF_RocketMagazine", "RocketAmmo", "RCK LNCH" },
	{ "SoF_Flamegun", "SoF_FlameGunMagazine", "RocketAmmo", "FLAME GUN" },
	{ "SoF_Slugger", "SoF_SluggerMagazine", "Cell", "SLGTHRWR" },
	{ "SoF_MPG", "SoF_MPGMagazine", "Cell", "MPG" },
	{ "SoF_MPistol", "SoF_MPistolMagazine", "Clip", "SUP. SMG" },
	{ "SoF_SniperRifle", "SoF_SniperMagazine", "Shell", "SNIPER R" }
};

Script "SoF_DrawHud" (int startIndex, int switchGradient)
{
	int selectedWeapon = CheckInventory("SoF_SelectedWeapon")-1;
	int sof_health = GetActorProperty(0,APROP_Health);
	int sof_armor = CheckInventory("BasicArmor");
	//Set hud size. This seems pretty safe
	SetHudSize(800,600,0);	
	//Draw the status bar backdrop
	SetFont("SFFULBAR");
	HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+8,CR_UNTRANSLATED,0.1,600.2,0.0);
	if(switchGradient > 2)
	{
		SetFont("SFFULLIP");
		HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+7,CR_UNTRANSLATED,800.2,568.2,0.0);
	} else RemoveMessages(startIndex+7,startIndex+7);
	
	//Draw health amount
	SetFont("SOFHUDSM");
	HudMessage(d:sof_health;HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN|HUDMSG_COLORSTRING,startIndex+6,"SoFHudGreen",332.2,590.2,0.0);
	
	//Draw Health bar
	SetFont("SOFLIFEB");
	if(sof_health > 100) sof_health = 100;
	SetHudClipRect(350,576,124*FixedDiv(sof_health,100)>>16,16,0);
	HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+9,CR_UNTRANSLATED,348.1,576.1,0.0);
	SetHudClipRect(0,0,0,0,0);
	
	//Draw armor amount
	SetFont("SOFHUDSM");
	HudMessage(d:sof_armor;HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN|HUDMSG_COLORSTRING,startIndex+5,"SoFHudGreen",332.2,577.2,0.0);
	
	//Draw Armor bar
	SetFont("SOFARMOR");
	if(sof_armor > 100) sof_armor = 100;
	SetHudClipRect(330,568,152*FixedDiv(sof_armor,100)>>16,16,0);
	HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+4,CR_UNTRANSLATED,280.1,568.1,0.0);
	SetHudClipRect(0,0,0,0,0);

	//Draw the magazine counter
	RemoveMessages(startIndex+3,startIndex+3);
	if (CheckInventory("SamsaraReloadMode") >= 2)
	{
		SetFont("SOFSCONB");
		int sof_clip = CheckInventory(SoFWeapons[selectedWeapon][1]);
		if(sof_clip > 99) sof_clip = 99;
		HudMessage(s:strparam(s:(sof_clip < 10 ? "0" : ""),d:sof_clip);HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+3,CR_UNTRANSLATED,736.1,580.2,0.0);
	}
	
	//Display the total ammo amount
	RemoveMessages(startIndex+2,startIndex+2);
	if ((StrCmp(SoFWeapons[selectedWeapon][2], "") && StrCmp(SoFWeapons[selectedWeapon][2], "-1")) || (!StrCmp(SoFWeapons[selectedWeapon][2], "-1") && CheckInventory("PistolModeOn")))
	{
		SetFont("SOFHUDSM");
		int sof_ammo = CheckInventory(!StrCmp(SoFWeapons[selectedWeapon][2], "-1") ? "Clip" : SoFWeapons[selectedWeapon][2]);
		if(sof_ammo > 999) sof_ammo = 999;
		HudMessage(d:sof_ammo;HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN|HUDMSG_COLORSTRING,startIndex+2,"SoFHudGreen",722.2,583.2,0.0);
	}
	
	//Display the weapon name widget. If there is 5 pixels left, raise the drawing id of the moving widget
	SetFont("SFFULWEP");
	HudMessage(s:"A";HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,startIndex+11,CR_UNTRANSLATED,800.2,599.2 - switchGradient*1.0,0.0);
	SetFont("SOFHUDSM");
	HudMessage(s:SoFWeapons[selectedWeapon][3];HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN|HUDMSG_COLORSTRING,startIndex+10,"SoFHudGreen",722.1,567.2 - switchGradient*1.0,0.0);
	
	//Now might as well draw kills here
	SetFont("SOFHUDSM");
	int sof_kills = CheckInventory("KillCountAmountTrue");
	if(sof_kills > 999999) sof_kills = 999999;
	HudMessage(s:strparam(s:"Kills\n",d:sof_kills);HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN|HUDMSG_COLORSTRING,startIndex+1,"SoFHudGreen",46.4,580.2,0.0);
}

// This should help route actual server side information to the client
Script "SoF_DrawBrutality" (int type, int reward, int brutalityCounter)
{
	switch(type)
		{
			case 0:
				ACS_NamedExecuteWithResult("SoF_DrawBrutalityClient",type,reward,brutalityCounter,CheckInventory("SoF_BulletSpongeMultiplier"));
				break;
			case 1:
				ACS_NamedExecuteWithResult("SoF_DrawBrutalityClient",type,reward,brutalityCounter,CheckInventory("SoF_LengTcheMultiplier"));
				break;
			case 2:
				ACS_NamedExecuteWithResult("SoF_DrawBrutalityClient",type,reward,brutalityCounter,CheckInventory("SoF_AlexMurphyMultiplier"));
				break;
			case 3:
				ACS_NamedExecuteWithResult("SoF_DrawBrutalityClient",type,reward,brutalityCounter,CheckInventory("SoF_TheJuicerMultiplier"));
				break;
			case 4:
				ACS_NamedExecuteWithResult("SoF_DrawBrutalityClient",type,reward,brutalityCounter,CheckInventory("SoF_TheEvisceratorMultiplier"));
				break;
			case 5:
				ACS_NamedExecuteWithResult("SoF_DrawBrutalityClient",type,reward,brutalityCounter,CheckInventory("SoF_MelonPopperMultiplier"));
				break;
			case 6:
				ACS_NamedExecuteWithResult("SoF_DrawBrutalityClient",type,reward,brutalityCounter,CheckInventory("SoF_TVDinnerMultiplier"));
				break;
			case 7:
				ACS_NamedExecuteWithResult("SoF_DrawBrutalityClient",type,reward,brutalityCounter,CheckInventory("SoF_RoastedMultiplier"));
				break;
		}
}

Script "SoF_DrawBrutalityClient" (int type, int reward, int brutalityCounter, int multiplier) clientside
{
	SetFont("SOFHUDBG");
	SetHudSize(1280,800,0);
	str primaryReward = "";
	str secondaryReward = "";
	
	switch(type)
	{
		case 0:
			if(reward)
			{
				primaryReward = strparam(s:"\c[SoFHUDRed]",d:multiplier,s:"\c[SoFHUDWhite] - Ammo 1");
				secondaryReward = multiplier >= 5 ? strParam(s:", \c[SoFHUDRed]",d:multiplier/5,s:"\c[SoFHUDWhite] - Armor") : "";
			}
			break;
		case 1:
			if(reward)
			{
				primaryReward = strparam(s:"\c[SoFHUDRed]",d:multiplier,s:"\c[SoFHUDWhite] - Health");
				secondaryReward = multiplier >= 20 ? strParam(s:", \c[SoFHUDRed]",d:1,s:"\c[SoFHUDWhite] - Knife") : "";
			}
			break;
		case 2:
			if(reward)
			{
				primaryReward = strparam(s:"\c[SoFHUDRed]",d:multiplier,s:"\c[SoFHUDWhite] - Ammo 1");
				secondaryReward = multiplier >= 2 ? strParam(s:", \c[SoFHUDRed]",d:multiplier/5,s:"\c[SoFHUDWhite] - Ammo 2") : "";
			}
			break;
		case 3:
			if(reward)
			{
				primaryReward = strparam(s:"\c[SoFHUDRed]",d:multiplier,s:"\c[SoFHUDWhite] - Armor");
				secondaryReward = multiplier >= 4 ? strParam(s:", \c[SoFHUDRed]",d:multiplier/4,s:"\c[SoFHUDWhite] - Ammo 3") : "";
			}
			break;
		case 4:
			if(reward)
			{
				primaryReward = strparam(s:"\c[SoFHUDRed]",d:multiplier,s:"\c[SoFHUDWhite] - Health");
				secondaryReward = strParam(s:", \c[SoFHUDRed]",d:multiplier,s:"\c[SoFHUDWhite] - Armor");
			}
			break;
		case 5:
			if(reward)
			{
				primaryReward = strparam(s:"\c[SoFHUDRed]",d:multiplier,s:"\c[SoFHUDWhite] - Armor");
				secondaryReward = multiplier >= 10 ? strParam(s:", \c[SoFHUDRed]",d:5,s:"\c[SoFHUDWhite] - Ammo 2") : "";
			}
			break;
		case 6:
			if(reward)
			{
				primaryReward = strparam(s:"\c[SoFHUDRed]",d:multiplier,s:"\c[SoFHUDWhite] - Ammo 4");
				secondaryReward = multiplier >= 4 ? strParam(s:", \c[SoFHUDRed]",d:multiplier/4,s:"\c[SoFHUDWhite] - Health") : "";
			}
			break;
		case 7:
			if(reward)
			{
				primaryReward = strparam(s:"\c[SoFHUDRed]",d:multiplier,s:"\c[SoFHUDWhite] - Ammo 4");
				secondaryReward = multiplier >= 10 ? strParam(s:", \c[SoFHUDRed]",d:multiplier/10,s:"\c[SoFHUDWhite] - Ammo 3") : "";
			}
			break;
	}
	
	if(reward)
	{
		HudMessage(s:strparam(s:BrutalityBonuses[type][0],s:" Reward:\n");HUDMSG_LAYER_OVERHUD|HUDMSG_NOTWITHFULLMAP|HUDMSG_FADEOUT,60+type*2,CR_UNTRANSLATED,640.0,720.0-(40.0*brutalityCounter),0.5,0.5);
		HudMessage(s:primaryReward,s:secondaryReward;HUDMSG_LAYER_OVERHUD|HUDMSG_NOTWITHFULLMAP|HUDMSG_FADEOUT,61+type*2,CR_UNTRANSLATED,640.0,736.0-(40.0*brutalityCounter),0.5,0.5);
		SetHudClipRect(0,0,0,0,0);
	}
	else
	{
		if(CheckInventory(strparam(s:BrutalityBonuses[type][1],s:"Timer")) > 0)
			drawBonusBar(type, brutalityCounter);
		else RemoveMessages(60+type*2,61+type*2);
	}
}

function void drawBonusBar (int type, int brutalityCounter)
{
	SetFont("SOFHUDBG");
	SetHudSize(1280,800,0);
	HudMessage(s:strparam(s:BrutalityBonuses[type][0],s:" ",s:"\c[SoFHUDRed]x",d:CheckInventory(strparam(s:BrutalityBonuses[type][1],s:"Multiplier")));HUDMSG_LAYER_OVERHUD|HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN|HUDMSG_COLORSTRING,60+type*2,CR_UNTRANSLATED,640.0,716.0-(40.0*brutalityCounter),0.0);
	SetHudSize(640,400,0);
	SetHudClipRect(256,364-(20*brutalityCounter),FixedMul(128.0,FixedDiv(CheckInventory(strparam(s:BrutalityBonuses[type][1],s:"Timer"))*1.0,105.0))>>16,16,0);
	SetFont("SOFCOMBO");
	HudMessage(s:"A";HUDMSG_LAYER_OVERHUD|HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,61+type*2,CR_UNTRANSLATED,320.0,364.0-(20.0*brutalityCounter),0.0);
	SetHudClipRect(0,0,0,0,0);
	return;
}

Script "SoF_BrutalityRewards" (int type)
{
	switch(type)
	{
		case 0:
			GiveInventory("Clip",CheckInventory("SoF_BulletSpongeMultiplier"));
			if(CheckInventory("SoF_BulletSpongeMultiplier") >= 5)
				GiveInventory("ArmorScrapArmorNormal",CheckInventory("SoF_BulletSpongeMultiplier")/5);
			break;
		case 1:
			GiveInventory("HealthBonus",CheckInventory("SoF_LengTcheMultiplier"));
			if(CheckInventory("SoF_LengTcheMultiplier") >= 20)
				GiveInventory("SoF_Knives",1);
			break;
		case 2:
			GiveInventory("Clip",CheckInventory("SoF_AlexMurphyMultiplier"));
			if(CheckInventory("SoF_AlexMurphyMultiplier") >= 2)
				GiveInventory("Shell",CheckInventory("SoF_AlexMurphyMultiplier")/5);
			break;
		case 3:
			GiveInventory("ArmorScrapArmorNormal",CheckInventory("SoF_TheJuicerMultiplier"));
			if(CheckInventory("SoF_TheJuicerMultiplier")/4)
				GiveInventory("RocketAmmo",CheckInventory("SoF_TheJuicerMultiplier")/4);
			break;
		case 4:
			GiveInventory("HealthBonus",CheckInventory("SoF_TheEvisceratorMultiplier"));
			GiveInventory("ArmorScrapArmorNormal",CheckInventory("SoF_TheEvisceratorMultiplier"));
			break;
		case 5:
			GiveInventory("ArmorScrapArmorNormal",CheckInventory("SoF_MelonPopperMultiplier"));
			if(CheckInventory("SoF_MelonPopperMultiplier") >= 10)
				GiveInventory("Shell",3);
			break;
		case 6:
			GiveInventory("Cell",CheckInventory("SoF_TVDinnerMultiplier"));
			if(CheckInventory("SoF_TVDinnerMultiplier")/4)
				GiveInventory("HealthBonus",CheckInventory("SoF_TVDinnerMultiplier")/4);
			break;
		case 7:
			GiveInventory("Cell",CheckInventory("SoF_RoastedMultiplier"));
			if(CheckInventory("SoF_RoastedMultiplier")/4)
				GiveInventory("RocketAmmo",CheckInventory("SoF_TVDinnerMultiplier")/10);
			break;
	}
}

Script "SoF_HandleLean" (void)
{
	int leanCounter = 0;
	//Need it to remain centered so it does nothing stupid
	SetInventory("SoF_LeanCounter",5);
	while(true)
	{
		// Do lean stuff. I gotta do this system earlier than I'd like unfortunately
		int buttons = GetPlayerInput(-1,INPUT_BUTTONS);
		int sideMove = GetPlayerInput(-1,INPUT_SIDEMOVE);
		ChangeActorRoll(0,0.00625*leanCounter,1);
		if((buttons & BT_USER1 || buttons & BT_USER2) && sideMove != 0)
		{
			if(sideMove < 0)
			{
				SetInventory("SoF_Leaning",1);
				SetPlayerProperty(0,1,PROP_FROZEN);
				SetActorVelocity(0,0,0,GetActorVelZ(0),0,0);
				if(leanCounter > -8)
				{
					leanCounter--;
					doLean(-4.0);
				}
			}
			else if(sideMove > 0)
			{
				SetInventory("SoF_Leaning",2);
				SetPlayerProperty(0,1,PROP_FROZEN);
				SetActorVelocity(0,0,0,GetActorVelZ(0),0,0);
				if(leanCounter < 8)
				{
					leanCounter++;
					doLean(4.0);
				}	
			}

			if(leanCounter == 0) { SetInventory("SoF_Leaning",0); TakeInventory("SoF_FullyLeaned",1); }
		}
		else
		{
			SetInventory("SoF_Leaning",0);
			if(leanCounter < 0)
			{
				//SetInventory("SoF_Leaning",2);
				leanCounter++;
				doLean(4.0);
			}
			else if(leanCounter > 0)
			{
				//SetInventory("SoF_Leaning",1);
				leanCounter--;
				doLean(-4.0);
			}
			else { SetPlayerProperty(0,0,PROP_FROZEN); TakeInventory("SoF_FullyLeaned",1); }
		}
		
		if(buttons & BT_ATTACK) SetInventory("SoF_Shooting",1);
		else SetInventory("SoF_Shooting",0);
		
		SetInventory("SoF_LeanCounter",5+(leanCounter/2));
		
		Delay(1);
	}
}

function void doLean(int amount)
{
	Warp(0,0,amount,0,0,WARPF_INTERPOLATE);
}

Script "SoF_Decorate" (int operation, int arg1, int arg2)
{
	int newtid = 0;
	int oldTid = 0;
	int height = 0;
	int radius = 0;
	int xPos, yPos, zPos;
	int mXPos, mYPos, mZPos;
	int result = 0;
	switch(operation)
	{
		//Check if animation frame needs to be wiped
		case 1:
			SetInventory("SoF_WeaponAnimState",arg1);
			if(CheckInventory("SoF_WeaponAnimState") != CheckInventory("SoF_LastWeaponAnimState"))
			{
				SetInventory("SoF_WeaponAnimFrame",0);
				SetInventory("SoF_LastWeaponAnimState",CheckInventory("SoF_WeaponAnimState"));
			}
			break;
		case 2:
			GiveInventory("SoF_SwitchHand",1);
			Delay(15);	
			SetInventory("SoF_SwitchHand",0);
			break;
		case 3:
			SetActivator(0,AAPTR_Master);
			GiveInventory("SoF_RemoveCorpseChildren",1);
			SetActorState(0,"SoFGibStart",1);
			break;
		case 4:
			newtid = UniqueTid();
			Thing_ChangeTid(0,newtid);	
			SetActivator(0,AAPTR_Master);
			int spawnHealth = GetActorProperty(0,APROP_SpawnHealth)*10;
			
			if(spawnHealth > 500)
				spawnHealth = 500;
				
			SetActivator(newtid,AAPTR_Default);
			Thing_ChangeTid(newtid,0);
			SetActorProperty(0,APROP_Health,spawnHealth);
			break;
		case 5:
			SetActivator(0,AAPTR_Master);
			if (Random(0, 1) == 0) { PlayActorSound(0, SOUND_Pain, CHAN_VOICE); }
			switch(arg1)
			{
				case 0:
					SetActorState(0,"Death.SoFSMGDelay",1);
					break;
				case 1:
					SetActorState(0,"Death.SoFHighCaliberDelay",1);
					break;
			}
			break;
		case 6:
			oldTID = ActivatorTID();
			newtid = UniqueTID();
			Thing_ChangeTID(0, newtid);
			SetActivator(0,AAPTR_Master);
			height = (GetActorProperty(0,APROP_Height)*4)>>16;
			radius = GetActorProperty(0,APROP_Radius)>>16;
			//To make up for my mistake that is too widespread to address head on, I will do it here
			SetActorPosition(newtid,GetActorX(0),GetActorY(0),GetActorZ(0)+(height/2)*1.0,0);

			SetActivator(newtid);
			Thing_ChangeTID(newtid, oldTID);
			int spacecube = height*radius*radius;
			int count = spacecube/4096;
			if(spacecube < 5000) { SetActorProperty(0,APROP_ScaleX,0.5); SetActorProperty(0,APROP_ScaleY,0.5); count*=3; }
			else if(spacecube < 50000) { SetActorProperty(0,APROP_ScaleX,1.0); SetActorProperty(0,APROP_ScaleY,1.0); count*=3; }
			else if(spacecube < 500000) { SetActorProperty(0,APROP_ScaleX,1.25); SetActorProperty(0,APROP_ScaleY,1.25); }
			else if(spacecube < 1000000) { SetActorProperty(0,APROP_ScaleX,1.5); SetActorProperty(0,APROP_ScaleY,1.5); }
			else { SetActorProperty(0,APROP_ScaleX,2.0); SetActorProperty(0,APROP_ScaleY,2.0); }
			if(count < 2)
				SetResultValue(1);
			else
				SetResultValue(count/(1+!isSinglePlayer()));
			break;
		case 7:
			newtid = UniqueTID();
			SpawnForced("SoF_GibberLooker",GetActorX(0),GetActorY(0),GetActorZ(0),newtid);
			//Flip the angle of this thing so it faces backward
			SetPointerExt(AAPTR_TRACER,0,newtid);
			//Assign the shooter to this object
			SetActivator(0,AAPTR_TARGET);
			SetPointerExt(AAPTR_TARGET,0,newtid);
			//Change the angle, the same as the shooter
			SetActorAngle(newtid,GetActorAngle(0));
			break;
		case 8:
			SetActivator(0,AAPTR_TRACER);
			Thing_Remove(0);
			break;
		case 9:
			xPos = GetActorX(0);
			YPos = GetActorY(0);
			ZPos = GetActorZ(0);
			SetActivator(0,AAPTR_MASTER);
			mXPos = GetActorX(0);
			mYPos = GetActorY(0);
			mZPos = GetActorZ(0);
			//PrintBold(s:"X Position: ",d:xPos-mXPos>>16,s:"\nY Position: ",d:yPos-mYPos>>16,s:"\nZ Position: ",d:zPos-mZPos>>16);
			switch(arg1)
			{
				case 0: //X
					SetResultValue(xPos-mXPos>>16);
					break;
				case 1: //Y
					SetResultValue(yPos-mYPos>>16);
					break;
				case 2: //Z
					SetResultValue(zPos-mZPos>>16);
					break;
			}
			break;
		case 10:
			result = CheckInventory("SoF_GibberDamageType");
			if(result == 0) result = 5;
			SetInventory("SoF_GibberDamageType",0);
			SetResultValue(result);
			break;
		case 13:
			GiveInventory("SoF_MPG_AmmoTaker", 1);
			GiveInventory("SoF_MPG_FireToken",1);
			Delay(1);
			GiveInventory("SoF_MPG_FireToken",1);
			break;
		case 14:
			SetActivator(0,AAPTR_TRACER);
			if((CheckInventory("SoF_MPG_InflationCounter") < 30) && (ClassifyActor(0) & ACTOR_ALIVE))
			{
				if (GetActorProperty(0, APROP_Accuracy) == -1) //if (CheckActorState(0,"SoFMPGLaserExpand",1))
				{
					SetActorState(0,"SoFMPGLaserExpand",true);
					SetResultValue(0);
				}
				else
				{
					SetResultValue(12);
				}
			}
			else if(CheckInventory("SoF_MPG_InflationCounter") >= 30)
			{
				SetResultValue(GetActorProperty(0,APROP_SpawnHealth)+5000);
			}
			break;
		case 15:
			SetResultValue(CheckInventory("SoF_MPG_InflationCounter"));
			break;
		case 16:
			If(CheckInventory("SoF_MPG_InflationCounter") > 1) break;
			else
			{
				GiveInventory("SoF_MPGBurnStart",1);
				int startX = GetActorProperty(0,APROP_ScaleX);
				int startY = GetActorProperty(0,APROP_ScaleY);
				
				PlaySound(0,"SoF/Weapons/mpg/Expand",CHAN_AUTO,1.0,true,0.5);
				
				while(CheckInventory("SoF_MPG_InflationCounter") > 0 && ClassifyActor(0) > 1)
				{
					SetActorProperty(0,APROP_ScaleX,FixedMul(startX,1.0+(CheckInventory("SoF_MPG_InflationCounter") * 0.01)));
					SetActorProperty(0,APROP_ScaleY,FixedMul(startY,1.0+(CheckInventory("SoF_MPG_InflationCounter") * 0.01)));
					Delay(4);
					if(!CheckInventory("SoF_MPG_PainExtender")) TakeInventory("SoF_MPG_InflationCounter",1);
					else { TakeInventory("SoF_MPG_PainExtender",1); }
				}
				SetInventory("SoF_MPG_InflationCounter",0);
				TakeInventory("SoF_MPGAlreadyBurning",1);
				StopSound(0,CHAN_AUTO);
			}
			break;
		//Brutality timer trackers, these are to deduct time added depending on how high the multiplier is
		case 17:
			str type = "";
			switch(arg1)
			{
				case 0:
					SetActivator(0,AAPTR_TARGET);
					type = "SoF_BulletSpongeMultiplier";
					break;
				case 1:
					SetActivator(0,AAPTR_TARGET);
					type = "SoF_LengTcheMultiplier";
					break;
				case 2:
					SetActivator(0,AAPTR_TARGET);
					type = "SoF_AlexMurphyMultiplier";
					break;
				case 3:
					SetActivator(0,AAPTR_TARGET);
					type = "SoF_TheJuicerMultiplier";
					break;
				case 4:
					SetActivator(0,AAPTR_TARGET);
					type = "SoF_TheEvisceratorMultiplier";
					break;
				case 5:
					type = "SoF_MelonPopperMultiplier";
					break;
				case 6:
					type = "SoF_TheEvisceratorMultiplier";
					break;
				case 7:
					SetActivator(0,AAPTR_TARGET);
					type = "SoF_TVDinnerMultiplier";
					break;
				case 8:
					SetActivator(0,AAPTR_TARGET);
					type = "SoF_RoastedMultiplier";
					break;
			}
			SetResultValue(105-(CheckInventory(type)*5));
			break;

        case 18:
            if (CheckInventory("SamsaraReloadMode") >= 2 && CheckInventory("SamsaraHasInfiniteAmmo") <= 1) { SetInventory("SamsaraSOFRocketCycle", CheckInventory("SoF_RocketMagazine") % 4); }
            else
            {
                // this won't really be as consistent with the altfire, but it's something
                if (arg1 > 0)
                {
                    if (!CheckInventory("SamsaraSOFRocketCycle")) { SetInventory("SamsaraSOFRocketCycle", 3); }
                    else { TakeInventory("SamsaraSOFRocketCycle", 1); }
                }
            }
            break;
	}
}

Script "SoF_Decorate_Client" (int operation, int arg1, int arg2) CLIENTSIDE
{
	int newtid = 0;
	int oldTid = 0;
	int result = 0;
	switch(operation)
	{
		case 1:
			newtid = UniqueTid();
			SpawnForced("SoF_RocketFlare",GetActorX(0),GetActorY(0),GetActorZ(0),newTid);
			SetPointerExt(AAPTR_MASTER,0,newTid);
			while(ClassifyActor(0) > 1)
			{
				Warp(newtid,-20.0,0,0,0,WARPF_NOCHECKPOSITION|WARPF_MOVEPTR|WARPF_INTERPOLATE);
				Delay(1);
			}
			Thing_Remove(newtid);
			break;
		case 2:
			newtid = UniqueTid();
			oldtid = UniqueTid();
			SpawnForced("SoF_SlugParticle",GetActorX(0),GetActorY(0),GetActorZ(0),newTid);
			SpawnForced("SoF_SlugFlare",GetActorX(0),GetActorY(0),GetActorZ(0),oldtid);
			while(ClassifyActor(0) > 1)
			{
				Warp(newtid,0,0,0,0,WARPF_NOCHECKPOSITION|WARPF_MOVEPTR|WARPF_INTERPOLATE);
				Warp(oldtid,0,0,0,0,WARPF_NOCHECKPOSITION|WARPF_MOVEPTR|WARPF_INTERPOLATE);
				Delay(1);
			}
			Thing_Remove(newtid);
			Thing_Remove(oldtid);
			break;
	}
}

//A decorate won't convert a decimal to a floating point as far as my knowledge goes, so it's up to the decorate to multiply the intended decimal by 65536
Script "SoF_FX" (int type, int duration, int maxSize)
{
	int i = 0;
	int startScaleX = GetActorProperty(0,APROP_ScaleX);
	int startScaleY = GetActorProperty(0,APROP_ScaleY);
	int startAlpha = GetActorProperty(0,APROP_Alpha);
	switch(type)
	{
		case 1:
			for(i = 0; i <= duration; i++)
			{
				//SetActorProperty(0,APROP_Alpha,(1.0/duration)*i);
				SetActorProperty(0,APROP_ScaleX,startScaleX+(maxSize/duration)*i);
				SetActorProperty(0,APROP_ScaleY,startScaleY+(maxSize/duration)*i);
				Delay(1);
			}
			for(i = duration; i >= 0; i--)
			{
				SetActorProperty(0,APROP_Alpha,(1.0/duration)*i);
				Delay(1);
			}
			Thing_Remove(0);
			break;
		case 2:
			for(i = 0; i <= duration; i++)
			{
				SetActorProperty(0,APROP_ScaleX,startScaleX+(maxSize/duration)*i);
				SetActorProperty(0,APROP_ScaleY,startScaleY+(maxSize/duration)*i);
				Delay(1);
			}
			Thing_Remove(0);
			break;
		case 3:
			SetActorProperty(0,APROP_Alpha,0.0);
			for(i = 0; i <= duration; i++)
			{
				SetActorProperty(0,APROP_Alpha,(startAlpha/duration)*i);
				SetActorProperty(0,APROP_ScaleX,startScaleX+(maxSize/duration)*i);
				SetActorProperty(0,APROP_ScaleY,startScaleY+(maxSize/duration)*i);
				Delay(1);
			}
			for(i = duration; i >= 0; i--)
			{
				SetActorProperty(0,APROP_Alpha,(startAlpha/duration)*i);
				Delay(1);
			}
			Thing_Remove(0);
			break;
		case 4:
			for(i = 0; i <= duration; i++)
			{
				SetActorProperty(0,APROP_Alpha,(startAlpha/duration)*(duration-i));
				SetActorProperty(0,APROP_ScaleX,startScaleX+(maxSize/duration)*i);
				SetActorProperty(0,APROP_ScaleY,startScaleY+(maxSize/duration)*i);
				Delay(1);
			}
			Thing_Remove(0);
			break;
	}
}

Script "SoF_BulletDamage" (int damage)
{
	int bulletType = 0;

    if (CheckInventory("SamsaraSOFAttackIsKnifeMelee")) { bulletType = 1; }
    else if (CheckInventory("SamsaraSOFAttackIsKnifeRanged")) { bulletType = 2; }
    else if (CheckInventory("SamsaraSOFAttackIsShotgun")) { bulletType = 3; }

    /*
    switch (bullettype)
    {
      default: break;
      case 1: PrintBold(s:"melee knife"); break;
      case 2: PrintBold(s:"ranged knife"); break;
      case 3: PrintBold(s:"shotgun"); break;
    }
    */

	int bulletX = GetActorX(0);
	int bulletY = GetActorY(0);
	int bulletZ = GetActorZ(0);

	SetActivator(0,AAPTR_Tracer);

	if(CheckFlag(0,"NOBLOOD")) { SetResultValue(damage); terminate; }

	int monsterX = GetActorX(0);
	int monsterY = GetActorY(0);
	int monsterZ = GetActorZ(0);
	int monsterHealth = GetActorProperty(0,APROP_Health);
	int monsterHeight = GetActorProperty(0,APROP_Height);
	int monsterWidth = GetActorProperty(0,APROP_Radius)*2;
	int monsterAngle, vang, angle;
	int health = GetActorProperty(0,APROP_SpawnHealth);

	if (health >= 1000)
	{
		SetResultValue(damage);
	}
	else if(monsterWidth >= monsterHeight && !CheckInventory("IsFatButBiped"))
	{
		monsterAngle = GetActorAngle(0);
		vang = VectorAngle(monsterX - bulletX, monsterY - bulletY);
		angle = vang % 1.0;
				
		if(!CheckInventory("SoF_PerformedHeadShot") && !CheckInventory("NoHeadShots") && bulletZ > monsterZ + FixedMul(monsterHeight,0.35) && bulletZ < monsterZ + FixedMul(monsterHeight,0.65) && ((abs(monsterAngle - angle)) < 0.65 && (abs(monsterAngle - angle)) > 0.35))
		{
			if(bulletType != 2 && monsterHealth - (damage*2) <= -damage)
			{
				SoF_HitDamageBrutalityBonus(0);
				GiveInventory("SoF_PerformedHeadShot",1);
				GiveInventory("SoF_BloodHeadshotGenerator",1);
			}
		
			SetResultValue(2 * damage * !CheckInventory("SoF_IsDeathGibber"));
		}
		else
		{
			if(GetActorClass(0) == "SoF_DeathGibber")
				GiveInventory("SoF_GibberSeverGenerator",1);
				
			SetResultValue(damage);
		}
	}
	else
	{
		if(bulletZ > monsterZ + FixedMul(monsterHeight,0.75))
		{
			if(bulletType != 2 && !CheckInventory("SoF_PerformedHeadShot") && monsterHealth - (damage*2) <= -damage)
			{
				SoF_HitDamageBrutalityBonus(0);
				GiveInventory("SoF_PerformedHeadShot",1);
				GiveInventory("SoF_BloodHeadshotGenerator",1);
			}
		
			int result;
			if(GetCvar("samsara_mixerloaded"))
				result = ACS_NamedExecuteWithResult("Goldeneye_HatShot",0,0,0,0);
			else
				result = 0;

			if(result == -1)
			{
				SetResultValue(-1);
				terminate;
			}
			//if(StrLeft(GetActorClass(0),4)=="RTCW" && GetCvar("samsara_mixerloaded"))
				//GiveInventory("RTCW_RemoveHat",1);
				
			
			SetResultValue(2 * damage * !CheckInventory("SoF_IsDeathGibber"));
		}
		else if(bulletType == 1 || bulletType == 3)
		{
			monsterAngle = GetActorAngle(0);
			vang = VectorAngle(monsterX - bulletX, monsterY - bulletY);
			angle = vang % 1.0;
			if(GetActorClass(0) == "SoF_DeathGibber")
			{
				if(random(0,4) == 0) 
					if(bulletType == 1)
						GiveInventory("SoF_GibberSeverKnifeGenerator",1);
					else
						GiveInventory("SoF_GibberSeverGenerator",1);
				SoF_SetGibberType(3);
			}
			else if(!CheckInventory("SoF_ShotgunStomachShot") && bulletZ > monsterZ + FixedMul(monsterHeight,0.35) && bulletZ < monsterZ + FixedMul(monsterHeight,0.65) && ((abs(monsterAngle - angle)) < 0.65 && (abs(monsterAngle - angle)) > 0.35))
			{
				GiveInventory("SoF_ShotgunStomachShot",1);
				SoF_HitDamageBrutalityBonus(1);
			}
			
			SetResultValue(damage);
		}
		else
		{
			if(GetActorClass(0) == "SoF_DeathGibber")
				GiveInventory("SoF_GibberSeverGenerator",1);
				
			SetResultValue(damage);
		}
	}
}

function void SoF_HitDamageBrutalityBonus (int type)
{
	if (!GetCvar("samsara_nosofbrutalities"))
	{
		SetActivator(0,AAPTR_TRACER);
		if(type == 0) { GiveInventory("SoF_MelonPopperTimer",ACS_NamedExecuteWithResult("SoF_Decorate",17,5)); GiveInventory("SoF_MelonPopperMultiplier",1); }
		else if(type == 1) { GiveInventory("SoF_TheEvisceratorTimer",ACS_NamedExecuteWithResult("SoF_Decorate",17,6)); GiveInventory("SoF_TheEvisceratorMultiplier",1); }
	}
}

function void SoF_SetGibberType (int count)
{
	SetActivator(0,AAPTR_Master);
	SetInventory("SoF_GibberDamageType",3);
}

Script "SoF_BloodGenerator_Offsets" (void)
{
	int missilex = GetActorX(0);
	int missiley = GetActorY(0);
	int missilez = GetActorZ(0);
	int missileAngle = GetActorAngle(0);
	SetActivator(0,AAPTR_Tracer);

	int enemyx = GetActorX(0);
	int enemyy = GetActorY(0);
	int enemyz = GetActorZ(0);
	int currentangle = GetActorAngle(0);
	int vang = VectorAngle(enemyx - missilex, enemyy - missiley);
	int angle = vang % 1.0;
	SetInventory("SoF_BloodGeneratorAngle",angle+65536);
	SetInventory("SoF_BloodGeneratorBleedAngle",missileAngle+65536);
	SetInventory("SoF_BloodGeneratorZ",(missilez - enemyz)>>16 + 65536);
}

Script "SoF_BloodGenerator_Return" (int mode)
{
	int result;
	switch(mode)
	{
		case 1:
			result = ((CheckInventory("SoF_BloodGeneratorAngle") - 65536)/182)+180;
			break;
		case 2:
			result = CheckInventory("SoF_BloodGeneratorZ");
			break;
		case 3:
			result = ((CheckInventory("SoF_BloodGeneratorBleedAngle") - 65536)/182);
			break;
	}
	SetResultValue(result);
}

Script "SoF_BloodPool" (int type)
{
	int ownerTid = uniqueTid();
	SpawnForced(strparam(s:"SoF_BloodPool",s:type == 1 ? "Gib" : ""),GetActorX(0),GetActorY(0),GetActorFloorZ(0),ownerTid);
	Thing_SetTranslation(ownerTid,-1);
	SetActivator(0,AAPTR_MASTER);
	SetPointerExt(AAPTR_MASTER,0,ownerTid);
	SetActorProperty(ownerTid,APROP_ScaleX,GetActorProperty(0,APROP_Radius)/20);
	Thing_ChangeTid(ownerTid,0);
}

Script "SoF_DrawLaserToClient" (int type)
{
	int x = GetActorX(0);
	int y = GetActorY(0);
	int z = GetActorZ(0);
	SetActivatorToTarget(0);
	ACS_NamedExecuteWithResult("SoF_DrawMPGLaser",x,y,z,type);
}

Script "SoF_DrawMPGLaser" (int tx, int ty, int tz, int type) clientside
{
	int t, k = 0, l, angle, pitch, x, y, z, vx, vy, vz, mag, magI, height, space, horz, i;
	str segment;
	int leanMod = 0;
	if(CheckInventory("SoF_Leaning") == 1) leanMod = 4.0;
	else if(CheckInventory("SoF_Leaning") == 2) leanMod = -4.0;
	
	//Properties
	switch(type)
	{
		case 0:
			height = GetActorViewHeight(0) - 9.0;
			space = 32;
			horz = 8.0 + leanMod;
			i = 40;
			segment = "SoF_MPGLaserSegment";
			break;
		case 1:
			height = GetActorViewHeight(0) - 9.0;
			space = 16;
			horz = 8.0 + leanMod;
			i = 40;
			segment = "SoF_MPGAltFireTrail";
			break;
	}
	
	int newtid = UniqueTid();
	
	int xoff = FixedMul(sin(GetActorAngle(0)),horz);
	int yoff = FixedMul(cos(GetActorAngle(0)),horz);
		
    x = GetActorX(0) + xoff;
	y = GetActorY(0) - yoff;
	z = GetActorZ(0) + height;
	
	int vectorx = tx - x;
	int vectory = ty - y;
	int vectorz = tz - z;
	angle = VectorAngle(vectorx, vectory);
	
	int length = magnitudeTwo(vectorx>>16,vectory>>16);
	pitch = VectorAngle(length<<16, vectorz);

    vx = tx-x; vy = ty-y; vz = tz-z; mag = magnitudeThree_f(vx, vy, vz);
    vx = FixedDiv(vx, mag); vy = FixedDiv(vy, mag); vz = FixedDiv(vz, mag);
    magI = ftoi(mag);
    for (i = i; i < magI; i += space)
    {
        SpawnForced(segment, x+(vx*i), y+(vy*i), z+(vz*i), newtid);
		SetActorPitch(newtid, pitch);
		SetActorAngle(newtid, angle);
		
		
		if(type == 1 && ((i % 128) == 8))
			Delay(1);

		if(i % 1500 == 0)
			Delay(1);
    }
}

Script "SoF_DoScope" (void) clientside
{
	while(CheckInventory("SoF_SniperScoped"))
	{
		int zoomLevel = CheckInventory("SoF_SniperZoomLevel");
		if(zoomLevel < 6) zoomLevel = 6;
		SetHudSize(280,240,0);
		SetFont("SOFSCOPE");
		HudMessage(s:"A";HUDMSG_LAYER_UNDERHUD|HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,59,CR_UNTRANSLATED,140.0,120.0,0.0);
		
		SetHudSize(400,280,0);
		SetFont(strparam(s:"SOFSCO0",d:2+CheckInventory("SoF_SniperZoomLevel")%4));
		HudMessage(s:"A";HUDMSG_LAYER_UNDERHUD|HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,58,CR_UNTRANSLATED,200.0,140.0,0.0);
		
		SetHudSize(400,120,0);
		SetFont("SOFSCO06");
		HudMessage(s:"A";HUDMSG_LAYER_UNDERHUD|HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,57,CR_UNTRANSLATED,0.0,60.0,0.0);
		
		SetHudSize(400,400,0);
		SetFont("SOFSCO07");
		HudMessage(s:"A";HUDMSG_LAYER_UNDERHUD|HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,56,CR_UNTRANSLATED,0.0,290.0-(7.0*(zoomLevel)),0.0);
		
		SetHudSize(1600,1600,0);
		SetFont("SOFSCONM");
		HudMessage(d:CheckInventory("SoF_SniperZoomLevel");HUDMSG_LAYER_UNDERHUD|HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,55,CR_UNTRANSLATED,0.0,536.0,0.0);
		
		RemoveMessages(49,54);
		
		SetFont("SOFSCO01");
		SetHudSize(480,480,0);

        int curammo = 0;

        if (CheckInventory("SamsaraReloadMode") >= 2) { curammo = CheckInventory("SoF_SniperMagazine"); }
        else { curammo = CheckInventory("Shell"); }

        if (curammo > 6) { curammo = 6; }
        else if (curammo < 0) { curammo = 0; }

		for(int a = 0; a < curammo; a++)
		{
			HudMessage(s:((GetCVar("screenblocks") == 11 && CheckInventory("SamsaraUsingNewFullscreenHUD")) || (GetCVar("screenblocks") >= 12)) ? "A" : "";HUDMSG_LAYER_UNDERHUD|HUDMSG_NOTWITHFULLMAP|HUDMSG_PLAIN,49+a,CR_UNTRANSLATED,480.0,400.0-16.0*a,0.0);
		}
		
		Delay(1);
	}
	RemoveMessages(49,59);
}

Script "SoF_CheckWeapon" (void)
{
	for(int a = 0; a < 12; a++)
	{
		if(CheckWeapon(SoFWeapons[a][0]))
		{
			//Only do the thing if the weapon changed.
			if(CheckInventory("SoF_SelectedWeapon") != (a + 1))
				SetInventory("SoF_SelectedWeapon",a+1);
			break;
		}
	}	
}

script "SoFMachinegunReloadDisplayInit" (void) { SetInventory("SamsaraSOFMachinegunReloadDisplay", CheckInventory("SoF_MachinegunMagazine")); } // also used for netplay, funnily enough
