int activetokenselectors[CLASSCOUNT];
int pickrandos = 0;
int pickrandomitems = 0;

#DEFINE MISC_LIFESABEACH 2
#DEFINE MISC_DUKE64 4
#DEFINE MISC_HLOP 2

str miscCharGameTypesStr[CLASSCOUNT] =
{
	"",
	"",
	"",
	"",
	"",
	"samsara_misccharspawn_duke3d",
	"",
	"",
	"samsara_misccharspawn_rott",
	"",
	"samsara_misccharspawn_blood",
	"samsara_misccharspawn_strife",
	"",
	"",
	"samsara_misccharspawn_rmr",
	"",
	"",
	"",
	"",
	"samsara_misccharspawn_halflife",
	"samsara_misccharspawn_sw",
	"",
	"samsara_misccharspawn_ps",
	"samsara_misccharspawn_rr",
	"samsara_misccharspawn_quake2",
	"samsara_misccharspawn_hexen2",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	""
};

function void createCellCheckers(str cellCheckClass)
{
	for (int a = 512; a <= 0.5; a += 1024)
	{
		int fixedA = a * 1.0;

		for (int b = 512; b <= 0.5; b += 1024)
		{
			int fixedB = b * 1.0;

			SpawnForced(cellCheckClass, fixedA, fixedB, 0, 0);

			if (b > 0)
				b = -b - 1024;
			else
				b = -b;
		}

		if (a > 0)
			a = -a - 1024;
		else
			a = -a;
	}
}

function void createSpawnCheckers(str spawnCheckClass, int cvarValueChars, int cvarValueItems)
{
	int chanceToSpawnChars = (cvarValueChars * cvarValueChars)/10;
	int chanceToSpawnItems = (cvarValueItems * cvarValueItems)/10;

	if (chanceToSpawnChars <= 0 && GetCVar("samsara_randomcharacters") > 0) { chanceToSpawnChars = 1; }
	if (chanceToSpawnItems <= 0 && GetCVar("samsara_randomitems") > 0) { chanceToSpawnItems = 1; }

	int x = GetActorX(0);
	int y = GetActorY(0);
	int newTid = UniqueTID();

	for (int a = -512; a < 512; a += 64)
	{
		int xPos = x + (a * 1.0);

		for (int b = -512; b < 512; b += 64)
		{
			int yPos = y + (b * 1.0);
			int randomValue = random(1,1500);
			if (randomValue <= chanceToSpawnChars && randomValue <= chanceToSpawnItems && pickRandos)
			{
				SpawnForced(spawnCheckClass, xPos, yPos, 0, newtid);
				GiveActorInventory(newtid,"ValidSpawnCheckAll",1);
			}
			else if (randomValue <= chanceToSpawnChars && pickRandos)
			{
				SpawnForced(spawnCheckClass, xPos, yPos, 0, newtid);
			}
			else if (randomValue <= chanceToSpawnItems)
			{
				SpawnForced(spawnCheckClass, xPos, yPos, 0, newtid);
				GiveActorInventory(newtid,"ValidSpawnCheckItems",1);
			}
		}
	}
}

Script "DetermineValidSpawn" (void)
{
	// Don't bother with checking spawn conditions when random characters won't spawn anyway
	if ((GetCVar("samsara_randomcharacters") + GetCVar("samsara_randomitems")) <= 0)
	{
		terminate;
	}
	str cellCheckClass = GetCVar("samsara_zscriptready") == 1 ? "DetermineValidCellZS" : "DetermineValidCell";

	createCellCheckers(cellCheckClass);
}

script "CellDoneScanning" (void)
{
	str spawnCheckClass = GetCVar("samsara_zscriptready") == 1 ? "DetermineValidSpawnZS" : "DetermineValidSpawn";
	int randomCharactersCVar = GetCVar("samsara_randomcharacters");
	int randomItemsCVar = GetCVar("samsara_randomitems");

	createSpawnCheckers(spawnCheckClass, randomCharactersCVar, randomItemsCVar);
}

script "IsThisSpawnSpotorCell" (int type)
{
	if(type == 0)
		SetResultValue(GetActorClass(0)=="DetermineValidCell");
	else
		SetResultValue(GetActorClass(0)=="DetermineValidSpawn");
}

script "HeroOnMap" Open
{
	if(GameType () == GAME_TITLE_MAP) { terminate; }

	if(isCompetitiveGameMode() && GetCVar("samsara_deathmatchcharacters") == false) { terminate; }

	int clients = PlayerCount();
	int playervalue;
	int setBasedSpawns = GetCvar("samsara_misccharacterspawnmode");

	for(int a = 0; a < CLASSCOUNT; a++)
	{
		activetokenselectors[a] = 0;
	}

	for(int p = 0; p < clients; p++)
	{
		if(PlayerInGame(p) == true)
		{
			for(int b = 0; b < CLASSCOUNT; b++)
			{
				if(PlayerClass(p) == b && !setBasedSpawns)
				{
					if(b == 5 || b == 8 || b == 10 || b == 11 || b == 14 || b == 19 || b == 20 || b == 22 || b == 23 || b == 24 || b == 25)
						pickrandos = 1;

					if (GetCVar("samsara_moddedgame")) { b = 0; }

					switch(b)
					{
						default:
							activetokenselectors[b] = 1;
							break;
						case 5:
							if(!(activetokenselectors[b] & 1<<GetUserCvar(p,"samsara_cl_dukemode")))
								activetokenselectors[b] += 1<<GetUserCvar(p,"samsara_cl_dukemode");
							break;
						case 19:
							if(!(activetokenselectors[b] & 1<<GetUserCvar(p,"samsara_cl_shephardmode")))
								activetokenselectors[b] += 1<<GetUserCvar(p,"samsara_cl_shephardmode");
							break;
					}
				}
				else if(GetCvar(miscCharGameTypesStr[b]) >= 1 && setBasedSpawns)
				{
					activetokenselectors[b] = 31;
					pickrandos = 1;
				}
			}
		}
		else
		{
			clients += 1;
		}
	}

	ACS_NamedExecuteWithResult("DetermineValidSpawn",0,0,0,0);
}

Script "Samsara2689" (void)  //2689
{
	int myPosX = GetActorX(0);
	int myPosY = GetActorY(0);
	int myPosZ = GetActorZ(0);

	int randomAngle = random(0,256);
	int randomPick = random(0,256);
	SetActorAngle(0,randomAngle<<8);
	ThrustThing(randomAngle,random(16,32),0,0);
	Delay(1);
	int myTid = UniqueTid();
	Thing_ChangeTid(0,myTid);
	int maxAttempts = 0;
	int zandronumGameMode = (isLMS() || isDeathMatch() || isInvasion() || isFreeForAll() || isTeamGame());

	int setBasedSpawns = GetCvar("samsara_misccharacterspawnmode");
	int dukeMode = GetCvar("samsara_misccharspawn_duke3d");
	int HLMode = GetCvar("samsara_misccharspawn_halflife");

	int newX = GetActorX(0)/1.0;
	int newY = GetActorY(0)/1.0;

	int floor1 = GetSectorFloorZ(0,newX-32,newY);
	int floor2 = GetSectorFloorZ(0,newX+32,newY);
	int floor3 = GetSectorFloorZ(0,newX,newY-32);
	int floor4 = GetSectorFloorZ(0,newX,newY+32);

	if(floor1 != floor2 || floor1 != floor3 || floor1 != floor4)
		terminate;

	while(maxAttempts <= 100)
	{
		int a, b;

		if(activetokenselectors[a] > 0)
		{
			switch(a)
			{
				default:
					break;
				case 5:
					if (dukeMode <= 1)
					{
						if(activetokenselectors[a] & MISC_LIFESABEACH)
							if (zandronumGameMode) { SpawnSpotFacing("Duke3DBeachBabeSpawnerDeathmatch", 0, 0); }
							else { SpawnSpotFacing("Duke3DBeachBabeSpawner", 0, 0); }
						else if(activetokenselectors[a] & MISC_DUKE64)
						{
							a = random(0,CLASSCOUNT);
							continue;
						}
						else
							if (zandronumGameMode) { SpawnSpotFacing("Duke3DBabeDeathmatch", 0, 0); }
							else { SpawnSpotFacing("Duke3DBabe", 0, 0); }
						break;
					}
					else if (dukeMode == 2)
					{
						if (zandronumGameMode) { SpawnSpotFacing("Duke3DBabeDeathmatch", 0, 0); }
						else { SpawnSpotFacing("Duke3DBabe", 0, 0); }
						break;
					}
					else if (dukeMode == 3)
					{
						if (zandronumGameMode) { SpawnSpotFacing("Duke3DBeachBabeSpawnerDeathmatch", 0, 0); }
						else { SpawnSpotFacing("Duke3DBeachBabeSpawner", 0, 0); }
						break;
					}
					else if (dukeMode == 4)
					{
						if(random(0,2) <= 1)
							SpawnSpotFacing("Duke3DBeachBabeSpawner", 0, 0);
						else
							if (zandronumGameMode) { SpawnSpotFacing("Duke3DBabeDeathmatch", 0, 0); }
							else { SpawnSpotFacing("Duke3DBabe", 0, 0); }
						break;
					}
				case 8:
					if(onLiquid(0) > 0)
					{
						a = random(0,CLASSCOUNT);
						continue;
					}
					else if(randompick <= 96)
						Spawn("RoTTBlades", myPosX, myPosY, myPosZ, 0);
					else if(randompick <= 188)
						Spawn("RoTTFireJet", myPosX, myPosY, myPosZ, 0);
					else if(randompick <= 256)
						Spawn("RoTTUpSpikes", myPosX, myPosY, myPosZ, 0);
					break;
				case 10:
					if(random(0,2) <= 1)
						SpawnSpotFacing("BloodInnocentMime", 0, 0);
					else
						SpawnSpotFacing("BloodInnocentMoron", 0, 0);
					break;
				case 11:
					if (zandronumGameMode) { SpawnSpotFacing("StrifePeasantDeathmatch", 0, 0); }
					else { SpawnSpotFacing("StrifePeasant", 0, 0); }
					break;
				case 14:
					if(random(0,2) <= 1)
						SpawnSpotFacing("RMRLDFGuard", 0, 0);
					else
						SpawnSpotFacing("RMRLDFMilitia", 0, 0);
					break;
				case 19:
					if (HLMode <= 1)
					{
						if(activetokenselectors[a] & MISC_HLOP)
						{
							if(random(0,2) <= 1)
								if (zandronumGameMode) { SpawnSpotFacing("HECU_FGrunt_Opp_SmallDeathmatch", 0, 0); }
								else { SpawnSpotFacing("HECU_FGrunt_Opp_Small", 0, 0); }
							else
								if (zandronumGameMode) { SpawnSpotFacing("HECU_FGrunt_Opp_MGDeathmatch", 0, 0); }
								else { SpawnSpotFacing("HECU_FGrunt_Opp_MG", 0, 0); }
							break;
						}
						if(random(0,2) <= 1)
							if (zandronumGameMode) { SpawnSpotFacing("HLScientistDeathmatch", 0, 0); }
							else { SpawnSpotFacing("HLScientist", 0, 0); }
						else
							if (zandronumGameMode) { SpawnSpotFacing("HLSecurityGuardDeathmatch", 0, 0); }
							else { SpawnSpotFacing("HLSecurityGuard", 0, 0); }
						break;
					}
					else if (HLMode == 2)
					{
						if(random(0,2) <= 1)
							if (zandronumGameMode) { SpawnSpotFacing("HLScientistDeathmatch", 0, 0); }
							else { SpawnSpotFacing("HLScientist", 0, 0); }
						else
							if (zandronumGameMode) { SpawnSpotFacing("HLSecurityGuardDeathmatch", 0, 0); }
							else { SpawnSpotFacing("HLSecurityGuard", 0, 0); }
						break;
					}
					else if (HLMode == 3)
					{
						if(random(0,2) <= 1)
							if (zandronumGameMode) { SpawnSpotFacing("HECU_FGrunt_Opp_SmallDeathmatch", 0, 0); }
							else { SpawnSpotFacing("HECU_FGrunt_Opp_Small", 0, 0); }
						else
							if (zandronumGameMode) { SpawnSpotFacing("HECU_FGrunt_Opp_MGDeathmatch", 0, 0); }
							else { SpawnSpotFacing("HECU_FGrunt_Opp_MG", 0, 0); }
						break;
					}
					else if (HLMode == 4)
					{
						if(random(0,2) <= 1)
							if(random(0,2) <= 1)
								if (zandronumGameMode) { SpawnSpotFacing("HECU_FGrunt_Opp_SmallDeathmatch", 0, 0); }
								else { SpawnSpotFacing("HECU_FGrunt_Opp_Small", 0, 0); }
							else
								if (zandronumGameMode) { SpawnSpotFacing("HECU_FGrunt_Opp_MGDeathmatch", 0, 0); }
								else { SpawnSpotFacing("HECU_FGrunt_Opp_MG", 0, 0); }
						else
							if(random(0,2) <= 1)
								if (zandronumGameMode) { SpawnSpotFacing("HLScientistDeathmatch", 0, 0); }
								else { SpawnSpotFacing("HLScientist", 0, 0); }
							else
								if (zandronumGameMode) { SpawnSpotFacing("HLSecurityGuardDeathmatch", 0, 0); }
								else { SpawnSpotFacing("HLSecurityGuard", 0, 0); }
						break;
					}
				case 20:
					if(random(0,2) == 0 && onLiquid(0) == 1)
						SpawnSpotFacing("SW_WashGirl", 0, 0);
					else if(randompick<=24)
						SpawnSpotFacing("SW_MechanicGirl", 0, 0);
					else if(randompick<=48)
						SpawnSpotFacing("SW_CarGirl", 0, 0);
					else if(randompick<=72)
						SpawnSpotFacing("SW_MoonGirl", 0, 0);
					else if(randompick<=160)
						SpawnSpotFacing("SW_Rabbit", 0, 0);
					else
						if (zandronumGameMode) { SpawnSpotFacing("SWPruneGirlSpawnerDeathmatch", 0, 0); }
						else { SpawnSpotFacing("SWPruneGirlSpawner", 0, 0); }
					break;
				case 22:
					if(randompick<=128)
						SpawnSpotFacing("AnubisWarriorReinc", 0, 0);
					else if(random(0,1) == 1)
						SpawnSpotFacing("PSHaremGirl1", 0, 0);
					else if(random(0,1) == 1)
						SpawnSpotFacing("PSHaremGirl2", 0, 0);
					else if(random(0,1) == 1)
						SpawnSpotFacing("PSHaremGirl3", 0, 0);
					else if(random(0,1) == 1)
						SpawnSpotFacing("PSHaremGirl4", 0, 0);
					else if(random(0,1) == 1)
						SpawnSpotFacing("PSHaremGirl5", 0, 0);
					else if(random(0,1) == 1)
						SpawnSpotFacing("PSHaremGirl6", 0, 0);
					else
						SpawnSpotFacing("PSHaremGirl7", 0, 0);
					break;
				case 23:
					if(random(0,1) == 1)
						SpawnSpotFacing("RedneckRampage_Chicken", 0, 0);
					else if(random(0,1) == 1)
						SpawnSpotFacing("RedneckRampage_Pig", 0, 0);
					else if(random(0,1) == 1)
						SpawnSpotFacing("RedneckRampage_Cow", 0, 0);
					else
						SpawnSpotFacing("RRBanjoConcert", 0, 0);
					break;
				case 24:
					if (zandronumGameMode) { SpawnSpotFacing("Q2InsaneDeathmatch", 0, 0); }
					else { SpawnSpotFacing("Q2Insane", 0, 0); }
					break;
				case 25:
					SpawnSpotFacing("Hexen2_Sheep", 0, 0);
					break;
			}
			terminate;
		}
		else
		{
			a = random(0,CLASSCOUNT);
		}

		maxAttempts++;
	}
}

Script "AllyCellPhone" ENTER
{
	If(CheckInventory("HexenClass") || CheckInventory("RoTTClass") || CheckInventory("POGreedClass") || CheckInventory("EradClass") || CheckInventory("RRClass") || CheckInventory("BondClass"))
	{
		if(!CheckInventory("AllyCellPhone") && !CheckInventory("SamsaraAlliesAreBanned") && CheckInventory("KillCountBar") == 250 && !CheckInventory("CellPhoneGiven"))
		{
			GiveInventory("AllyCellPhone", 1);
			GiveInventory("CellPhoneGiven", 1);
		}
		else if(CheckInventory("CellPhoneGiven") && !CheckInventory("AllyCellPhone"))
		{
			TakeInventory("CellPhoneGiven", 1);
			TakeInventory("KillCountBar", 250);
		}
		delay(1);
		restart;
	}
	else
	{
		terminate;
	}
}

str rottdropstrings[5] = {"DropIan","DropTaradino","DropThi","DropLorelei","DropDoug"};
/*str hexendropstrings[3] = {"DropFighter","DropMage","DropClassic"};
str hexenclassicdropstrings[3] = {"DropFighter","DropMage","DropCleric"};
str hexenmagedropstrings[3] = {"DropFighter","DropCleric","DropClassic"};
str hexenfighterdropstrings[3] = {"DropCleric","DropClassic","DropMage"};*/
str hexendropstrings[2] = {"DropFighter","DropMage"};
str hexenmagedropstrings[2] = {"DropFighter","DropCleric"};
str hexenfighterdropstrings[2] = {"DropCleric","DropMage"};
str eradicatordropstrings[4] = {"DropEleena","DropKamechak","DropDan","DropMarine"};
str ipogdropstrings[5] = {"DropMooman","DropCyborg","DropLizard","DropSpecimen","DropDominatrix"};

Script "Samsara2999" (int class, int mode)
{
	int resultcounter = 0;
	int maxallies = 2;
	if(class == 1)
		mode = ceilZandronum((mode*1.0)/100); //the shit I have to do to cleanup Zandronum's mistakes
	if(class == 3)
		mode = ceilZandronum((mode*1.0)/100); //the shit I have to do to cleanup Zandronum's mistakes
	if(class == 4)
		mode = ceilZandronum((mode*1.0)/100); //the shit I have to do to cleanup Zandronum's mistakes
	Switch(class)
	{
		Case 1:
		maxallies = 5;
		For(int a = 0; a < 36; a++)
		{
			Delay(1);
			If(a==35)
			{
				if(resultcounter == maxallies)
				{
					SetActorState(0,"Death",TRUE);
					terminate;
				}

				if(mode != resultcounter)
				{
					//PrintBold(d:resultcounter);
					SetActorState(0,rottdropstrings[resultcounter],TRUE);
				}

				a=0;
				resultcounter++;
			}
		}
		break;
		Case 2:
		maxallies = 2;
		For(int b = 0; b < 36; b++)
		{
			Delay(1);
			If(b==35)
			{
				If(resultcounter == maxallies)
				{
					SetActorState(0,"Death",TRUE);
					terminate;
				}
				switch(mode)
				{
					/*case 1:
						SetActorState(0,hexenclassicdropstrings[resultcounter],TRUE);
						b=0;
						resultcounter++;
						break;*/
					case 2:
						SetActorState(0,hexenmagedropstrings[resultcounter],TRUE);
						b=0;
						resultcounter++;
						break;
					case 3:
						SetActorState(0,hexenfighterdropstrings[resultcounter],TRUE);
						b=0;
						resultcounter++;
						break;
					default:
						SetActorState(0,hexendropstrings[resultcounter],TRUE);
						b=0;
						resultcounter++;
						break;
				}
			}
		}
		break;
		Case 3:
		maxallies = 4;
		For(int c = 0; c < 36; c++)
		{
			Delay(1);
			If(c==35)
			{
				If(resultcounter == maxallies)
				{
					SetActorState(0,"Death",TRUE);
					terminate;
				}
				
				if(mode != resultcounter)
				{
					//PrintBold(d:resultcounter);
					SetActorState(0,eradicatordropstrings[resultcounter],TRUE);
				}
				
				c=0;
				resultcounter++;
			}
		}
		break;
		Case 4:
		maxallies = 5;
		For(int d = 0; d < 36; d++)
		{
			Delay(1);
			If(d==35)
			{
				If(resultcounter == maxallies)
				{
					SetActorState(0,"Death",TRUE);
					terminate;
				}
				
				if(mode != resultcounter)
				{
					//PrintBold(d:resultcounter);
					SetActorState(0,ipogdropstrings[resultcounter],TRUE);
				}

				d=0;
				resultcounter++;
			}
		}
		break;
	}
}

Script "Samsara_AllyBeaconDrops" (void)
{
	switch (samsaraClassNum())
	{
		case CLASS_ROTT:
			SetResultValue(CheckInventory("RottMode"));
			break;
		case CLASS_ERAD:
			SetResultValue(CheckInventory("EradMode"));
			break;
		case CLASS_POGREED:
			SetResultValue(CheckInventory("IPoGMode"));
			break;
	}
}

script "Samsara_AllySwitch" (void)
{
    int activator = ActivatorTID();
    int playeractivator = ActivatorTID();
    int newtid = UniqueTID();

    Thing_ChangeTID(0, newtid);
    SetActivator(0, AAPTR_MASTER);

    int pln = PlayerNumber();
    int playertid = UniqueTID();
    int newtid2 = UniqueTID();

    Thing_ChangeTID(0, playertid);

    str allyswitchfrom = "Placeholder", allyswitchto = "Placeholder";

    switch (PlayerClass(pln))
    {
      case CLASS_HEXEN:
        switch (GetUserCVar(pln, "samsara_cl_hexclass"))
        {
          case 0:
          case 1:
            allyswitchfrom = "ClericAlly";
            allyswitchto = "FighterAlly";
            break;

          case 2:
            allyswitchfrom = "MageAlly";
            allyswitchto = "ClericAlly";
            break;

          case 3:
            allyswitchfrom = "FighterAlly";
            allyswitchto = "MageAlly";
            break;
        }
        break;

      case CLASS_ROTT:
        switch (GetUserCVar(pln, "samsara_cl_rottmode"))
        {
          case 0:
            allyswitchfrom = "IanPaulFreeley";
            allyswitchto = "DougWendt";
            break;

          case 1:
            allyswitchfrom = "TaradinoCassatt";
            allyswitchto = "IanPaulFreeley";
            break;

          case 2:
            allyswitchfrom = "ThiBarret";
            allyswitchto = "TaradinoCassatt";
            break;

          case 3:
            allyswitchfrom = "LoreleiNi";
            allyswitchto = "ThiBarret";
            break;

          case 4:
            allyswitchfrom = "DougWendt";
            allyswitchto = "LoreleiNi";
            break;
        }
        break;

      case CLASS_ERAD:
        switch (GetUserCVar(pln, "samsara_cl_eradmode"))
        {
          case 0:
            allyswitchfrom = "EleenaBrynstaarl";
            allyswitchto = "AllianceCommando";
            break;

          case 1:
            allyswitchfrom = "Kamechak";
            allyswitchto = "EleenaBrynstaarl";
            break;

          case 2:
            allyswitchfrom = "DanBlaze";
            allyswitchto = "Kamechak";
            break;

          case 3:
            allyswitchfrom = "AllianceCommando";
            allyswitchto = "DanBlaze";
            break;
        }
        break;

      case CLASS_POGREED:
        switch (GetUserCVar(pln, "samsara_cl_ipogmode"))
        {
          case 0:
            allyswitchfrom = "MoomanAlly";
            allyswitchto = "DominatrixAlly";
            break;

          case 1:
            allyswitchfrom = "CyborgAlly";
            allyswitchto = "MoomanAlly";
            break;

          case 2:
            allyswitchfrom = "LizardAlly";
            allyswitchto = "CyborgAlly";
            break;

          case 3:
            allyswitchfrom = "SpecimenAlly";
            allyswitchto = "LizardAlly";
            break;

          case 4:
            allyswitchfrom = "DominatrixAlly";
            allyswitchto = "SpecimenAlly";
            break;
        }
        break;
    }

    if (CheckActorClass(newtid, allyswitchfrom)) { SpawnSpotFacingForced(allyswitchto, newtid, newtid2); }
    else { terminate; }

    SetActorAngle(newtid2, GetActorAngle(newtid));
    Thing_SetTranslation(newtid2, -1);

    SetActivator(newtid2, AAPTR_DEFAULT);
    SetPointer(AAPTR_MASTER, playertid);

    Thing_Remove(newtid);
    Thing_ChangeTID(playertid, playeractivator);
    Thing_ChangeTID(0, activator);
}

script "Samsara_BeaconSpawner" (int mode)
{
    int pln = PlayerNumber();
    int newtid = UniqueTID();
    int playertid = UniqueTID();
    int activator = ActivatorTID();

    Thing_ChangeTID(0, playertid);

    switch (PlayerClass(pln))
    {
      case CLASS_HEXEN:
        switch(mode)
        {
          case 0: SpawnForced("StrifeBeaconHexen_Allies", GetActorX(0), GetActorY(0), GetActorZ(0), newtid); break;
          case 1: SpawnForced("StrifeBeaconHexenMage_Allies", GetActorX(0), GetActorY(0), GetActorZ(0), newtid); break;
          case 2: SpawnForced("StrifeBeaconHexenFighter_Allies", GetActorX(0), GetActorY(0), GetActorZ(0), newtid); break;
        }
        break;

      case CLASS_ROTT:
        SpawnSpotForced("StrifeBeaconRott_Allies", 0, newtid, 0);
        SetActorAngle(newtid, CheckInventory("RottMode") * 182);
        break;

      case CLASS_ERAD:
        SpawnSpotForced("StrifeBeaconErad_Allies", 0, newtid, 0);
        SetActorAngle(newtid, CheckInventory("EradMode") * 182);
        break;

      case CLASS_POGREED:
        SpawnSpotForced("StrifeBeaconPOGreed_Allies", 0, newtid, 0);
        SetActorAngle(newtid, CheckInventory("IpogMode") * 182);
        break;
    }

    Thing_SetTranslation(newtid, -1);

    SetActivator(newtid, AAPTR_DEFAULT);
    SetPointer(AAPTR_MASTER, playertid);

    Thing_ChangeTID(playertid, activator);
}

Script "Samsara_AllyCheckMaster" (void)
{
	SetResultValue(SetActivator(0,AAPTR_MASTER));
}

Script "CellPhoneHax" (int mode) //2560
{
	Switch(mode)
	{
		Case 0:
			Delay(160);
			GiveInventory("AllyCellPhoneHax1",1);
			break;
		Case 1:
			Delay(160);
			GiveInventory("AllyCellPhoneHax2",1);
			break;
	}
}

Script "Samsara_AllyHealthRegen" (void)
{
	While(GetActorProperty(0, APROP_Health) > 0)
	{
		HealThing(1);
		Delay(35);
	}
}

Script "Samsara2689_Items" (void)
{
	int myPosX = GetActorX(0);
	int myPosY = GetActorY(0);
	int myPosZ = GetActorZ(0);

	int randomAngle = random(0,256);
	int randomPick = random(0,256);
	SetActorAngle(0,randomAngle<<8);
	ThrustThing(randomAngle,random(16,32),0,0);
	Delay(1);
	int myTid = UniqueTid();
	Thing_ChangeTid(0,myTid);
	int maxAttempts = 0;

	int newX = GetActorX(0)/1.0;
	int newY = GetActorY(0)/1.0;

	int floor1 = GetSectorFloorZ(0,newX-32,newY);
	int floor2 = GetSectorFloorZ(0,newX+32,newY);
	int floor3 = GetSectorFloorZ(0,newX,newY-32);
	int floor4 = GetSectorFloorZ(0,newX,newY+32);

	str setItemSpawns = GetCvar("samsara_randomitempool") == 1 ? "SamsaraRandomItemSpawnerFull" : "SamsaraRandomItemSpawnerBalanced";
	str setItemSpawnsExtra = GetCvar("samsara_randomitempool") == 1 ? "SamsaraRandomItemSpawnerFullExtra" : "SamsaraRandomItemSpawnerBalancedExtra";

	if(floor1 != floor2 || floor1 != floor3 || floor1 != floor4)
		terminate;

	while(maxAttempts <= 100)
	{
		if(GetCvar("samsara_randomitemextras"))
		{
			SpawnSpotFacing(setItemSpawnsExtra, 0, 0);
			break;
		}
		else
		{
			SpawnSpotFacing(setItemSpawns, 0, 0);
			break;
		}
		terminate;

		maxAttempts++;
	}
}
